## 00. Quick Start

In [1]:
print('Concept Portfolio V2 Lab — 기본 MODE는 MOCK입니다.')
print('LIVE는 06→28 순서의 staged 검증 후 46의 가드를 직접 켜야 합니다.')

Concept Portfolio V2 Lab — 기본 MODE는 MOCK입니다.
LIVE는 06→28 순서의 staged 검증 후 46의 가드를 직접 켜야 합니다.

## 01. Environment

In [2]:
import os, sys, json
from pathlib import Path
from IPython.display import display
SEARCH_ROOTS = [Path.cwd(), *Path.cwd().parents]
AI_ROOT = next((p for p in SEARCH_ROOTS if (p / 'app').is_dir()), None)
if AI_ROOT is None: AI_ROOT = next((p / 'ai' for p in SEARCH_ROOTS if (p / 'ai' / 'app').is_dir()))
if str(AI_ROOT) not in sys.path: sys.path.insert(0, str(AI_ROOT))
print({'python': sys.version.split()[0], 'aiRoot': str(AI_ROOT)})

{'python': '3.14.5', 'aiRoot': 'C:\\Users\\seewo\\Desktop\\big_proj_01\\new_3\\ai'}

## 02. MODE

In [3]:
MODE = 'LIVE'  # MOCK | REPLAY | LIVE
RECORDINGS_DIR = AI_ROOT / 'recordings' / 'concept_portfolio_v2'
print({'mode': MODE, 'liveExternalOperationsEnabled': MODE == 'LIVE'})

{'mode': 'LIVE', 'liveExternalOperationsEnabled': True}

## 03. Environment Check

In [4]:
LIVE_ENV_KEYS = ['AI_PROVIDER', 'AI_API_KEY', 'AI_MODEL', 'MOLEG_API_KEY', 'LEGAL_REGISTRY_VERSION']
env_status = {key: bool(os.getenv(key)) for key in LIVE_ENV_KEYS}
print(env_status if MODE == 'LIVE' else {'mode': MODE, 'message': '외부 환경변수 불필요'})

{'AI_PROVIDER': True, 'AI_API_KEY': True, 'AI_MODEL': True, 'MOLEG_API_KEY': True, 'LEGAL_REGISTRY_VERSION': True}

## 04. Schema Preflight

In [5]:
from app.concept_portfolio_v2 import ConceptPortfolioEngine, ProviderGateway, ProviderMode
from app.concept_portfolio_v2.adapters import CurrentLegalAdapter
from app.concept_portfolio_v2.diagnostics.notebook_view import *
gateway = ProviderGateway(MODE, recordings_dir=RECORDINGS_DIR)
engine = ConceptPortfolioEngine(MODE, gateway=gateway)
schema_preflight = engine.schema_preflight_report()
display(show_schema_preflight(schema_preflight))
assert schema_preflight.status == 'PASS' and schema_preflight.providerCalls == 0

                          스키마    상태  실패  Provider 호출
0               PlanDraftPool  PASS  []            0
1       ConceptCandidateDraft  PASS  []            0
2  SemanticDistinctnessResult  PASS  []            0
3      SemanticFidelityResult  PASS  []            0

## 05. Input

In [6]:
TEST_INPUT = {
    'ideaOverview': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
    'problem': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다',
    'targetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
}
MAX_CONCEPTS = 5

## 06. Idea Brief Derivation

In [7]:
engine._reset()
seed = engine.seed_adapter.adapt(TEST_INPUT)
idea_context = await engine.derive_idea_brief(seed)
print({'ideaCallComplete': True, 'interpretationPresent': bool(seed.interpretation)})

{'ideaCallComplete': True, 'interpretationPresent': True}

## 07. Safety

In [8]:
display(idea_context.safetyReview.model_dump(mode='json'))
assert idea_context.safetyReview.passed

{'decision': 'ALLOW',
 'categories': [],
 'restrictions': [],
 'userFacingReason': '이 아이디어는 안전하며, 개인 맞춤형 식재료 제공과 관련된 문제를 해결하는 데 기여할 수 있습니다.'}

## 08. AI가 이해한 아이디어

In [9]:
display(show_idea_interpretation(idea_context))

                               항목                                 AI 이해 결과
0              interpretedProblem       1~2인 가구에서 발생하는 음식물 쓰레기를 줄이기 위한 문제.
1          interpretedTargetUsers           요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.
2                    usageContext  소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.
3                industryCategory                                   식품 서비스
4                   researchScope           소량 식재료 및 레시피 제공 서비스에 대한 시장 조사.
5           conciseIdeaDefinition         개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.
6      targetRegionInterpretation                          대상 지역은 명시되지 않음.
7  relevantKnownCompetitorContext                            경쟁자는 명시되지 않음.

## 09. Readiness / Summary / commitments

In [10]:
display(show_idea_readiness(idea_context))

{'readiness': {'status': 'READY_FOR_REVIEW',
  'score': 0,
  'missingFieldKeys': []},
 'userFacingSummary': '이 서비스는 개인 맞춤형 소량 식재료를 제공하고, 남은 재료를 활용할 수 있는 레시피를 안내하여 1~2인 가구의 음식물 쓰레기를 줄이는 데 도움을 줄 수 있습니다.',
 'commitmentCandidates': [],
 'contradictions': [],
 'questions': []}

## 10. Seed Analysis

In [11]:
analysis = await engine.analyze_seed(seed)
display(show_seed_analysis(analysis))

        구분                                                  값
0     탐색 폭                                            EXPLORE
1  다양성 수용량                                                  5
2       설명  선택 입력 LOCK 0개로 11개 설계 차원이 열려 있습니다. diversityCa...

## 11. Generic Opportunity Kernel

In [12]:
display(analysis.opportunityKernel.model_dump(mode='json'))

{'problemCore': '1~2인 가구에서 발생하는 음식물 쓰레기를 줄이기 위한 문제.',
 'targetCore': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.',
 'useContexts': ['소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.'],
 'intentComponents': ['개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.'],
 'mustPreserve': ['1~2인 가구에서 발생하는 음식물 쓰레기를 줄이기 위한 문제.',
  '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.',
  '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.'],
 'maySpecialize': ['핵심 대상의 의미 있는 하위 세그먼트',
  '핵심 사용 맥락의 구체화',
  '가치 제안 또는 offer의 구체화'],
 'forbiddenDriftSummary': '핵심 문제와 대상이 모두 무관한 기회로 교체되면 범위를 벗어납니다.'}

## 12. Design Space

In [13]:
display(show_design_space(analysis))

,분류,필드,값
0,SOURCE_LOCK,ideaOverview,개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스
1,SOURCE_LOCK,problem,1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다
2,SOURCE_LOCK,targetUsers,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구
3,SEMANTIC_ANCHOR,ideaOverview,개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스
4,SEMANTIC_ANCHOR,problem,1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다
5,SEMANTIC_ANCHOR,targetUsers,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구
6,OPEN,solutionMechanism,변경 가능
7,OPEN,valueDelivery,변경 가능
8,OPEN,operatingModel,변경 가능
9,OPEN,supplyStructure,변경 가능
10,OPEN,partnerModel,변경 가능
11,OPEN,transactionFlow,변경 가능
12,OPEN,fulfillment,변경 가능
13,OPEN,platformRole,변경 가능
14,OPEN,commercialFlow,변경 가능
15,OPEN,dataDependency,변경 가능
16,OPEN,physicalDependency,변경 가능

## 13. Generate and Adaptively Replenish Plan Pool

In [14]:
plan_validation = await engine.prepare_portfolio_plans(seed, analysis, max_concepts=MAX_CONCEPTS)
plans = engine._last_plan_pool
print({'totalPlans': len(plans), 'planningRounds': plan_validation.planningRounds,
       'replenishmentRequested': plan_validation.replenishmentRequested})

{'totalPlans': 7, 'planningRounds': 1, 'replenishmentRequested': 0}

## 14. Plan Count / Adaptive Replenishment Check

In [15]:
display(show_plan_pool_status(engine._last_plan_pool_status))
display({'planningRounds': plan_validation.planningRounds,
         'replenishmentRequested': plan_validation.replenishmentRequested,
         'adaptiveReplenishmentUsed': plan_validation.planningRounds > 1})

,requestedPoolSize,returnedPoolSize,initialTarget,reserveTarget,reserveAvailable,status
0,7,7,5,2,2,RESERVE_READY

{'planningRounds': 1,
 'replenishmentRequested': 0,
 'adaptiveReplenishmentUsed': False}

## 15. Korean Plan Display

In [16]:
display(show_portfolio_plans(plans))

,planId,제목,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P1,소량 맞춤형 식재료 서비스,직접 운영 · 자체 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료를 제공하여 음식물 쓰레기를 줄이고 요리를 간편하게 한다,소량의 식재료와 레시피를 통해 요리의 즐거움을 제공한다,개인 맞춤형 식재료와 레시피를 통해 1~2인 가구의 요리 문제를 해결한다,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",1~2인 가구의 요리 문제를 해결하기 위한 혁신적인 접근 방식.
1,P2,간편 요리 레시피 서비스,직접 운영 · 자체 운영,요리할 시간이 부족한 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,간편한 요리 레시피로 요리의 부담을 줄인다,소량 식재료와 함께 제공되는 간편한 레시피로 요리를 쉽게 한다,소량 식재료와 레시피를 통해 요리의 접근성을 높인다,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",요리의 접근성을 높이고 음식물 쓰레기를 줄이는 혁신적인 서비스.
2,P3,1~2인 가구 맞춤형 요리 키트,직접 운영 · 자체 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 재료와 레시피를 한 번에 제공하여 요리를 간편하게 한다,요리 키트를 통해 요리의 번거로움을 줄인다,소량 식재료와 레시피를 통해 요리의 효율성을 높인다,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",1~2인 가구의 요리 문제를 해결하기 위한 혁신적인 접근 방식.
3,P4,음식물 쓰레기 감소 프로그램,직접 운영 · 자체 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,음식물 쓰레기를 줄이는 데 도움을 주는 서비스,소량 식재료와 레시피를 통해 음식물 쓰레기를 줄인다,음식물 쓰레기 감소를 위한 맞춤형 솔루션 제공,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",음식물 쓰레기 문제를 해결하기 위한 혁신적인 접근 방식.
4,P5,요리 시간 단축 서비스,직접 운영 · 자체 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,요리 시간을 단축시켜 주는 서비스,소량 식재료와 레시피를 통해 요리 시간을 줄인다,요리 시간 단축을 위한 맞춤형 솔루션 제공,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",요리 시간을 단축시키기 위한 혁신적인 접근 방식.
5,P6,소량 식재료 구독 서비스,직접 운영 · 자체 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,정기적으로 필요한 만큼의 식재료를 제공하여 음식물 쓰레기를 줄인다,소량 식재료 구독 서비스를 통해 요리의 번거로움을 줄인다,정기적인 소량 식재료 제공으로 요리의 효율성을 높인다,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",소량 식재료 제공을 통한 음식물 쓰레기 문제 해결.
6,P7,요리의 즐거움 증진 서비스,직접 운영 · 자체 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,요리의 즐거움을 높여 음식물 쓰레기를 줄인다,소량 식재료와 레시피를 통해 요리의 즐거움을 증진시킨다,요리의 즐거움을 높이는 맞춤형 솔루션 제공,"{'businessRole': 'PRINCIPAL_OPERATOR', 'operat...",요리의 즐거움을 높이기 위한 혁신적인 접근 방식.

## 16. Plan Lock/Intent Validation

In [17]:
display({'accepted': [p.planId for p in plan_validation.acceptedPlans],
         'rejected': [p.model_dump(mode='json') for p in plan_validation.rejectedPlans]})

{'accepted': ['P1', 'P2', 'P3', 'P4', 'P5'], 'rejected': []}

## 17. Portfolio Family / Variant / Distinct

In [18]:
display(show_plan_diversity(plan_validation.diversity))

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,P1,P2,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, d...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,P1,P3,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,P2,P3,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, d...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,P1,P4,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, da...","transactionModel, monetizationModel, deliveryM...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
4,P2,P4,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, transactionModel...","partnerModel, monetizationModel, deliveryModel...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
5,P3,P4,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, da...","transactionModel, monetizationModel, deliveryM...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,P1,P5,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, dataDependency, ...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,P2,P5,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, tr...","monetizationModel, deliveryModel, targetSegmen...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
8,P3,P5,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, dataDependency, ...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,P4,P5,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, solution...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
10,P1,P6,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, de...","monetizationModel, valuePropositionThesis, off...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
11,P2,P6,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, m...","partnerModel, transactionModel, customerIntera...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
12,P3,P6,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, de...","monetizationModel, valuePropositionThesis, off...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
13,P4,P6,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, da...","transactionModel, monetizationModel, deliveryM...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
14,P5,P6,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, dataDependency, ...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
15,P1,P7,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, dataDependency, ...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
16,P2,P7,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, tr...","monetizationModel, deliveryModel, targetSegmen...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
17,P3,P7,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, dataDependency, ...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
18,P4,P7,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
19,P5,P7,VARIANT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
20,P6,P7,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, dataDependency, ...","partnerModel, transactionModel, monetizationMo...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.

## 18. Selected + Reserve Plans

In [19]:
selected_plans = plan_validation.acceptedPlans
reserve_plans = plan_validation.reservePlans
display({'selected': [p.planId for p in selected_plans], 'reserve': [p.planId for p in reserve_plans]})

{'selected': ['P1', 'P2', 'P3', 'P4', 'P5'], 'reserve': ['P6', 'P7']}

## 19. Candidate 1

In [20]:
candidate_one = await engine.expand_plan(seed, selected_plans[0], 1) if selected_plans else None
display(show_candidates([candidate_one]) if candidate_one else [])

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,소량 맞춤형 식재료 서비스,개인 맞춤형 식재료와 레시피를 통해 1~2인 가구의 요리 문제를 해결한다.,직접 운영 · 자체 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델을 통한 지속적인 수익 창출,소량 식재료의 효율적인 공급망 관리

## 20. Candidate 1 Korean/Governance

In [21]:
candidate_one_accepted, candidate_one_reports = await engine.validate_candidates(
    seed, selected_plans[:1], [candidate_one]) if candidate_one else ([], [])
display(show_candidate_validation(candidate_one_reports))

,candidateId,schemaValid,hardLockPreserved,semanticAnchorPreserved,planFidelity,anchorDecision,fidelityDecision,contentLanguageValid,accepted,reasonCodes,safeSummary
0,C1,True,True,True,True,PASS,ADAPTED,True,True,[],검사 통과

## 21. Candidate 1 Actual Generic Descriptor

In [22]:
display(show_concept_descriptors([candidate_one]) if candidate_one else [])

,entityId,family,dimension,code
0,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,businessRole,PRINCIPAL_OPERATOR
1,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,operatingModel,OWN_OPERATED
2,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,partnerModel,PARTNER_NETWORK
3,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,deliveryModel,PHYSICAL_DELIVERY
4,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,transactionModel,ONE_OFF
5,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,monetizationModel,SUBSCRIPTION
6,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,customerInteractionModel,OTHER
7,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,dataDependency,MATERIAL
8,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,physicalDependency,MATERIAL

## 22. Candidate 1 Fidelity

In [23]:
display(show_candidate_validation(candidate_one_reports))

,candidateId,schemaValid,hardLockPreserved,semanticAnchorPreserved,planFidelity,anchorDecision,fidelityDecision,contentLanguageValid,accepted,reasonCodes,safeSummary
0,C1,True,True,True,True,PASS,ADAPTED,True,True,[],검사 통과

## 23. Remaining Candidates

In [24]:
remaining_candidates = []
for i, plan in enumerate(selected_plans[1:], 2):
    remaining_candidates.append(await engine.expand_plan(seed, plan, i))
candidate_drafts = ([candidate_one] if candidate_one else []) + remaining_candidates
display(show_candidates(candidate_drafts))

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,소량 맞춤형 식재료 서비스,개인 맞춤형 식재료와 레시피를 통해 1~2인 가구의 요리 문제를 해결한다.,직접 운영 · 자체 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델을 통한 지속적인 수익 창출,소량 식재료의 효율적인 공급망 관리
1,C2,L2,None,간편 요리 레시피 서비스,소량 식재료와 레시피를 통해 요리의 접근성을 높인다.,직접 운영 · 자체 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,레시피 구매 시 식재료 할인 제공,레시피 개발 및 고객 맞춤형 서비스 운영
2,C3,L3,None,1~2인 가구 맞춤형 요리 키트,소량 식재료와 레시피를 통해 요리의 효율성을 높인다.,직접 운영 · 자체 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델을 통한 지속적인 수익 창출,효율적인 재료 조달 및 키트 구성
3,C4,L4,None,음식물 쓰레기 감소 프로그램,고객의 소비 패턴 분석 및 맞춤형 제안,거래 중개 · 자체 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,서비스 이용 시 할인 제공,고객 맞춤형 데이터 분석 및 서비스 제공
4,C5,L5,None,요리 시간 단축 서비스,고객의 요리 스타일 분석 및 맞춤형 제안,거래 중개 · 자체 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,서비스 이용 시 할인 제공,주문 후 3일 이내 서비스 제공

## 24. Candidate Actual Generic Descriptors

In [25]:
display(show_concept_descriptors(candidate_drafts))

,entityId,family,dimension,code
0,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,businessRole,PRINCIPAL_OPERATOR
1,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,operatingModel,OWN_OPERATED
2,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,partnerModel,PARTNER_NETWORK
3,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,deliveryModel,PHYSICAL_DELIVERY
4,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,transactionModel,ONE_OFF
5,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,monetizationModel,SUBSCRIPTION
6,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,customerInteractionModel,OTHER
7,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,dataDependency,MATERIAL
8,C1,PRINCIPAL_OPERATOR:OWN_OPERATED,physicalDependency,MATERIAL
9,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,businessRole,PRINCIPAL_OPERATOR
10,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,operatingModel,OWN_OPERATED
11,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,partnerModel,EXPERT_NETWORK
12,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,deliveryModel,PHYSICAL_DELIVERY
13,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,transactionModel,ONE_OFF
14,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,monetizationModel,DIRECT_SALE
15,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,customerInteractionModel,OTHER
16,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,dataDependency,MATERIAL
17,C2,PRINCIPAL_OPERATOR:OWN_OPERATED,physicalDependency,MATERIAL
18,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,businessRole,PRINCIPAL_OPERATOR
19,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,operatingModel,OWN_OPERATED
20,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,partnerModel,PARTNER_NETWORK
21,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,deliveryModel,PHYSICAL_DELIVERY
22,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,transactionModel,ONE_OFF
23,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,monetizationModel,SUBSCRIPTION
24,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,customerInteractionModel,OTHER
25,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,dataDependency,MATERIAL
26,C3,PRINCIPAL_OPERATOR:OWN_OPERATED,physicalDependency,MATERIAL
27,C4,INTERMEDIARY:OWN_OPERATED,businessRole,INTERMEDIARY
28,C4,INTERMEDIARY:OWN_OPERATED,operatingModel,OWN_OPERATED
29,C4,INTERMEDIARY:OWN_OPERATED,partnerModel,PARTNER_NETWORK
30,C4,INTERMEDIARY:OWN_OPERATED,deliveryModel,PHYSICAL_DELIVERY
31,C4,INTERMEDIARY:OWN_OPERATED,transactionModel,ONE_OFF
32,C4,INTERMEDIARY:OWN_OPERATED,monetizationModel,OTHER
33,C4,INTERMEDIARY:OWN_OPERATED,customerInteractionModel,OTHER
34,C4,INTERMEDIARY:OWN_OPERATED,dataDependency,MATERIAL
35,C4,INTERMEDIARY:OWN_OPERATED,physicalDependency,MATERIAL
36,C5,INTERMEDIARY:OWN_OPERATED,businessRole,INTERMEDIARY
37,C5,INTERMEDIARY:OWN_OPERATED,operatingModel,OWN_OPERATED
38,C5,INTERMEDIARY:OWN_OPERATED,partnerModel,EXPERT_NETWORK
39,C5,INTERMEDIARY:OWN_OPERATED,deliveryModel,DIGITAL
40,C5,INTERMEDIARY:OWN_OPERATED,transactionModel,ONE_OFF
41,C5,INTERMEDIARY:OWN_OPERATED,monetizationModel,SUBSCRIPTION
42,C5,INTERMEDIARY:OWN_OPERATED,customerInteractionModel,OTHER
43,C5,INTERMEDIARY:OWN_OPERATED,dataDependency,MATERIAL
44,C5,INTERMEDIARY:OWN_OPERATED,physicalDependency,MATERIAL

## 25. Candidate Portfolio Relations

In [26]:
candidates, candidate_reports = await engine.validate_candidates(seed, selected_plans, candidate_drafts)
candidate_pairwise = [engine.compare_candidates(candidates[i], candidates[j])
                      for i in range(len(candidates)) for j in range(i + 1, len(candidates))]
display(show_plan_diversity(candidate_pairwise))

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,C1,C2,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, t...","partnerModel, monetizationModel, useCaseThesis...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,C1,C3,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,C2,C3,DISTINCT,PRINCIPAL_OPERATOR:OWN_OPERATED,PRINCIPAL_OPERATOR:OWN_OPERATED,"businessRole, operatingModel, deliveryModel, t...","partnerModel, monetizationModel, valueProposit...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.

## 26. Structural Legal Precheck

In [27]:
prechecks = [engine.legal_precheck(item) for item in candidates]
display(show_legal_precheck(prechecks))

,candidateId,label,directSeller,intermediary,regulatedPhysicalActivity,personalDataDependency,qualificationDependency,riskHints
0,C1,Structural risk precheck — not final legal review,True,False,True,True,True,"[물리 활동, 개인정보, 자격 의존]"
1,C2,Structural risk precheck — not final legal review,True,False,True,True,True,"[물리 활동, 개인정보, 자격 의존]"
2,C3,Structural risk precheck — not final legal review,True,False,True,True,True,"[물리 활동, 개인정보, 자격 의존]"

## 27. Legal C1 Evidence Summary

In [28]:
legal_adapter = CurrentLegalAdapter()
legal_c1_input = legal_adapter.task_input(candidates[0].candidate, seed) if candidates else None
display({'candidateId': candidates[0].candidateId if candidates else None,
         'externalFacts': legal_c1_input['externalFactContext']['facts'] if legal_c1_input else [],
         'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'})

{'candidateId': 'C1',
 'externalFacts': [],
 'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'}

## 28. Full Legal C1

In [29]:
RUN_FULL_LEGAL_C1 = False  # staged LIVE 확인 후 True
legal_one = None
if RUN_FULL_LEGAL_C1 and candidates:
    try:
        legal_one = await engine.review_legal_candidate(seed, candidates[0])
        display(show_legal_result([legal_one]))
    except Exception:
        display(show_legal_failure(candidates[0].candidateId, engine.gateway))
else:
    print('SKIPPED — RUN_FULL_LEGAL_C1=True로 명시해야 실행됩니다.')

SKIPPED — RUN_FULL_LEGAL_C1=True로 명시해야 실행됩니다.

## 29. Remaining Legal

In [30]:
RUN_REMAINING_LEGAL = False
legal_remaining = []
if RUN_REMAINING_LEGAL and legal_one and len(candidates) > 1:
    legal_remaining = await engine.review_legal(seed, candidates[1:])
display(show_legal_result(legal_remaining) if legal_remaining else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}

## 30. Redesign

In [31]:
legal_initial = ([legal_one] if legal_one else []) + legal_remaining
portfolio, legal_all, required_inputs, redesigned_count, replanned_count = ([], legal_initial, [], 0, 0)
if len(legal_initial) == len(candidates) and candidates:
    portfolio, legal_all, required_inputs, redesigned_count, replanned_count = await engine.resolve_legal(
        seed, selected_plans, candidates, legal_initial)
print({'redesigned': redesigned_count})

{'redesigned': 0}

## 31. Replan

In [32]:
display(show_replan(type('PortfolioView', (), {'concepts': portfolio})()))
print({'replanned': replanned_count, 'reserveAvailable': len(reserve_plans)})

Empty DataFrame
Columns: []
Index: []

{'replanned': 0, 'reserveAvailable': 2}

## 32. Final Portfolio

In [33]:
display(show_final_portfolio(type('PortfolioView', (), {'concepts': portfolio})()) if portfolio else {'status': 'LEGAL_PENDING'})

{'status': 'LEGAL_PENDING'}

## 33. Unresolved Candidate Summary

In [34]:
display(required_inputs if required_inputs else {'unresolved': []})

{'unresolved': []}

## 34. Manual Concept Selection

In [35]:
SELECTED_CANDIDATE_ID = portfolio[0].candidateId if portfolio else None  # 사용자가 수정
selected_concept = next((item for item in portfolio if item.candidateId == SELECTED_CANDIDATE_ID), None)
print({'selectedCandidateId': SELECTED_CANDIDATE_ID})

{'selectedCandidateId': None}

## 35. 7 Hypotheses

In [36]:
hypotheses = engine.build_or_load_current_hypothesis_contract(selected_concept) if selected_concept else []
display(show_hypotheses(hypotheses))

Empty DataFrame
Columns: []
Index: []

## 36. Confirm / Edit

In [37]:
CONFIRM_ALL_PROPOSED = False
HYPOTHESIS_EDITS = {
    # 'PRICE': '월 17,900원',
}
confirmed_hypotheses = engine.confirm_hypotheses(
    hypotheses, HYPOTHESIS_EDITS, confirm_all_proposed=CONFIRM_ALL_PROPOSED) if hypotheses else []
display(show_hypotheses(confirmed_hypotheses))

Empty DataFrame
Columns: []
Index: []

## 37. Actual Delta Legal

In [38]:
RUN_DELTA_LEGAL = False
delta_legal_result = None
if RUN_DELTA_LEGAL and selected_concept and any(h.deltaLegalRequired for h in confirmed_hypotheses):
    delta_legal_result = await engine.review_delta_legal(seed, selected_concept, confirmed_hypotheses)
    confirmed_hypotheses = engine.mark_delta_legal_reviewed(confirmed_hypotheses, delta_legal_result)
display(delta_legal_result.model_dump(mode='json') if delta_legal_result else {'status': 'NOT_REQUIRED_OR_SKIPPED'})

{'status': 'NOT_REQUIRED_OR_SKIPPED'}

## 38. Market Seed

In [39]:
handoff = None
if selected_concept and legal_all:
    handoff = engine.build_downstream_handoff(seed, selected_concept, confirmed_hypotheses, legal_all)
display(handoff.marketAnalysisSeedSnapshot if handoff else {'status': 'NOT_READY'})

{'status': 'NOT_READY'}

## 39. Marketing Source

In [40]:
display(handoff.marketingSourceSnapshot if handoff else {'status': 'NOT_READY'})

{'status': 'NOT_READY'}

## 40. Contract Compatibility

In [41]:
display(show_downstream_handoff(handoff) if handoff else {'contract': 'NOT_READY'})

{'contract': 'NOT_READY'}

## 41. Trace

In [42]:
display(show_trace(engine.trace))

,순서,시각,stage,action,entity,parent,status,mode,호출,요약,decision,reasonCode
0,1,2026-08-09T23:08:27.035455+00:00,CREATED,CREATED,NaN,NaN,RUNNING,LIVE,NaN,V2 Lab 실행을 생성했습니다.,None,NaN
1,2,2026-08-09T23:08:31.375348+00:00,SAFETY_CHECKING,IDEA_BRIEF_DERIVED,NaN,NaN,PASS,LIVE,1.0,Idea interpretation/readiness를 보존했습니다: READY_F...,None,NaN
2,3,2026-08-09T23:08:31.411191+00:00,SEED_ANALYZING,ANALYZED,lab-idea-brief,NaN,PASS,LIVE,NaN,필수 3개와 LOCK 3개를 분류했습니다.,None,NaN
3,4,2026-08-09T23:08:31.411396+00:00,SEED_ANALYZING,DESIGN_SPACE_READY,NaN,NaN,PASS,LIVE,NaN,Open=11 Constrained=0 Breadth=EXPLORE,None,NaN
4,5,2026-08-09T23:08:31.461028+00:00,PLANNING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,최대 5개 동적 plan을 요청합니다.,None,NaN
5,6,2026-08-09T23:08:50.515663+00:00,PLANNING,DRAFTS_GENERATED,NaN,NaN,PASS,LIVE,2.0,Plan draft pool=7,None,NaN
6,7,2026-08-09T23:08:50.519116+00:00,PLANNING,NORMALIZED,NaN,NaN,PASS,LIVE,NaN,System metadata를 부여한 Plan=7,None,NaN
7,8,2026-08-09T23:08:50.519145+00:00,PLAN_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Opportunity·LOCK·DUPLICATE/VARIANT/DISTINCT 관계...,None,NaN
8,9,2026-08-09T23:08:53.046275+00:00,PLAN_VALIDATING,SELECTED,NaN,NaN,PASS,LIVE,NaN,Plans=5 Rejected=0,None,NaN
9,10,2026-08-09T23:09:00.564426+00:00,EXPANDING,EXPANDED,C1,P1,PASS,LIVE,4.0,P1 → C1,None,NaN
10,11,2026-08-09T23:09:00.576883+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,None,NaN
11,12,2026-08-09T23:09:00.577242+00:00,CANDIDATE_VALIDATING,VALIDATED,C1,NaN,PASS,LIVE,NaN,검사 통과,None,NaN
12,13,2026-08-09T23:09:07.794970+00:00,EXPANDING,EXPANDED,C2,P2,PASS,LIVE,5.0,P2 → C2,None,NaN
13,14,2026-08-09T23:09:15.059690+00:00,EXPANDING,EXPANDED,C3,P3,PASS,LIVE,6.0,P3 → C3,None,NaN
14,15,2026-08-09T23:09:22.423760+00:00,EXPANDING,EXPANDED,C4,P4,PASS,LIVE,7.0,P4 → C4,None,NaN
15,16,2026-08-09T23:09:28.845783+00:00,EXPANDING,EXPANDED,C5,P5,PASS,LIVE,8.0,P5 → C5,None,NaN
16,17,2026-08-09T23:09:28.876048+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,None,NaN
17,18,2026-08-09T23:09:28.877171+00:00,CANDIDATE_VALIDATING,VALIDATED,C1,NaN,PASS,LIVE,NaN,검사 통과,None,NaN
18,19,2026-08-09T23:09:28.878249+00:00,CANDIDATE_VALIDATING,VALIDATED,C2,NaN,PASS,LIVE,NaN,검사 통과,None,NaN
19,20,2026-08-09T23:09:28.878914+00:00,CANDIDATE_VALIDATING,VALIDATED,C3,NaN,PASS,LIVE,NaN,검사 통과,None,NaN
20,21,2026-08-09T23:09:28.879699+00:00,CANDIDATE_VALIDATING,VALIDATED,C4,NaN,REJECTED,LIVE,NaN,PLAN_FIDELITY_FAILED,None,PLAN_FIDELITY_FAILED
21,22,2026-08-09T23:09:28.880155+00:00,CANDIDATE_VALIDATING,VALIDATED,C5,NaN,REJECTED,LIVE,NaN,PLAN_FIDELITY_FAILED,None,PLAN_FIDELITY_FAILED

## 42. Provider/Legal Usage

In [43]:
display(show_provider_usage(engine.gateway.usage))
print('상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.')

,논리 작업,상위 외부 작업,논리 stage별,상위 외부 작업 stage별,재시도,소요(ms),모드별,token,보고 비용
0,8,8,"{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'DISTINC...","{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'DISTINC...",0,61551,{'LIVE': 8},None,None

상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.

## 43. Replay Manifest

In [44]:
display(show_replay_manifest(engine.gateway))

{'status': 'REPLAY_PARTIAL',
 'entries':                 operation                                               hash  \
 0               PLAN_POOL  03b73ea7d485636893670a848e28d49e239cc8bc0c5239...
 1       SEMANTIC_RELATION  05680e1eabb667cd53d8bbde75192650b626fd5dfaa3fd...
 2   IDEA_BRIEF_DERIVATION  07c6209c7795158bce16bf1d386c8f6cd1322277337ef9...
 3                  EXPAND  1af5fde74ee67196097d4ed11be725ac3964b73a8255f9...
 4                  EXPAND  3c5d54226c8e1dc67a781ee23b621f351adc0856e1bf95...
 5                  EXPAND  56691ac0644f2037ba4073abb93e5c41db18feb2695b74...
 6                  EXPAND  5ea7858cc4a88f9b3cf7f584ca6c4ef6ffd65b9825722d...
 7                  EXPAND  803c35256a386c06a427b5dc9bec4638ecdb98007a597c...
 8                  EXPAND  8153e8981bf092861864149480a7a14306dd5747ae563f...
 9                  EXPAND  945dade2f5ba6344e63dfed5e609ecf02c92ae92a51ad2...
 10                 EXPAND  9f1396fec8ea20c3c32e9c46d343e153d671147c2ad81e...
 11              PLAN_POOL  a77ef8dfd8e946c2ce16a423408fc787216aa72ccd38ee...
 12                 EXPAND  b516afbff977d7ecd1fcd44e75f12adff0757b4ea82569...
 13              PLAN_POOL  c98df36191fe679624cf311dd5e671864c0bdedd03a338...
 14                 EXPAND  d2aa5afd9111547a50e0ec850d3f40f68f2b64ebdcdf57...
 15                 EXPAND  fb6986c6b42d538d7e6633cd0b5e8695331b5eab5748d2...

    operationVersion                           promptVersion schemaVersion  \
 0              v2.1             concept-portfolio-plan-v2.1           2.0
 1                v3           concept-portfolio-relation-v3           2.0
 2                v2                   idea-brief-current-v2           2.0
 3               NaN                                     NaN           2.0
 4                v3  concept-portfolio-generic-candidate-v3           2.0
 5                v3  concept-portfolio-generic-candidate-v3           2.0
 6               NaN                                     NaN           2.0
 7                v3  concept-portfolio-generic-candidate-v3           2.0
 8              v2.1        concept-portfolio-candidate-v2.1           2.0
 9               NaN                                     NaN           2.0
 10               v3  concept-portfolio-generic-candidate-v3           2.0
 11               v3       concept-portfolio-generic-plan-v3           2.0
 12               v3  concept-portfolio-generic-candidate-v3           2.0
 13              NaN                                     NaN           2.0
 14              NaN                                     NaN           2.0
 15              NaN                                     NaN           2.0

     recordExists                         timestamp  versionCompatible
 0           True  2026-08-09T22:07:18.877351+00:00               True
 1           True  2026-08-09T23:08:53.044335+00:00               True
 2           True  2026-08-09T23:08:31.374729+00:00               True
 3           True  2026-08-09T15:57:26.931257+00:00              False
 4           True  2026-08-09T23:09:22.421630+00:00               True
 5           True  2026-08-09T23:09:15.058753+00:00               True
 6           True  2026-08-09T15:56:56.379364+00:00              False
 7           True  2026-08-09T23:09:00.553826+00:00               True
 8           True  2026-08-09T22:07:26.091646+00:00               True
 9           True  2026-08-09T15:57:33.741497+00:00              False
 10          True  2026-08-09T23:09:07.793971+00:00               True
 11          True  2026-08-09T23:08:50.513875+00:00               True
 12          True  2026-08-09T23:09:28.844031+00:00               True
 13          True  2026-08-09T15:55:40.653020+00:00              False
 14          True  2026-08-09T15:57:21.293137+00:00              False
 15          True  2026-08-09T15:57:14.211269+00:00              False  }

## 44. One-click MOCK

In [45]:
mock_result = await ConceptPortfolioEngine('MOCK').run_full(
    TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=True)
display(show_run_summary(mock_result))
assert mock_result.handoff and mock_result.handoff.contractStatus == 'CONTRACT_PASS'

,safety,requestedMaximum,planned,planDuplicatesRemoved,candidatesExpanded,legalAccepted,legalRedesigned,replanned,finalPortfolio,portfolioStatus,selectedConcept,downstreamHandoff,providerCalls,totalDurationMs
0,PASS,5,7,0,5,5,0,0,5,READY_FULL,직접 운영 핵심형,PASS,0,33

## 45. One-click REPLAY

In [46]:
RUN_ONE_CLICK_REPLAY = False
replay_result = None
if RUN_ONE_CLICK_REPLAY:
    replay_gateway = ProviderGateway('REPLAY', recordings_dir=RECORDINGS_DIR)
    replay_result = await ConceptPortfolioEngine('REPLAY', gateway=replay_gateway).run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=False)
display(show_run_summary(replay_result) if replay_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}

## 46. One-click LIVE

In [47]:
RUN_ONE_CLICK_LIVE = False
live_result = None
if RUN_ONE_CLICK_LIVE:
    assert MODE == 'LIVE', 'MODE=LIVE를 먼저 명시하세요.'
    assert RUN_FULL_LEGAL_C1 and RUN_REMAINING_LEGAL, 'staged LIVE Legal 확인이 먼저입니다.'
    live_result = await engine.run_full(TEST_INPUT, max_concepts=MAX_CONCEPTS,
                                        auto_confirm_hypotheses=False)
display(show_run_summary(live_result) if live_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}