## 00. Quick Start

In [1]:
print('Concept Portfolio V2 Lab — staged와 one-click은 동일 Core를 사용합니다.')
print('LIVE_TEST_LEVEL로 CORE / LEGAL_C1 / FULL_E2E / ONE_CLICK 중 하나만 선택하세요.')

Concept Portfolio V2 Lab — staged와 one-click은 동일 Core를 사용합니다.
LIVE_TEST_LEVEL로 CORE / LEGAL_C1 / FULL_E2E / ONE_CLICK 중 하나만 선택하세요.

## 01. Environment

In [2]:
import os, sys, json
from pathlib import Path
from IPython.display import display
SEARCH_ROOTS = [Path.cwd(), *Path.cwd().parents]
AI_ROOT = next((p for p in SEARCH_ROOTS if (p / 'app').is_dir()), None)
if AI_ROOT is None: AI_ROOT = next((p / 'ai' for p in SEARCH_ROOTS if (p / 'ai' / 'app').is_dir()))
if str(AI_ROOT) not in sys.path: sys.path.insert(0, str(AI_ROOT))
print({'python': sys.version.split()[0], 'aiRoot': str(AI_ROOT)})

{'python': '3.14.5', 'aiRoot': 'C:\\Users\\seewo\\Desktop\\big_proj_01\\new_3\\ai'}

## 02. MODE

In [3]:
MODE = 'LIVE'  # MOCK | REPLAY | LIVE
RECORDINGS_DIR = AI_ROOT / 'recordings' / 'concept_portfolio_v2'
print({'mode': MODE, 'liveExternalOperationsEnabled': MODE == 'LIVE'})

{'mode': 'LIVE', 'liveExternalOperationsEnabled': True}

## 03. Environment Check

In [4]:
LIVE_ENV_KEYS = ['AI_PROVIDER', 'AI_API_KEY', 'AI_MODEL', 'MOLEG_API_KEY', 'LEGAL_REGISTRY_VERSION']
env_status = {key: bool(os.getenv(key)) for key in LIVE_ENV_KEYS}
print(env_status if MODE == 'LIVE' else {'mode': MODE, 'message': '외부 환경변수 불필요'})

{'AI_PROVIDER': True, 'AI_API_KEY': True, 'AI_MODEL': True, 'MOLEG_API_KEY': True, 'LEGAL_REGISTRY_VERSION': True}

## 04. Schema Preflight

In [5]:
from app.concept_portfolio_v2 import ConceptPortfolioEngine, ProviderGateway, ProviderMode
from app.concept_portfolio_v2.adapters import CurrentLegalAdapter
from app.concept_portfolio_v2.diagnostics.notebook_view import *
gateway = ProviderGateway(MODE, recordings_dir=RECORDINGS_DIR)
engine = ConceptPortfolioEngine(MODE, gateway=gateway)
schema_preflight = engine.schema_preflight_report()
display(show_schema_preflight(schema_preflight))
assert schema_preflight.status == 'PASS' and schema_preflight.providerCalls == 0

                                스키마    상태  실패  Provider 호출
0                     PlanDraftPool  PASS  []            0
1             ConceptCandidateDraft  PASS  []            0
2        SemanticDistinctnessResult  PASS  []            0
3            SemanticFidelityResult  PASS  []            0
4         SemanticArchitectureBatch  PASS  []            0
5           SemanticHypothesisBatch  PASS  []            0
6         BusinessRoleSemanticBatch  PASS  []            0
7  LegalFactDependencySemanticBatch  PASS  []            0
8          LegalFactCompletionPatch  PASS  []            0

## 05. Input

In [6]:
SCENARIO_FILE = AI_ROOT / 'fixtures' / 'concept_portfolio_v2' / 'live_scenarios.json'
SCENARIOS = {item['scenarioId']: item for item in json.loads(SCENARIO_FILE.read_text(encoding='utf-8'))}
LIVE_SCENARIO = 'WEEKEND_TRIP_PLANNER'
LIVE_TEST_LEVEL = 'FULL_E2E'  # CORE | LEGAL_C1 | FULL_E2E | ONE_CLICK
RUN_STAGED_CORE = LIVE_TEST_LEVEL in {'CORE', 'LEGAL_C1', 'FULL_E2E'}
RUN_STAGED_LEGAL = LIVE_TEST_LEVEL in {'LEGAL_C1', 'FULL_E2E'}
RUN_STAGED_FULL = LIVE_TEST_LEVEL == 'FULL_E2E'
scenario = SCENARIOS[LIVE_SCENARIO]
TEST_INPUT = {key: scenario[key] for key in ('ideaOverview', 'problem', 'targetUsers')}
MAX_CONCEPTS = 5
display({'scenario': LIVE_SCENARIO, 'testLevel': LIVE_TEST_LEVEL, 'domain': scenario['domain'],
         'expectedStructuralFeatures': scenario['expectedStructuralFeatures']})

{'scenario': 'WEEKEND_TRIP_PLANNER',
 'testLevel': 'FULL_E2E',
 'domain': 'Travel planning',
 'expectedStructuralFeatures': ['디지털 계획', '예약 연결 역할과 직접 판매 구분']}

## 06. Idea Brief Derivation

In [7]:
seed = engine.seed_adapter.adapt(TEST_INPUT)
idea_context = None
if RUN_STAGED_CORE:
    engine._reset()
    idea_context = await engine.derive_idea_brief(seed)
print({'ideaCallComplete': bool(idea_context), 'interpretationPresent': bool(seed.interpretation),
       'stagedCore': RUN_STAGED_CORE})

{'ideaCallComplete': True, 'interpretationPresent': True, 'stagedCore': True}

## 07. Safety

In [8]:
display(idea_context.safetyReview.model_dump(mode='json') if idea_context else {'status': 'SKIPPED'})
assert idea_context is None or idea_context.safetyReview.passed

{'decision': 'ALLOW',
 'categories': [],
 'restrictions': [],
 'userFacingReason': '이 아이디어는 안전하며, 여행 계획 서비스를 제공하는 것으로 보입니다.'}

## 08. AI가 이해한 아이디어

In [9]:
display(show_idea_interpretation(idea_context) if idea_context else {'status': 'SKIPPED'})

,항목,AI 이해 결과
0,interpretedProblem,짧은 주말 여행을 계획하는 데 소요되는 시간과 노력을 줄이는 것.
1,interpretedTargetUsers,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.
2,usageContext,사용자의 이동 가능 시간과 관심사를 고려하여 여행 일정을 자동으로 구성하는 서비스.
3,industryCategory,여행 및 관광
4,researchScope,주말 여행 계획 서비스에 대한 시장 조사.
5,conciseIdeaDefinition,사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동으로 구성...
6,targetRegionInterpretation,대상 지역은 명시되지 않음.
7,relevantKnownCompetitorContext,경쟁자는 명시되지 않음.

## 09. Readiness / Summary / commitments

In [10]:
display(show_idea_readiness(idea_context) if idea_context else {'status': 'SKIPPED'})

{'readiness': {'status': 'READY_FOR_REVIEW',
  'score': 0,
  'missingFieldKeys': []},
 'readinessDiagnostic': 'READINESS_INCONSISTENT',
 'userFacingSummary': '이 아이디어는 사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동으로 구성하는 여행 계획 서비스입니다.',
 'commitmentCandidates': [],
 'contradictions': [],
 'questions': []}

## 10. Seed Analysis

In [11]:
analysis = await engine.analyze_seed(seed) if RUN_STAGED_CORE else None
display(show_seed_analysis(analysis) if analysis else {'status': 'SKIPPED'})

        구분                                                  값
0     탐색 폭                                            EXPLORE
1  다양성 수용량                                                  5
2       설명  선택 입력 LOCK 0개로 11개 설계 차원이 열려 있습니다. diversityCa...

## 11. Generic Opportunity Kernel

In [12]:
display(analysis.opportunityKernel.model_dump(mode='json') if analysis else {'status': 'SKIPPED'})

{'problemCore': '짧은 주말 여행을 계획하는 데 소요되는 시간과 노력을 줄이는 것.',
 'targetCore': '주말에 1~2일 단기 여행을 자주 계획하는 직장인들.',
 'useContexts': ['사용자의 이동 가능 시간과 관심사를 고려하여 여행 일정을 자동으로 구성하는 서비스.'],
 'intentComponents': ['사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동으로 구성하는 서비스.'],
 'mustPreserve': ['짧은 주말 여행을 계획하는 데 소요되는 시간과 노력을 줄이는 것.',
  '주말에 1~2일 단기 여행을 자주 계획하는 직장인들.',
  '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동으로 구성하는 서비스.'],
 'maySpecialize': ['핵심 대상의 의미 있는 하위 세그먼트',
  '핵심 사용 맥락의 구체화',
  '가치 제안 또는 offer의 구체화'],
 'forbiddenDriftSummary': '핵심 문제와 대상이 모두 무관한 기회로 교체되면 범위를 벗어납니다.'}

## 12. Design Space

In [13]:
display(show_design_space(analysis) if analysis else {'status': 'SKIPPED'})

,분류,필드,값
0,SOURCE_LOCK,ideaOverview,사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고...
1,SOURCE_LOCK,problem,짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.
2,SOURCE_LOCK,targetUsers,주말 1~2일 단기 여행을 자주 계획하는 직장인
3,SEMANTIC_ANCHOR,ideaOverview,사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고...
4,SEMANTIC_ANCHOR,problem,짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.
5,SEMANTIC_ANCHOR,targetUsers,주말 1~2일 단기 여행을 자주 계획하는 직장인
6,OPEN,solutionMechanism,변경 가능
7,OPEN,valueDelivery,변경 가능
8,OPEN,operatingModel,변경 가능
9,OPEN,supplyStructure,변경 가능
10,OPEN,partnerModel,변경 가능
11,OPEN,transactionFlow,변경 가능
12,OPEN,fulfillment,변경 가능
13,OPEN,platformRole,변경 가능
14,OPEN,commercialFlow,변경 가능
15,OPEN,dataDependency,변경 가능
16,OPEN,physicalDependency,변경 가능

## 13. Generate and Adaptively Replenish Plan Pool

In [14]:
plan_validation = (await engine.prepare_portfolio_plans(seed, analysis, max_concepts=MAX_CONCEPTS)
                   if RUN_STAGED_CORE else None)
plans = engine._last_plan_pool if plan_validation else []
print({'totalPlans': len(plans),
       'planningRounds': plan_validation.planningRounds if plan_validation else 0,
       'replenishmentRequested': plan_validation.replenishmentRequested if plan_validation else 0})

{'totalPlans': 6, 'planningRounds': 1, 'replenishmentRequested': 0}

## 14. Plan Count / Adaptive Replenishment Check

In [15]:
display(show_plan_pool_status(engine._last_plan_pool_status) if plan_validation else {'status': 'SKIPPED'})
display({'planningRounds': plan_validation.planningRounds if plan_validation else 0,
         'replenishmentRequested': plan_validation.replenishmentRequested if plan_validation else 0,
         'adaptiveReplenishmentUsed': bool(plan_validation and plan_validation.planningRounds > 1)})

,requestedPoolSize,returnedPoolSize,initialTarget,reserveTarget,reserveAvailable,status
0,7,6,5,2,1,RESERVE_SHORTFALL

{'planningRounds': 1,
 'replenishmentRequested': 0,
 'adaptiveReplenishmentUsed': False}

## 15. Korean Plan Display

In [16]:
display(show_portfolio_plans(plan_validation.acceptedPlans + plan_validation.reservePlans)
        if plan_validation else {'status': 'SKIPPED'})

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P1,주말 여행 자동 계획 서비스,SELECTED,0.9035,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 이동 가능 시간과 관심사를 고려하여 여행 일정을 자동으로 구성하는 서비스.,"사용자는 여행 계획에 소요되는 시간을 절약하고, 더 많은 시간을 여행에 할애할 수 있다.",사용자의 이동 가능 시간과 관심사를 기반으로 최적의 여행 일정을 자동으로 생성하여 ...,자동으로 생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...","주말 여행 계획의 효율성을 높이고, 사용자 경험을 개선하기 위해."
1,P4,주말 여행 계획 지원 서비스,SELECTED,0.8399,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 이동 가능 시간과 관심사를 고려하여 여행 계획을 지원하는 서비스.,사용자는 여행 계획을 쉽게 진행할 수 있다.,여행 계획을 지원하여 사용자의 편의를 높인다.,자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",여행 계획의 편리함을 제공하여 사용자 경험을 개선하기 위해.
2,P3,주말 여행 일정 최적화 서비스,SELECTED,0.6773,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 이동 가능 시간과 관심사를 고려하여 최적화된 여행 일정을 제공하는 서비스.,"사용자는 여행 계획에 소요되는 시간을 줄이고, 비용을 절감할 수 있다.",최적화된 여행 일정을 제공하여 사용자의 시간과 비용을 절약한다.,자동으로 생성된 최적화된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...","여행 일정의 효율성을 높이고, 사용자 경험을 개선하기 위해."
3,P5,주말 여행 일정 생성 서비스,SELECTED,0.6711,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 요구와 이동 가능 시간을 고려하여 여행 일정을 생성하는 서비스.,사용자는 자신의 요구에 맞는 여행 일정을 쉽게 찾을 수 있다.,사용자의 요구를 분석하여 최적의 여행 일정을 생성한다.,생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...",사용자의 요구를 반영한 여행 일정 생성을 통해 만족도를 높이기 위해.
4,P6,주말 여행 일정 추천 및 예약 서비스,SELECTED,0.5646,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,추천된 여행 일정을 사용자가 쉽게 예약할 수 있도록 지원하는 서비스.,사용자는 추천된 일정을 쉽게 예약할 수 있다.,추천된 여행 일정을 사용자가 쉽게 예약할 수 있도록 지원한다.,추천된 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...",추천된 일정을 쉽게 예약할 수 있도록 하여 사용자 경험을 개선하기 위해.
5,P2,주말 여행 맞춤형 추천 서비스,RESERVE,0.5775,Selected Portfolio 대비 marginal value가 낮아 reser...,"AMBIGUOUS,DISTINCT,VARIANT",거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 취향과 이동 가능 시간을 고려하여 맞춤형 여행 일정을 추천하는 서비스.,사용자는 자신의 취향에 맞는 여행 일정을 쉽게 찾을 수 있다.,사용자의 취향을 분석하여 최적의 여행 일정을 추천한다.,추천된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...",사용자의 취향을 반영한 여행 추천으로 만족도를 높이기 위해.

## 16. Plan Lock/Intent Validation

In [17]:
display({'accepted': [p.planId for p in plan_validation.acceptedPlans] if plan_validation else [],
         'rejected': [p.model_dump(mode='json') for p in plan_validation.rejectedPlans]
                     if plan_validation else []})

{'accepted': ['P1', 'P4', 'P3', 'P5', 'P6'], 'rejected': []}

## 17. Portfolio Family / Variant / Distinct

In [18]:
display(show_plan_diversity(plan_validation.diversity) if plan_validation else {'status': 'SKIPPED'})

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,P1,P2,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
1,P1,P3,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,P2,P3,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, useCaseThesis, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,P1,P4,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
4,P2,P4,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, useCaseThesis, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
5,P3,P4,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
6,P1,P5,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
7,P2,P5,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole: INTERMEDIARY, customerInteractio...",mechanismFamily: 추천된 여행 일정은 사용자가 선호하는 숙박 및 체험 ...,SEMANTIC_REVIEW,True,"두 개의 아키텍처는 비즈니스 역할, 고객 상호작용 모델, 데이터 의존성, 배달 모델..."
8,P3,P5,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, useCaseThesis, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,P4,P5,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, useCaseThesis, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
10,P1,P6,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
11,P2,P6,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
12,P3,P6,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, useCaseThesis, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
13,P4,P6,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, useCaseThesis, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
14,P5,P6,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...

## 18. Selected + Reserve Plans

In [19]:
selected_plans = plan_validation.acceptedPlans if plan_validation else []
reserve_plans = plan_validation.reservePlans if plan_validation else []
display(show_portfolio_plans(selected_plans + reserve_plans))
display({'selected': [p.planId for p in selected_plans], 'reserve': [p.planId for p in reserve_plans]})

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P1,주말 여행 자동 계획 서비스,SELECTED,0.9035,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 이동 가능 시간과 관심사를 고려하여 여행 일정을 자동으로 구성하는 서비스.,"사용자는 여행 계획에 소요되는 시간을 절약하고, 더 많은 시간을 여행에 할애할 수 있다.",사용자의 이동 가능 시간과 관심사를 기반으로 최적의 여행 일정을 자동으로 생성하여 ...,자동으로 생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...","주말 여행 계획의 효율성을 높이고, 사용자 경험을 개선하기 위해."
1,P4,주말 여행 계획 지원 서비스,SELECTED,0.8399,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 이동 가능 시간과 관심사를 고려하여 여행 계획을 지원하는 서비스.,사용자는 여행 계획을 쉽게 진행할 수 있다.,여행 계획을 지원하여 사용자의 편의를 높인다.,자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",여행 계획의 편리함을 제공하여 사용자 경험을 개선하기 위해.
2,P3,주말 여행 일정 최적화 서비스,SELECTED,0.6773,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 이동 가능 시간과 관심사를 고려하여 최적화된 여행 일정을 제공하는 서비스.,"사용자는 여행 계획에 소요되는 시간을 줄이고, 비용을 절감할 수 있다.",최적화된 여행 일정을 제공하여 사용자의 시간과 비용을 절약한다.,자동으로 생성된 최적화된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...","여행 일정의 효율성을 높이고, 사용자 경험을 개선하기 위해."
3,P5,주말 여행 일정 생성 서비스,SELECTED,0.6711,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 요구와 이동 가능 시간을 고려하여 여행 일정을 생성하는 서비스.,사용자는 자신의 요구에 맞는 여행 일정을 쉽게 찾을 수 있다.,사용자의 요구를 분석하여 최적의 여행 일정을 생성한다.,생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...",사용자의 요구를 반영한 여행 일정 생성을 통해 만족도를 높이기 위해.
4,P6,주말 여행 일정 추천 및 예약 서비스,SELECTED,0.5646,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,추천된 여행 일정을 사용자가 쉽게 예약할 수 있도록 지원하는 서비스.,사용자는 추천된 일정을 쉽게 예약할 수 있다.,추천된 여행 일정을 사용자가 쉽게 예약할 수 있도록 지원한다.,추천된 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...",추천된 일정을 쉽게 예약할 수 있도록 하여 사용자 경험을 개선하기 위해.
5,P2,주말 여행 맞춤형 추천 서비스,RESERVE,0.5775,Selected Portfolio 대비 marginal value가 낮아 reser...,"AMBIGUOUS,DISTINCT,VARIANT",거래 중개 · 기타 운영,주말에 1~2일 단기 여행을 자주 계획하는 직장인들.,사용자의 취향과 이동 가능 시간을 고려하여 맞춤형 여행 일정을 추천하는 서비스.,사용자는 자신의 취향에 맞는 여행 일정을 쉽게 찾을 수 있다.,사용자의 취향을 분석하여 최적의 여행 일정을 추천한다.,추천된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,"{'businessRole': 'INTERMEDIARY', 'operatingMod...",사용자의 취향을 반영한 여행 추천으로 만족도를 높이기 위해.

{'selected': ['P1', 'P4', 'P3', 'P5', 'P6'], 'reserve': ['P2']}

## 19. Candidate 1

In [20]:
candidate_one = (await engine.expand_plan(seed, selected_plans[0], 1)
                 if RUN_STAGED_CORE and selected_plans else None)
display(show_candidates([candidate_one]) if candidate_one else [])

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,주말 여행 자동 계획 서비스,자동으로 생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,앱 내 예약 수수료를 통한 수익 창출,사용자 데이터를 기반으로 지속적으로 알고리즘을 개선하여 더 나은 여행 일정을 제공한다.

## 20. Candidate 1 Korean/Governance

In [21]:
candidate_one_reports = []
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'status': 'PENDING_FULL_CANDIDATE_RECOVERY'})

{'candidateId': 'C1', 'status': 'PENDING_FULL_CANDIDATE_RECOVERY'}

## 21. Candidate 1 Actual Generic Descriptor

In [22]:
display(show_concept_descriptors([candidate_one]) if candidate_one else [])

,entityId,family,dimension,code,confidence,source
0,C1,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
1,C1,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
2,C1,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
3,C1,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
4,C1,INTERMEDIARY:OTHER,transactionModel,BOOKING,HIGH,RULE
5,C1,INTERMEDIARY:OTHER,monetizationModel,COMMISSION,HIGH,RULE
6,C1,INTERMEDIARY:OTHER,customerInteractionModel,APP,HIGH,RULE
7,C1,INTERMEDIARY:OTHER,dataDependency,MATERIAL,NaN,NaN
8,C1,INTERMEDIARY:OTHER,physicalDependency,MATERIAL,NaN,NaN

## 22. Candidate 1 Fidelity

In [23]:
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'})

{'candidateId': 'C1',
 'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'}

## 23. Remaining Candidates

In [24]:
remaining_candidates = []
if RUN_STAGED_CORE:
    for i, plan in enumerate(selected_plans[1:], 2):
        remaining_candidates.append(await engine.expand_plan(seed, plan, i))
candidate_drafts = ([candidate_one] if candidate_one else []) + remaining_candidates
display(show_candidates(candidate_drafts))

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,주말 여행 자동 계획 서비스,자동으로 생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,앱 내 예약 수수료를 통한 수익 창출,사용자 데이터를 기반으로 지속적으로 알고리즘을 개선하여 더 나은 여행 일정을 제공한다.
1,C2,L2,None,주말 여행 계획 지원 서비스,자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,"수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.",사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 더 나은 여행 계획을 지원한다.
2,C3,L3,None,주말 여행 일정 최적화 서비스,자동으로 생성된 최적화된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공합니다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,"수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출합니다.",사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 최적의 일정을 제공합니다.
3,C4,L4,None,주말 여행 일정 생성 서비스,"사용자의 요구를 분석하는 알고리즘을 통해 여행 일정을 생성하고, 생성된 일정은 사용...",거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,"사용자는 생성된 일정에 따라 직접 예약을 진행하며, 수수료를 통해 수익을 창출한다.",사용자 피드백을 통해 생성 알고리즘을 지속적으로 개선한다.
4,C5,L5,None,주말 여행 일정 추천 및 예약 서비스,추천된 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,예약 수수료 기반 수익 모델,사용자 데이터를 기반으로 추천 알고리즘을 지속적으로 개선하여 더 나은 일정을 제공한다.

## 24. Candidate Actual Generic Descriptors

In [25]:
display(show_concept_descriptors(candidate_drafts))

,entityId,family,dimension,code,confidence,source
0,C1,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
1,C1,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
2,C1,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
3,C1,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
4,C1,INTERMEDIARY:OTHER,transactionModel,BOOKING,HIGH,RULE
5,C1,INTERMEDIARY:OTHER,monetizationModel,COMMISSION,HIGH,RULE
6,C1,INTERMEDIARY:OTHER,customerInteractionModel,APP,HIGH,RULE
7,C1,INTERMEDIARY:OTHER,dataDependency,MATERIAL,NaN,NaN
8,C1,INTERMEDIARY:OTHER,physicalDependency,MATERIAL,NaN,NaN
9,C2,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
10,C2,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
11,C2,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
12,C2,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
13,C2,INTERMEDIARY:OTHER,transactionModel,BOOKING,HIGH,RULE
14,C2,INTERMEDIARY:OTHER,monetizationModel,COMMISSION,HIGH,RULE
15,C2,INTERMEDIARY:OTHER,customerInteractionModel,APP,HIGH,RULE
16,C2,INTERMEDIARY:OTHER,dataDependency,MATERIAL,NaN,NaN
17,C2,INTERMEDIARY:OTHER,physicalDependency,MATERIAL,NaN,NaN
18,C3,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
19,C3,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
20,C3,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
21,C3,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
22,C3,INTERMEDIARY:OTHER,transactionModel,BOOKING,HIGH,RULE
23,C3,INTERMEDIARY:OTHER,monetizationModel,COMMISSION,HIGH,RULE
24,C3,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
25,C3,INTERMEDIARY:OTHER,dataDependency,MATERIAL,NaN,NaN
26,C3,INTERMEDIARY:OTHER,physicalDependency,MATERIAL,NaN,NaN
27,C4,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
28,C4,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
29,C4,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
30,C4,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
31,C4,INTERMEDIARY:OTHER,transactionModel,BOOKING,HIGH,RULE
32,C4,INTERMEDIARY:OTHER,monetizationModel,COMMISSION,HIGH,RULE
33,C4,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
34,C4,INTERMEDIARY:OTHER,dataDependency,NONE,NaN,NaN
35,C4,INTERMEDIARY:OTHER,physicalDependency,MATERIAL,NaN,NaN
36,C5,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
37,C5,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
38,C5,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
39,C5,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
40,C5,INTERMEDIARY:OTHER,transactionModel,BOOKING,HIGH,RULE
41,C5,INTERMEDIARY:OTHER,monetizationModel,COMMISSION,HIGH,RULE
42,C5,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
43,C5,INTERMEDIARY:OTHER,dataDependency,NONE,NaN,NaN
44,C5,INTERMEDIARY:OTHER,physicalDependency,MATERIAL,NaN,NaN

## 25. Candidate Recovery / Portfolio Relations

In [26]:
candidate_preparation = (await engine.prepare_candidate_portfolio(
    seed, plan_validation, max_concepts=MAX_CONCEPTS, initial_candidates=candidate_drafts)
    if RUN_STAGED_CORE and plan_validation else None)
candidates = candidate_preparation.candidates if candidate_preparation else []
candidate_reports = candidate_preparation.reports if candidate_preparation else []
display(show_candidate_recovery(candidate_preparation) if candidate_preparation else {'status': 'SKIPPED'})
candidate_pairwise = [engine.compare_candidates(candidates[i], candidates[j])
                      for i in range(len(candidates)) for j in range(i + 1, len(candidates))]
display(show_plan_diversity(candidate_pairwise))

{'summary':    candidateGenerated  candidateAcceptedInitially  candidateRegenerated  \
 0                   5                           5                     0

    candidateRecovered  reservePlansActivated  candidateRecoveryReplans  \
 0                   0                      0                         0

    finalCandidatePortfolio
 0                        5  ,
 'attempts':   candidateId  schemaValid  hardLockPreserved  semanticAnchorPreserved  \
 0          C1         True               True                     True
 1          C2         True               True                     True
 2          C3         True               True                     True
 3          C4         True               True                     True
 4          C5         True               True                     True

    planFidelity anchorDecision fidelityDecision  contentLanguageValid  \
 0          True           PASS          ADAPTED                  True
 1          True           PASS          ADAPTED                  True
 2          True           PASS          ADAPTED                  True
 3          True           PASS          ADAPTED                  True
 4          True           PASS          ADAPTED                  True

    accepted   outcome  semanticFidelityUsed  \
 0      True  ACCEPTED                 False
 1      True  ACCEPTED                 False
 2      True  ACCEPTED                 False
 3      True  ACCEPTED                 False
 4      True  ACCEPTED                 False

                            matchedIdentityComponents  \
 0  [targetSegmentThesis, valuePropositionThesis, ...
 1  [targetSegmentThesis, valuePropositionThesis, ...
 2  [targetSegmentThesis, valuePropositionThesis, ...
 3  [targetSegmentThesis, valuePropositionThesis, ...
 4  [targetSegmentThesis, valuePropositionThesis, ...

       missingIdentityComponents reasonCodes safeSummary
 0  [useCaseThesis, offerThesis]          []       검사 통과
 1  [useCaseThesis, offerThesis]          []       검사 통과
 2  [useCaseThesis, offerThesis]          []       검사 통과
 3  [useCaseThesis, offerThesis]          []       검사 통과
 4  [useCaseThesis, offerThesis]          []       검사 통과  ,
 'finalCandidates':   candidateId lineageId parentCandidateId                    이름  \
 0          C1        L1              None       주말 여행 자동 계획 서비스
 1          C2        L2              None       주말 여행 계획 지원 서비스
 2          C3        L3              None      주말 여행 일정 최적화 서비스
 3          C4        L4              None       주말 여행 일정 생성 서비스
 4          C5        L5              None  주말 여행 일정 추천 및 예약 서비스

                                              핵심 작동방식         family  \
 0    자동으로 생성된 여행 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.  거래 중개 · 기타 운영
 1        자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.  거래 중개 · 기타 운영
 2  자동으로 생성된 최적화된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공합니다.  거래 중개 · 기타 운영
 3  사용자의 요구를 분석하는 알고리즘을 통해 여행 일정을 생성하고, 생성된 일정은 사용...  거래 중개 · 기타 운영
 4            추천된 일정은 사용자가 선호하는 숙박 및 체험 예약 페이지로 연결된다.  거래 중개 · 기타 운영

                                           descriptor  \
 0  {'thesis': {'targetSegmentThesis': '주말 1~2일 단기...
 1  {'thesis': {'targetSegmentThesis': '주말 1~2일 단기...
 2  {'thesis': {'targetSegmentThesis': '주말 1~2일 단기...
 3  {'thesis': {'targetSegmentThesis': '주말 1~2일 단기...
 4  {'thesis': {'targetSegmentThesis': '주말 1~2일 단기...

                                                수익  \
 0                            앱 내 예약 수수료를 통한 수익 창출
 1       수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.
 2      수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출합니다.
 3  사용자는 생성된 일정에 따라 직접 예약을 진행하며, 수수료를 통해 수익을 창출한다.
 4                                 예약 수수료 기반 수익 모델

                                                  운영
 0  사용자 데이터를 기반으로 지속적으로 알고리즘을 개선하여 더 나은 여행 일정을 제공한다.
 1  사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 더 나은 여행 계획을 지원한다.
 2     사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 최적의 일정을 제공합니다.
 3                  사용자 피드백을 통해 생성 알고리즘을 지속적으로 개선한다.
 4  사용자 데이터를 기반으로 추천 알고리즘을 지속적으로 개선하여 더 나은 일정을 제공한다.  }

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,C1,C2,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,C1,C3,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,C1,C4,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, dataDependency, valu...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
3,C1,C5,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, dataDependency, valu...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
4,C2,C3,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
5,C2,C4,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, dataDependency, valu...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,C2,C5,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, dataDependency, valu...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,C3,C4,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","dataDependency, valuePropositionThesis, offerT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
8,C3,C5,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","dataDependency, valuePropositionThesis, offerT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,C4,C5,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...

## 26. Legal Fact Completeness + Business Design Completion + C1 Fact Pattern

In [27]:
prechecks = [engine.legal_precheck(item) for item in candidates] if RUN_STAGED_LEGAL else []
display(show_legal_precheck(prechecks))
legal_preparation = (await engine.prepare_legal_candidates(seed, candidates)
                     if RUN_STAGED_LEGAL and candidates else None)
candidates_before_legal = candidates
candidates = legal_preparation.candidates if legal_preparation else candidates
display({'factCompleteness': [item.model_dump(mode='json') for item in legal_preparation.reports]
                              if legal_preparation else [],
         'roleSemanticBatchCalls': legal_preparation.roleSemanticBatchCalls if legal_preparation else 0,
         'dependencySemanticBatchCalls': legal_preparation.dependencySemanticBatchCalls if legal_preparation else 0,
         'completionAttempted': legal_preparation.completionAttempted if legal_preparation else 0,
         'completionValidated': legal_preparation.completionValidated if legal_preparation else 0,
         'completionAccepted': legal_preparation.completionAccepted if legal_preparation else 0,
         'completionExhausted': legal_preparation.completionExhausted if legal_preparation else 0,
         'completionCompliance': [item.model_dump(mode='json') for item in legal_preparation.completionCompliance] if legal_preparation else [],
         'preLegalExclusions': legal_preparation.excludedCandidates if legal_preparation else []})
display(show_legal_fact_pattern(candidates[0].candidate, seed) if candidates else [])

,candidateId,label,directSeller,intermediary,regulatedPhysicalActivity,personalDataDependency,qualificationDependency,riskHints
0,C1,Structural risk precheck — not final legal review,False,True,True,True,False,"[물리 활동, 개인정보]"
1,C2,Structural risk precheck — not final legal review,True,True,True,True,False,"[물리 활동, 개인정보]"
2,C3,Structural risk precheck — not final legal review,True,True,False,True,False,[개인정보]
3,C4,Structural risk precheck — not final legal review,True,False,True,False,False,[물리 활동]
4,C5,Structural risk precheck — not final legal review,False,False,True,False,False,[물리 활동]

{'factCompleteness': [{'candidateId': 'C1',
   'status': 'COMPLETABLE',
   'missingDesignFacts': ['sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'contradictions': [],
   'completionRequirements': ['sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'affectedFields': ['sellerRole'],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MISMATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MISMATCH',
     'finalStatus': 'MISMATCH',
     'safeReason': '다른 역할의 설명이 들어 있어 해당 역할을 다시 명시해야 합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '배송·방문·설치 등 물리적 이행이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [{'field': 'sellerRole',
     'reasonType': 'ROLE_MISMATCH',
     'dependencyType': None,
     'instruction': 'sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'}],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.'},
  {'candidateId': 'C2',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '배송·방문·설치 등 물리적 이행이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C3',
   'status': 'COMPLETABLE',
   'missingDesignFacts': ['물리적 이행 활동과 수행 주체를 physicalActivities에 명시해야 합니다.'],
   'contradictions': [],
   'completionRequirements': ['물리적 이행 활동과 수행 주체를 physicalActivities에 명시해야 합니다.'],
   'affectedFields': ['physicalActivities'],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticDecision': 'REQUIRED',
     'finalDecision': 'REQUIRED',
     'safeReason': 'Physical activities such as booking accommodations and experiences are integral to the service.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [{'field': 'physicalActivities',
     'reasonType': 'MISSING_REQUIRED_FACT',
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'instruction': '물리적 이행 활동과 수행 주체를 physicalActivities에 명시해야 합니다.'}],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.'},
  {'candidateId': 'C4',
   'status': 'COMPLETABLE',
   'missingDesignFacts': ['외부 사업 파트너의 주체와 역할을 partnerRequirements에 명시해야 합니다.'],
   'contradictions': [],
   'completionRequirements': ['외부 사업 파트너의 주체와 역할을 partnerRequirements에 명시해야 합니다.'],
   'affectedFields': ['partnerRequirements'],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '데이터 비의존 구조이며 개인 단위 처리 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '배송·방문·설치 등 물리적 이행이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticDecision': 'REQUIRED',
     'finalDecision': 'REQUIRED',
     'safeReason': 'Partnerships with travel-related businesses are essential for service integration.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [{'field': 'partnerRequirements',
     'reasonType': 'MISSING_REQUIRED_FACT',
     'dependencyType': 'BUSINESS_PARTNER',
     'instruction': '외부 사업 파트너의 주체와 역할을 partnerRequirements에 명시해야 합니다.'}],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.'},
  {'candidateId': 'C5',
   'status': 'COMPLETABLE',
   'missingDesignFacts': ['sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.',
    '실제 처리하는 개인 단위 정보와 처리 목적을 personalDataUsage에 명시해야 합니다.'],
   'contradictions': [],
   'completionRequirements': ['sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.',
    '실제 처리하는 개인 단위 정보와 처리 목적을 personalDataUsage에 명시해야 합니다.'],
   'affectedFields': ['sellerRole', 'personalDataUsage'],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MISMATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MISMATCH',
     'finalStatus': 'MISMATCH',
     'safeReason': '다른 역할의 설명이 들어 있어 해당 역할을 다시 명시해야 합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticDecision': 'REQUIRED',
     'finalDecision': 'REQUIRED',
     'safeReason': 'User data is necessary for generating personalized travel itineraries.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '배송·방문·설치 등 물리적 이행이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [{'field': 'sellerRole',
     'reasonType': 'ROLE_MISMATCH',
     'dependencyType': None,
     'instruction': 'sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'},
    {'field': 'personalDataUsage',
     'reasonType': 'MISSING_REQUIRED_FACT',
     'dependencyType': 'PERSONAL_DATA',
     'instruction': '실제 처리하는 개인 단위 정보와 처리 목적을 personalDataUsage에 명시해야 합니다.'}],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.'},
  {'candidateId': 'C1-F1',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '배송·방문·설치 등 물리적 이행이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'}],
 'roleSemanticBatchCalls': 2,
 'dependencySemanticBatchCalls': 1,
 'completionAttempted': 4,
 'completionValidated': 1,
 'completionAccepted': 0,
 'completionExhausted': 4,
 'completionCompliance': [{'candidateId': 'C1-F1',
   'status': 'FAIL',
   'satisfiedRequirements': [],
   'unsatisfiedRequirements': ['sellerRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'changedFields': [],
   'unchangedRequiredFields': ['sellerRole'],
   'safeSummary': 'Completion Provider가 요청된 사업 사실을 실제로 보완하지 않았습니다.'}],
 'preLegalExclusions': [{'candidateId': 'C3',
   'scope': 'PRE_LEGAL_EXCLUSION',
   'reasonCode': 'LEGAL_FACT_COMPLETION_SCOPE_VIOLATION',
   'affectedFields': ['channels',
    'intermediaryRole',
    'partnerRequirements',
    'paymentFlow',
    'personalDataUsage',
    'platformRole',
    'providerRole',
    'sellerRole',
    'targetRegion',
    'transactionFlow'],
   'dependencyDecisions': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticDecision': 'REQUIRED',
     'finalDecision': 'REQUIRED',
     'safeReason': 'Physical activities such as booking accommodations and experiences are integral to the service.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'completionRequirements': [{'field': 'physicalActivities',
     'reasonType': 'MISSING_REQUIRED_FACT',
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'instruction': '물리적 이행 활동과 수행 주체를 physicalActivities에 명시해야 합니다.'}],
   'patchChangedFields': ['platformRole',
    'providerRole',
    'sellerRole',
    'intermediaryRole',
    'transactionFlow',
    'paymentFlow',
    'personalDataUsage',
    'physicalActivities',
    'partnerRequirements',
    'targetRegion',
    'channels'],
   'recoveryAttempted': True,
   'recoveryResolution': 'PATCH_SCOPE_VIOLATION',
   'safeSummary': 'Completion patch가 허용 범위 또는 사용자 LOCK을 위반했습니다.'},
  {'candidateId': 'C4',
   'scope': 'PRE_LEGAL_EXCLUSION',
   'reasonCode': 'LEGAL_FACT_COMPLETION_SCOPE_VIOLATION',
   'affectedFields': ['channels',
    'intermediaryRole',
    'paymentFlow',
    'physicalActivities',
    'platformRole',
    'providerRole',
    'sellerRole',
    'targetRegion',
    'transactionFlow'],
   'dependencyDecisions': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '데이터 비의존 구조이며 개인 단위 처리 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '배송·방문·설치 등 물리적 이행이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticDecision': 'REQUIRED',
     'finalDecision': 'REQUIRED',
     'safeReason': 'Partnerships with travel-related businesses are essential for service integration.',

,field,legalFact,source,authority,decision
0,platformRole,여행 계획 지원 플랫폼으로서 사용자와 제공업체를 연결한다.,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
1,providerRole,여행 계획 서비스를 제공하는 주체로서 사용자와의 상호작용을 담당한다.,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
2,sellerRole,숙박 및 체험 제공업체로서 예약 서비스를 판매한다.,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
3,intermediaryRole,플랫폼을 통해 사용자와 제공업체 간의 거래를 중개한다.,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
4,transactionFlow,"[사용자가 앱에서 여행 일정을 선택한다., 사용자가 예약을 진행한다., 예약이 완료...",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
5,paymentFlow,"[사용자가 예약 시 결제 정보를 입력한다., 결제가 완료되면 예약 확인이 이루어진다...",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
6,personalDataUsage,[사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
7,physicalActivities,"[배송, 현장 방문, 설치]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
8,partnerRequirements,[숙박 및 체험 제공업체와의 제휴 계약 체결이 필요하다.],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
9,qualificationRequirements,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
10,advertisingClaims,[사용자의 이동 가능 시간과 관심사를 반영한 맞춤형 여행 일정 제공],CONCEPT_GENERATED,REVIEWABLE,PROPOSED

## 27. Prepared Legal C1 Evidence Summary

In [28]:
legal_adapter = CurrentLegalAdapter() if RUN_STAGED_LEGAL else None
legal_c1_input = (legal_adapter.task_input(candidates[0].candidate, seed)
                  if legal_adapter and candidates else None)
display({'candidateId': candidates[0].candidateId if candidates else None,
         'externalFacts': legal_c1_input['externalFactContext']['facts'] if legal_c1_input else [],
         'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'})

{'candidateId': 'C2',
 'externalFacts': [],
 'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'}

## 28. Full Evidence Judgment — C1 Staged Smoke

In [29]:
RUN_FULL_LEGAL_C1 = RUN_STAGED_LEGAL
legal_one = None
if RUN_FULL_LEGAL_C1 and candidates:
    try:
        legal_one = await engine.review_legal_candidate(seed, candidates[0])
        display(show_legal_result([legal_one]))
    except Exception:
        display(show_legal_failure(candidates[0].candidateId, engine.gateway))
else:
    print('SKIPPED — RUN_FULL_LEGAL_C1=True로 명시해야 실행됩니다.')

,candidateId,route,productionStatus,sourceStatus,evidenceCoverage,reviewPhase,factCompletenessStatus,legalSourceStatus,finalEvidenceJudgmentExecuted,recoveryResolution,...,legalClarificationCount,safeSummary,unknownFacts,requiredControls,requiredPartnersAndQualifications,requiredDisclosures,prohibitedVariants,evidenceCount,evidenceRefs,evidenceDiagnostics
0,C2,ACCEPT,IMPLEMENTABLE_WITH_CONTROLS,SOURCE_COMPLETE,None,LEGAL_SOURCE,None,SOURCE_COMPLETE,True,None,...,0,사용자 데이터 보호 및 개인정보 처리 관련 법령 준수 필요.,[],"[통신판매업자는 신고를 해야 한다., 통신판매업자는 거래조건에 대한 정보를 제공해야...",[숙박 및 체험 제공업체와의 제휴 계약 체결이 필요하다.],[사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.],[],24,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...","{'coverageStatus': 'SOURCE_COMPLETE', 'coverag..."

## 29. C1 Route + Staged Redesign/Compliance/Second Legal

In [30]:
c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = ([], [], [], 0, 0)
if legal_one and candidates:
    c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[:1], [legal_one])
display({'initialRoute': legal_one.route.value if legal_one else 'SKIPPED',
         'redesignRequirements': legal_one.redesignRequirements if legal_one else [],
         'recoveryReviews': [item.model_dump(mode='json') for item in c1_legal_all[1:]],
         'requiredInputs': c1_required_inputs, 'terminalCandidates': len(c1_portfolio),
         'redesigned': c1_redesigned, 'replanned': c1_replanned})

{'initialRoute': 'ACCEPT',
 'redesignRequirements': [],
 'recoveryReviews': [],
 'requiredInputs': [],
 'terminalCandidates': 1,
 'redesigned': 0,
 'replanned': 0}

## 30. Remaining 4 Legal + Exhaustive Recovery Summary

In [31]:
RUN_REMAINING_LEGAL = RUN_STAGED_FULL
legal_remaining = []
portfolio, legal_all, required_inputs = (list(c1_portfolio), list(c1_legal_all), list(c1_required_inputs))
redesigned_count, replanned_count = c1_redesigned, c1_replanned
c1_terminal = bool(c1_portfolio or c1_required_inputs or (c1_legal_all and c1_legal_all[-1].route.value == 'SYSTEM_FAILURE'))
if RUN_REMAINING_LEGAL and c1_terminal and len(candidates) > 1:
    legal_remaining = await engine.review_legal(seed, candidates[1:])
    rest_portfolio, rest_legal, rest_inputs, rest_redesigned, rest_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[1:], legal_remaining)
    portfolio += rest_portfolio; legal_all += rest_legal; required_inputs += rest_inputs
    redesigned_count += rest_redesigned; replanned_count += rest_replanned
else:
    print('SKIPPED — C1이 정상 terminal에 도달한 후 remaining Legal을 실행합니다.')
legal_initial = ([legal_one] if legal_one else []) + legal_remaining
display({'recoveryTrace': [item.model_dump(mode='json') for item in legal_all
                           if item.candidateId not in {x.candidateId for x in legal_initial}],
         'requiredInputs': required_inputs, 'metrics': engine._legal_metrics})
print({'Plan Selected': len(selected_plans),
       'Candidate Generated': candidate_preparation.candidateGenerated if candidate_preparation else 0,
       'Candidate Valid Initially': candidate_preparation.candidateAcceptedInitially if candidate_preparation else 0,
       'Candidate Regenerated': candidate_preparation.candidateRegenerated if candidate_preparation else 0,
       'Candidate Recovered': candidate_preparation.candidateRecovered if candidate_preparation else 0,
       'Fact Completion Attempted': legal_preparation.completionAttempted if legal_preparation else 0,
       'Fact Completion Validated': legal_preparation.completionValidated if legal_preparation else 0,
       'Fact Completion Accepted': legal_preparation.completionAccepted if legal_preparation else 0,
       'Dependency Semantic Calls': legal_preparation.dependencySemanticBatchCalls if legal_preparation else 0,
       'Completion Compliance PASS': sum(item.status == 'PASS' for item in legal_preparation.completionCompliance) if legal_preparation else 0,
       'Legal Ready': len(candidates) if legal_preparation else 0,
       'Legal Reviewed': len(legal_initial),
       'Legal Accepted': sum(item.route.value == 'ACCEPT' for item in legal_all),
       'Legal Redesigned': redesigned_count, 'Legal Replanned': replanned_count,
       'Final Portfolio': len(portfolio)})

SKIPPED — C1이 정상 terminal에 도달한 후 remaining Legal을 실행합니다.

{'recoveryTrace': [],
 'requiredInputs': [],
 'metrics': {'factAttempted': 4,
  'factValidated': 1,
  'factAccepted': 0,
  'factExhausted': 4,
  'dependencySemanticCalls': 1,
  'completionCompliancePassed': 0,
  'providerNoncompliant': 1,
  'recheckFailed': 0,
  'redesignAttempted': 0,
  'redesignValidated': 0,
  'redesignAccepted': 0,
  'redesignExhausted': 0,
  'replanAttempted': 0,
  'replanValidated': 0,
  'replanAccepted': 0,
  'replanExhausted': 0}}

{'Plan Selected': 5, 'Candidate Generated': 5, 'Candidate Valid Initially': 5, 'Candidate Regenerated': 0, 'Candidate Recovered': 0, 'Fact Completion Attempted': 4, 'Fact Completion Validated': 1, 'Fact Completion Accepted': 0, 'Dependency Semantic Calls': 1, 'Completion Compliance PASS': 0, 'Legal Ready': 1, 'Legal Reviewed': 1, 'Legal Accepted': 1, 'Legal Redesigned': 0, 'Legal Replanned': 0, 'Final Portfolio': 1}

## 31. Replan

In [32]:
display(show_replan(type('PortfolioView', (), {'concepts': portfolio})()))
print({'replanned': replanned_count, 'reserveAvailable': len(reserve_plans)})

Empty DataFrame
Columns: []
Index: []

{'replanned': 0, 'reserveAvailable': 1}

## 32. Final Portfolio

In [33]:
legal_terminal_status = ('READY_FULL' if len(portfolio) == MAX_CONCEPTS else
    'READY_LIMITED' if portfolio else
    'LEGAL_RECOVERY_COMPLETE_NO_ACCEPTED_CANDIDATE' if legal_initial and len(legal_initial) == len(candidates)
    else 'LEGAL_PENDING')
display(show_final_portfolio(type('PortfolioView', (), {'concepts': portfolio})()) if portfolio else {'status': legal_terminal_status})

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C2,L2,None,주말 여행 계획 지원 서비스,자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '주말 1~2일 단기...,"수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.",사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 더 나은 여행 계획을 지원한다.

## 33. Unresolved Candidate Summary

In [34]:
display(show_required_inputs(required_inputs) if required_inputs else {'unresolved': []})

{'unresolved': []}

## 34. Manual Concept Selection

In [35]:
SELECTED_CANDIDATE_ID = portfolio[0].candidateId if portfolio else None  # 사용자가 수정
selected_concept = next((item for item in portfolio if item.candidateId == SELECTED_CANDIDATE_ID), None)
print({'selectedCandidateId': SELECTED_CANDIDATE_ID})

{'selectedCandidateId': 'C2'}

## 35. 7 Hypotheses

In [36]:
hypotheses = (engine.build_or_load_current_hypothesis_contract(selected_concept)
              if RUN_STAGED_FULL and selected_concept else [])
hypotheses = await engine.resolve_hypothesis_semantics(hypotheses) if hypotheses else []
display(show_hypotheses(hypotheses))
display(show_hypothesis_readiness(hypotheses))

,HypothesisType,ProposedValue,FinalValue,SemanticStatus,SemanticReason,Locked,DecisionStatus,LegalImpact
0,TARGET_REGION,한국 전역,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
1,REVENUE_MODEL,"수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.",None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
2,PRICE,서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
3,CHANNELS,"모바일 앱을 통해 사용자와 소통하며, 소셜 미디어를 통한 마케팅을 진행한다.",None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
4,DIFFERENTIATORS,"사용자의 이동 가능 시간과 관심사를 실시간으로 반영한 지원, 숙박 및 체험 예약 페...",None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
5,PRE_MARKET_SOM_SHARE,targetSharePercent=15.0 horizonYears=3 rationa...,None,VALID,수치·기간·산식 가설이 명시되었습니다.,False,PROPOSED,NONE
6,PRE_MARKET_SOM,amount=5000000.0 currency='KRW' period='연간' ca...,None,VALID,수치·기간·산식 가설이 명시되었습니다.,False,PROPOSED,NONE

{'All Values Semantically Valid': True,
 'All Decisions Confirmed': False,
 'Ready For Handoff': False,
 'status': 'NOT_READY',
 'reason': 'UNRESOLVED_HYPOTHESES',
 'unresolvedHypotheses': ['TARGET_REGION',
  'REVENUE_MODEL',
  'PRICE',
  'CHANNELS',
  'DIFFERENTIATORS',
  'PRE_MARKET_SOM_SHARE',
  'PRE_MARKET_SOM']}

## 36. Confirm / Edit

In [37]:
CONFIRM_ALL_PROPOSED = True
HYPOTHESIS_EDITS = {
    # 'PRICE': '월 17,900원',
}
confirmed_hypotheses = engine.confirm_hypotheses(
    hypotheses, HYPOTHESIS_EDITS, confirm_all_proposed=CONFIRM_ALL_PROPOSED) if hypotheses else []
display(show_hypotheses(confirmed_hypotheses))
hypothesis_readiness = show_hypothesis_readiness(confirmed_hypotheses)
display(hypothesis_readiness)

,HypothesisType,ProposedValue,FinalValue,SemanticStatus,SemanticReason,Locked,DecisionStatus,LegalImpact
0,TARGET_REGION,한국 전역,한국 전역,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
1,REVENUE_MODEL,"수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.","수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.",VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
2,PRICE,서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.,서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
3,CHANNELS,"모바일 앱을 통해 사용자와 소통하며, 소셜 미디어를 통한 마케팅을 진행한다.","모바일 앱을 통해 사용자와 소통하며, 소셜 미디어를 통한 마케팅을 진행한다.",VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
4,DIFFERENTIATORS,"사용자의 이동 가능 시간과 관심사를 실시간으로 반영한 지원, 숙박 및 체험 예약 페...","사용자의 이동 가능 시간과 관심사를 실시간으로 반영한 지원, 숙박 및 체험 예약 페...",VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
5,PRE_MARKET_SOM_SHARE,targetSharePercent=15.0 horizonYears=3 rationa...,targetSharePercent=15.0 horizonYears=3 rationa...,VALID,수치·기간·산식 가설이 명시되었습니다.,False,ACCEPTED,NONE
6,PRE_MARKET_SOM,amount=5000000.0 currency='KRW' period='연간' ca...,amount=5000000.0 currency='KRW' period='연간' ca...,VALID,수치·기간·산식 가설이 명시되었습니다.,False,ACCEPTED,NONE

{'All Values Semantically Valid': True,
 'All Decisions Confirmed': True,
 'Ready For Handoff': True,
 'status': 'READY',
 'reason': None,
 'unresolvedHypotheses': []}

## 37. Actual Delta Legal

In [38]:
RUN_DELTA_LEGAL = True
delta_legal_result = None
if RUN_STAGED_FULL and RUN_DELTA_LEGAL and selected_concept and any(h.deltaLegalRequired for h in confirmed_hypotheses):
    delta_legal_result = await engine.review_delta_legal(seed, selected_concept, confirmed_hypotheses)
    confirmed_hypotheses = engine.mark_delta_legal_reviewed(confirmed_hypotheses, delta_legal_result)
display(delta_legal_result.model_dump(mode='json') if delta_legal_result else {'status': 'NOT_REQUIRED_OR_SKIPPED'})

{'status': 'NOT_REQUIRED_OR_SKIPPED'}

## 38. Market Seed

In [39]:
handoff = None
if selected_concept and legal_all and hypothesis_readiness['Ready For Handoff']:
    handoff = engine.build_downstream_handoff(seed, selected_concept, confirmed_hypotheses, legal_all)
display(handoff.marketAnalysisSeedSnapshot if handoff else {
    'status': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'contract': 'market-analysis-seed-snapshot-v1',
 'schemaVersion': '2.0',
 'snapshotId': 'lab-market-seed',
 'projectId': 0,
 'selectionId': 0,
 'conceptId': 'C2',
 'createdAt': '2026-08-10T06:51:42.104530+00:00',
 'sourceSnapshotHash': 'sha256:c80d3ca735a837897aa27872d5da439460d4fc5e7040a0ac3a7c3f46aea70473',
 'originalSeed': {'ideaOverview': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
  'fields': {'ideaOverview': {'value': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'},
   'problem': {'value': '짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'},
   'targetUsers': {'value': '주말 1~2일 단기 여행을 자주 계획하는 직장인',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'}}},
 'aiInterpretation': {'interpretedProblem': '짧은 주말 여행을 계획하는 데 소요되는 시간과 노력을 줄이는 것.',
  'interpretedTargetUsers': '주말에 1~2일 단기 여행을 자주 계획하는 직장인들.',
  'usageContext': '사용자의 이동 가능 시간과 관심사를 고려하여 여행 일정을 자동으로 구성하는 서비스.',
  'industryCategory': '여행 및 관광',
  'researchScope': '주말 여행 계획 서비스에 대한 시장 조사.',
  'conciseIdeaDefinition': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동으로 구성하는 서비스.',
  'targetRegionInterpretation': '대상 지역은 명시되지 않음.',
  'relevantKnownCompetitorContext': '경쟁자는 명시되지 않음.'},
 'selectedConcept': {'identity': {'conceptName': '주말 여행 계획 지원 서비스',
   'conceptDefinition': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
   'introduction': '여행 계획을 지원하여 사용자의 편의를 높이는 서비스.',
   'coreValue': '사용자는 여행 계획을 쉽게 진행할 수 있다.',
   'targetUsers': '주말 1~2일 단기 여행을 자주 계획하는 직장인',
   'industryCategory': '여행 및 관광',
   'researchScope': '주말 여행 계획 서비스에 대한 시장 조사.'},
  'solution': {'problemScenario': '짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.',
   'solutionMechanism': '자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.',
   'featureSet': ['사용자의 이동 가능 시간 입력 기능',
    '관심사 기반 여행 일정 추천',
    '숙박 및 체험 예약 연동 기능']},
  'operation': {'actorRoles': ['사용자', '숙박 제공업체', '체험 제공업체'],
   'platformRole': '여행 계획 지원 플랫폼으로서 사용자와 제공업체를 연결한다.',
   'operatingModel': '사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 더 나은 여행 계획을 지원한다.',
   'partnerModel': '숙박 및 체험 제공업체와 제휴하여 예약 서비스를 통합한다.',
   'providerRole': '여행 계획 서비스를 제공하는 주체로서 사용자와의 상호작용을 담당한다.',
   'sellerRole': '숙박 및 체험 제공업체로서 예약 서비스를 판매한다.',
   'intermediaryRole': '플랫폼을 통해 사용자와 제공업체 간의 거래를 중개한다.',
   'transactionFlow': ['사용자가 앱에서 여행 일정을 선택한다.',
    '사용자가 예약을 진행한다.',
    '예약이 완료되면 제공업체에 통보된다.'],
   'paymentFlow': ['사용자가 예약 시 결제 정보를 입력한다.',
    '결제가 완료되면 예약 확인이 이루어진다.',
    '제공업체에 수수료가 지급된다.'],
   'personalDataUsage': ['사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.'],
   'physicalActivities': ['배송', '현장 방문', '설치'],
   'partnerRequirements': ['숙박 및 체험 제공업체와의 제휴 계약 체결이 필요하다.'],
   'qualificationRequirements': []},
  'valueSemantics': [{'fieldKey': 'conceptName',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'conceptDefinition',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'introduction',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'coreValue',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'targetUsers',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'industryCategory',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'researchScope',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'targetRegion',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'revenueModel',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'price',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'channels',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'differentiators',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'preMarketSomShareHypothesis',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'preMarketSomHypothesis',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'actorRoles',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'platformRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'problemScenario',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'solutionMechanism',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'featureSet',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'operatingModel',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'partnerModel',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'providerRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'sellerRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'intermediaryRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'transactionFlow',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'paymentFlow',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'personalDataUsage',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'physicalActivities',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'partnerRequirements',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'qualificationRequirements',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'advertisingClaims',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'}],
  'canonicalHash': 'sha256:af3b6d378978e49a7105b871096ac880e96da4ab1a76f2bebeae9b8fbc8c9958'},
 'finalHypotheses': {'targetRegion': {'value': '한국 전역',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'revenueModel': {'value': '수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'price': {'value': '서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'channels': {'value': '모바일 앱을 통해 사용자와 소통하며, 소셜 미디어를 통한 마케팅을 진행한다.',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'differentiators': {'value': '사용자의 이동 가능 시간과 관심사를 실시간으로 반영한 지원, 숙박 및 체험 예약 페이지와의 원활한 연동',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'preMarketSomShare': {'value': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='주말 여행 시장의 성장과 사용자 편의성 증가에 따른 수요 증가 예상.', assumptions=['주말 여행을 계획하는 직장인 수가 증가할 것', '사용자 경험 개선으로 인한 재사용률 증가']),
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'preMarketSom': {'value': PreMarketSomHypothesis(amount=5000000.0, currency='KRW', period='연간', calculationBasis='주말 여행 예약 수수료 기반으로 추정한 시장 규모', assumptions=['주말 여행 예약 수요가 매년 10% 증가할 것', '경쟁 서비스 대비 차별화된 기능으로 시장 점유율 확보 가능'], confidence='MEDIUM'),
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'}},
 'legalResult': {'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
  'safeSummary': '사용자 데이터 보호 및 개인정보 처리 관련 법령 준수 필요.',
  'requiredControls': ['통신판매업자는 신고를 해야 한다.',
   '통신판매업자는 거래조건에 대한 정보를 제공해야 한다.',
   '소비자는 청약철회를 할 수 있는 권리가 있다.',
   '청약철회 시 소비자는 이미 공급받은 재화를 반환해야 한다.',
   '사업자는 부가가치세의 과세기간을 준수해야 한다.',
   '사업자는 사업자등록을 신청해야 한다.',
   '사업자는 영수증을 발급해야 한다.',
   '사업자는 약관을 한글로 작성해야 한다.',
   '사업자는 부당한 표시ㆍ광고 행위를 해서는 안 된다.',
   '개인정보를 수집할 때 동의를 받아야 한다.'],
  'requiredPartnersAndQualifications': ['숙박 및 체험 제공업체와의 제휴 계약 체결이 필요하다.'],
  'prohibitedVariants': [],
  'requiredDisclosures': ['사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.'],
  'officialEvidenceReferences': [{'referenceIndex': 0,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제12조',
    'title': '통신판매업자의 신고 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:448fe0bd6a72942700268999bc17abaf1a130dc75ff98338f016366ffccb8d53',
    'boundedProvisionSummary': '통신판매업자는 신고를 해야 한다.',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 1,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제13조',
    'title': '신원 및 거래조건에 대한 정보의 제공',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:6e496bba7781eda4a1e42db7cb6ead3a7f9648a8557ee96ea09e290d3f30b30d',
    'boundedProvisionSummary': '통신판매업자는 거래조건에 대한 정보를 제공해야 한다.',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 2,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제17조',
    'title': '청약철회등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:086921e6e5bc694ea2d723423f266762b50490e33b8739d64e1920b7a13bde5c',
    'boundedProvisionSummary': '소비자는 청약철회를 할 수 있는 권리가 있다.',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 3,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제18조',
    'title': '청약철회등의 효과',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:48bb8d8484384496bed84e6eac658a1ea9dcd53ed91bc5d6291359764c102642',
    'boundedProvisionSummary': '청약철회 시 소비자는 이미 공급받은 재화를 반환해야 한다.',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 4,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001571',
    'officialIdentifier': '276117',
    'lawName': '부가가치세법',
    'articleReference': '제5조',
    'title': '과세기간',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20260102',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:55e12be5d081847f6c347a9be100376c35ba524c561e8d24448e063534c29ca9',
    'boundedProvisionSummary': '사업자는 부가가치세의 과세기간을 준수해야 한다.',
    'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 5,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001571',
    'officialIdentifier': '276117',
    'lawName': '부가가치세법',
    'articleReference': '제8조',
    'title': '사업자등록',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20260102',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:f592e37dcf9ad848267be7603a224ad1645f2b8ef32bd5463d0f81b6296939b2',
    'boundedProvisionSummary': '사업자는 사업자등록을 신청해야 한다.',
    'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 6,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001571',
    'officialIdentifier': '276117',
    'lawName': '부가가치세법',
    'articleReference': '제36조',
    'title': '영수증 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20260102',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:73a2ea65e521a0d7b21520ba72f17ce4be74a0258a17177073833853d88968f2',
    'boundedProvisionSummary': '사업자는 영수증을 발급해야 한다.',
    'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 7,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001571',
    'officialIdentifier': '276117',
    'lawName': '부가가치세법',
    'articleReference': '제53조의2',
    'title': '전자적 용역을 공급하는 국외사업자의 사업자등록 및 납부 등에 관한 특례',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20260102',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:fb9766cb992d59a2c98a513510e00823fbac4ba1662f6afa5554c0e5e1e5dc18',
    'boundedProvisionSummary': '국외사업자는 간편사업자등록을 해야 한다.',
    'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 8,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '000667',
    'officialIdentifier': '260021',
    'lawName': '약관의 규제에 관한 법률',
    'articleReference': '제3조',
    'title': '약관의 작성 및 설명의무 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20240206',
    'effectiveDate': '20240807',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:1616dce193e178dfd11405c2891a1bdea99e8a3b2e06ee7b662ebcb5d99bea23',
    'boundedProvisionSummary': '사업자는 약관을 한글로 작성해야 한다.',
    'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 9,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '000667',
    'officialIdentifier': '260021',
    'lawName': '약관의 규제에 관한 법률',
    'articleReference': '제5조',
    'title': '약관의 해석',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20240206',
    'effectiveDate': '20240807',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:f85b7d1c454d2a8ed12a884b224e377844ab60a45906b658e47469009efc00e6',
    'boundedProvisionSummary': '약관은 신의성실의 원칙에 따라 해석되어야 한다.',
    'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 10,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '000667',
    'officialIdentifier': '260021',
    'lawName': '약관의 규제에 관한 법률',
    'articleReference': '제16조',
    'title': '일부 무효의 특칙',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20240206',
    'effectiveDate': '20240807',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:0719bda3584934dc655f86e42d2bd50b5faeedf32df5de39a409256332337d52',
    'boundedProvisionSummary': '약관의 일부 무효 시 계약은 나머지 부분만으로 유효하다.',
    'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 11,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '000667',
    'officialIdentifier': '260021',
    'lawName': '약관의 규제에 관한 법률',
    'articleReference': '제17조',
    'title': '불공정약관조항의 사용금지',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20240206',
    'effectiveDate': '20240807',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:c443ce12c5268686ed554a0ced386d8c85057d3bf72b69c432f50429172c692a',
    'boundedProvisionSummary': '사업자는 불공정약관조항을 사용해서는 안 된다.',
    'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 12,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '002011',
    'officialIdentifier': '268659',
    'lawName': '표시ㆍ광고의 공정화에 관한 법률',
    'articleReference': '제3조',
    'title': '부당한 표시ㆍ광고 행위의 금지',
    'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250121',
    'effectiveDate': '20250121',
    'retrievedAt': '2026-08-10T06:51:33.730046Z',
    'contentHash': 'sha256:8a232304b3941209cf6afb47ff8485dec72a80b22d8ea0bd5f72b07f583b5826',
    'boundedProvisionSummary': '사업자는 부당한 표시ㆍ광고 행위를 해서는 안 된다.',
    'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',

## 39. Marketing Source

In [40]:
display(handoff.marketingSourceSnapshot if handoff else {
    'status': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'contract': 'marketing-source-snapshot-v1',
 'schemaVersion': '2.0',
 'snapshotId': 'lab-marketing-source',
 'projectId': 0,
 'selectionId': 0,
 'conceptId': 'C2',
 'marketAnalysisSeedSnapshotId': 'lab-market-seed',
 'marketAnalysisSeedSnapshotHash': 'sha256:8b86432c2ef173e0402afc31488201cea0a8afc80e76e260f94b94c2670f38c6',
 'createdAt': '2026-08-10T06:51:42.104530+00:00',
 'conceptName': '주말 여행 계획 지원 서비스',
 'targetSegment': '주말 1~2일 단기 여행을 자주 계획하는 직장인',
 'problem': '짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.',
 'valueProposition': '사용자는 여행 계획을 쉽게 진행할 수 있다.',
 'positioning': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
 'keyFeatures': ['사용자의 이동 가능 시간 입력 기능', '관심사 기반 여행 일정 추천', '숙박 및 체험 예약 연동 기능'],
 'targetRegion': '한국 전역',
 'revenueModel': '수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.',
 'price': '서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.',
 'pricing': '수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다. · 서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.',
 'channels': ['모바일 앱을 통해 사용자와 소통하며, 소셜 미디어를 통한 마케팅을 진행한다.'],
 'competitorDifferentiators': ['사용자의 이동 가능 시간과 관심사를 실시간으로 반영한 지원, 숙박 및 체험 예약 페이지와의 원활한 연동'],
 'preMarketSomShare': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='주말 여행 시장의 성장과 사용자 편의성 증가에 따른 수요 증가 예상.', assumptions=['주말 여행을 계획하는 직장인 수가 증가할 것', '사용자 경험 개선으로 인한 재사용률 증가']),
 'preMarketSom': PreMarketSomHypothesis(amount=5000000.0, currency='KRW', period='연간', calculationBasis='주말 여행 예약 수수료 기반으로 추정한 시장 규모', assumptions=['주말 여행 예약 수요가 매년 10% 증가할 것', '경쟁 서비스 대비 차별화된 기능으로 시장 점유율 확보 가능'], confidence='MEDIUM'),
 'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
 'allowedClaims': ['사용자의 이동 가능 시간과 관심사를 반영한 맞춤형 여행 일정 제공'],
 'prohibitedClaims': [],
 'requiredDisclosures': ['사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.'],
 'requiredControls': ['통신판매업자는 신고를 해야 한다.',
  '통신판매업자는 거래조건에 대한 정보를 제공해야 한다.',
  '소비자는 청약철회를 할 수 있는 권리가 있다.',
  '청약철회 시 소비자는 이미 공급받은 재화를 반환해야 한다.',
  '사업자는 부가가치세의 과세기간을 준수해야 한다.',
  '사업자는 사업자등록을 신청해야 한다.',
  '사업자는 영수증을 발급해야 한다.',
  '사업자는 약관을 한글로 작성해야 한다.',
  '사업자는 부당한 표시ㆍ광고 행위를 해서는 안 된다.',
  '개인정보를 수집할 때 동의를 받아야 한다.'],
 'communicationRequiredControls': ['통신판매업자는 신고를 해야 한다.',
  '통신판매업자는 거래조건에 대한 정보를 제공해야 한다.',
  '소비자는 청약철회를 할 수 있는 권리가 있다.',
  '청약철회 시 소비자는 이미 공급받은 재화를 반환해야 한다.',
  '사업자는 부가가치세의 과세기간을 준수해야 한다.',
  '사업자는 사업자등록을 신청해야 한다.',
  '사업자는 영수증을 발급해야 한다.',
  '사업자는 약관을 한글로 작성해야 한다.',
  '사업자는 부당한 표시ㆍ광고 행위를 해서는 안 된다.',
  '개인정보를 수집할 때 동의를 받아야 한다.'],
 'officialEvidenceReferences': [{'referenceIndex': 0,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제12조',
   'title': '통신판매업자의 신고 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:448fe0bd6a72942700268999bc17abaf1a130dc75ff98338f016366ffccb8d53',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 1,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제13조',
   'title': '신원 및 거래조건에 대한 정보의 제공',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:6e496bba7781eda4a1e42db7cb6ead3a7f9648a8557ee96ea09e290d3f30b30d',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 2,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제17조',
   'title': '청약철회등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:086921e6e5bc694ea2d723423f266762b50490e33b8739d64e1920b7a13bde5c',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 3,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제18조',
   'title': '청약철회등의 효과',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:48bb8d8484384496bed84e6eac658a1ea9dcd53ed91bc5d6291359764c102642',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 4,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제5조',
   'title': '과세기간',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:55e12be5d081847f6c347a9be100376c35ba524c561e8d24448e063534c29ca9',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 5,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제8조',
   'title': '사업자등록',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:f592e37dcf9ad848267be7603a224ad1645f2b8ef32bd5463d0f81b6296939b2',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 6,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제36조',
   'title': '영수증 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:73a2ea65e521a0d7b21520ba72f17ce4be74a0258a17177073833853d88968f2',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 7,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제53조의2',
   'title': '전자적 용역을 공급하는 국외사업자의 사업자등록 및 납부 등에 관한 특례',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:fb9766cb992d59a2c98a513510e00823fbac4ba1662f6afa5554c0e5e1e5dc18',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 8,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제3조',
   'title': '약관의 작성 및 설명의무 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:1616dce193e178dfd11405c2891a1bdea99e8a3b2e06ee7b662ebcb5d99bea23',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 9,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제5조',
   'title': '약관의 해석',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:f85b7d1c454d2a8ed12a884b224e377844ab60a45906b658e47469009efc00e6',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 10,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제16조',
   'title': '일부 무효의 특칙',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:0719bda3584934dc655f86e42d2bd50b5faeedf32df5de39a409256332337d52',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 11,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제17조',
   'title': '불공정약관조항의 사용금지',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:c443ce12c5268686ed554a0ced386d8c85057d3bf72b69c432f50429172c692a',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 12,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제3조',
   'title': '부당한 표시ㆍ광고 행위의 금지',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:8a232304b3941209cf6afb47ff8485dec72a80b22d8ea0bd5f72b07f583b5826',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 13,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제5조',
   'title': '표시ㆍ광고 내용의 실증 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:175e1d20e79b88964eddbcfa658507a8968209ddba38fe094bc7005015b0ba30',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 14,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제10조',
   'title': '손해배상책임',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:9e32cfffe5aee496b1832d5e3707961c9f4280d83dc0f91deaf66f0318f1de73',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 15,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제17조',
   'title': '벌칙',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:f8efc781c87796884bf25f8d680b1efcd4e223f5e470a5b156122d6d82e15692',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 16,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '005361',
   'officialIdentifier': '286999',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률 시행령',
   'articleReference': '제3조',
   'title': '부당한 표시ㆍ광고의 내용',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0%20%EC%8B%9C%ED%96%89%EB%A0%B9',
   'jurisdiction': 'KR',
   'promulgationDate': '20260616',
   'effectiveDate': '20260701',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:bb13d967a5a68cb02624c80f3ddd5f7baf852a1e9d4661d43c631d3620d01d91',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 17,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '005361',
   'officialIdentifier': '286999',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률 시행령',
   'articleReference': '제4조',
   'title': '실증방법 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0%20%EC%8B%9C%ED%96%89%EB%A0%B9',
   'jurisdiction': 'KR',
   'promulgationDate': '20260616',
   'effectiveDate': '20260701',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:4ee972b82514a4bd88f90041f42bff69d15f6cd68a02ffcef1de2f4d0129aefd',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 18,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '005361',
   'officialIdentifier': '286999',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률 시행령',
   'articleReference': '제5조',
   'title': '실증자료',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0%20%EC%8B%9C%ED%96%89%EB%A0%B9',
   'jurisdiction': 'KR',
   'promulgationDate': '20260616',
   'effectiveDate': '20260701',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:6b8b9f88f5b159b791aa1e4f4521d558ea551933142259e5bb9a59a48e05d825',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 19,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '005361',
   'officialIdentifier': '286999',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률 시행령',
   'articleReference': '제6조',
   'title': '실증자료의 공개',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0%20%EC%8B%9C%ED%96%89%EB%A0%B9',
   'jurisdiction': 'KR',
   'promulgationDate': '20260616',
   'effectiveDate': '20260701',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:9a0527dca29be7e4c086e4f5bacae119ad81d2b016a78ea353f84343d4ffbb41',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 20,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '011357',
   'officialIdentifier': '270351',
   'lawName': '개인정보 보호법',
   'articleReference': '제15조',
   'title': '개인정보의 수집ㆍ이용',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%20%EB%B3%B4%ED%98%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20250401',
   'effectiveDate': '20251002',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:d057e48fdd8c23f93bcfcb814c84c02a71c51f476b2b2f824635725d488e4d9c',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 21,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '011357',
   'officialIdentifier': '270351',
   'lawName': '개인정보 보호법',
   'articleReference': '제16조',
   'title': '개인정보의 수집 제한',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%20%EB%B3%B4%ED%98%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20250401',
   'effectiveDate': '20251002',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:92011a2e3a02220ab77a308a194cdf773752b2c24e3059a67a0e03a80399f032',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 22,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '011357',
   'officialIdentifier': '270351',
   'lawName': '개인정보 보호법',
   'articleReference': '제20조',
   'title': '정보주체 이외로부터 수집한 개인정보의 수집 출처 등 통지',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%20%EB%B3%B4%ED%98%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20250401',
   'effectiveDate': '20251002',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:55c5d509f53ddd4fe40875720902fff238b927862a415b5d68f91faf6a283e3a',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 23,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '011357',
   'officialIdentifier': '270351',
   'lawName': '개인정보 보호법',
   'articleReference': '제22조',
   'title': '동의를 받는 방법',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EA%B0%9C%EC%9D%B8%EC%A0%95%EB%B3%B4%20%EB%B3%B4%ED%98%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20250401',
   'effectiveDate': '20251002',
   'retrievedAt': '2026-08-10T06:51:33.730046Z',
   'contentHash': 'sha256:0a2c63314441f4a7596423f6d8e42a957e7186af1edd0e3e608019dcb8e5f2d7',
   'registryVersion': 'legal-registry-v1'}],
 'hash': 'sha256:54db8a69e9b88bb20eb93fd211c75b390c3908d906357aa1bdc5df0231a00214',
 'sourceSnapshotHash': 'sha256:54db8a69e9b88bb20eb93fd211c75b390c3908d906357aa1bdc5df0231a00214'}

## 40. Contract Compatibility

In [41]:
display(show_downstream_handoff(handoff) if handoff else {
    'contract': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'호환성': 'PASS',
 '구조': 'STRUCTURE_PASS',
 '계약': 'CONTRACT_PASS',
 '필드 매핑':                        v2Field                             downstreamField  \
 0        candidate.conceptName        selectedConcept.identity.conceptName
 1  candidate.solutionMechanism  selectedConcept.solution.solutionMechanism
 2                hypotheses[*]                             finalHypotheses
 3                        legal                                 legalResult

               source  transformed  required
 0  CONCEPT_GENERATED        False      True
 1  CONCEPT_GENERATED        False      True
 2     USER_CONFIRMED         True      True
 3  OFFICIAL_EVIDENCE         True      True  ,
 'Market payload': {'contract': 'market-analysis-seed-snapshot-v1',
  'schemaVersion': '2.0',
  'snapshotId': 'lab-market-seed',
  'projectId': 0,
  'selectionId': 0,
  'conceptId': 'C2',
  'createdAt': '2026-08-10T06:51:42.104530+00:00',
  'sourceSnapshotHash': 'sha256:c80d3ca735a837897aa27872d5da439460d4fc5e7040a0ac3a7c3f46aea70473',
  'originalSeed': {'ideaOverview': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
   'fields': {'ideaOverview': {'value': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'},
    'problem': {'value': '짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'},
    'targetUsers': {'value': '주말 1~2일 단기 여행을 자주 계획하는 직장인',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'}}},
  'aiInterpretation': {'interpretedProblem': '짧은 주말 여행을 계획하는 데 소요되는 시간과 노력을 줄이는 것.',
   'interpretedTargetUsers': '주말에 1~2일 단기 여행을 자주 계획하는 직장인들.',
   'usageContext': '사용자의 이동 가능 시간과 관심사를 고려하여 여행 일정을 자동으로 구성하는 서비스.',
   'industryCategory': '여행 및 관광',
   'researchScope': '주말 여행 계획 서비스에 대한 시장 조사.',
   'conciseIdeaDefinition': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동으로 구성하는 서비스.',
   'targetRegionInterpretation': '대상 지역은 명시되지 않음.',
   'relevantKnownCompetitorContext': '경쟁자는 명시되지 않음.'},
  'selectedConcept': {'identity': {'conceptName': '주말 여행 계획 지원 서비스',
    'conceptDefinition': '사용자의 이동 가능 시간과 관심사를 바탕으로 주말 근거리 여행 일정을 자동 구성하고 숙박·체험 예약 페이지로 연결하는 여행 계획 서비스',
    'introduction': '여행 계획을 지원하여 사용자의 편의를 높이는 서비스.',
    'coreValue': '사용자는 여행 계획을 쉽게 진행할 수 있다.',
    'targetUsers': '주말 1~2일 단기 여행을 자주 계획하는 직장인',
    'industryCategory': '여행 및 관광',
    'researchScope': '주말 여행 계획 서비스에 대한 시장 조사.'},
   'solution': {'problemScenario': '짧은 주말 여행은 이동 시간까지 고려해 일정을 직접 조합하는 데 많은 시간이 든다.',
    'solutionMechanism': '자동으로 생성된 일정은 사용자가 쉽게 예약할 수 있도록 관련 링크를 제공한다.',
    'featureSet': ['사용자의 이동 가능 시간 입력 기능',
     '관심사 기반 여행 일정 추천',
     '숙박 및 체험 예약 연동 기능']},
   'operation': {'actorRoles': ['사용자', '숙박 제공업체', '체험 제공업체'],
    'platformRole': '여행 계획 지원 플랫폼으로서 사용자와 제공업체를 연결한다.',
    'operatingModel': '사용자 데이터를 기반으로 알고리즘을 지속적으로 개선하여 더 나은 여행 계획을 지원한다.',
    'partnerModel': '숙박 및 체험 제공업체와 제휴하여 예약 서비스를 통합한다.',
    'providerRole': '여행 계획 서비스를 제공하는 주체로서 사용자와의 상호작용을 담당한다.',
    'sellerRole': '숙박 및 체험 제공업체로서 예약 서비스를 판매한다.',
    'intermediaryRole': '플랫폼을 통해 사용자와 제공업체 간의 거래를 중개한다.',
    'transactionFlow': ['사용자가 앱에서 여행 일정을 선택한다.',
     '사용자가 예약을 진행한다.',
     '예약이 완료되면 제공업체에 통보된다.'],
    'paymentFlow': ['사용자가 예약 시 결제 정보를 입력한다.',
     '결제가 완료되면 예약 확인이 이루어진다.',
     '제공업체에 수수료가 지급된다.'],
    'personalDataUsage': ['사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.'],
    'physicalActivities': ['배송', '현장 방문', '설치'],
    'partnerRequirements': ['숙박 및 체험 제공업체와의 제휴 계약 체결이 필요하다.'],
    'qualificationRequirements': []},
   'valueSemantics': [{'fieldKey': 'conceptName',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'conceptDefinition',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'introduction',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'coreValue',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'targetUsers',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'industryCategory',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'researchScope',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'targetRegion',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'revenueModel',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'price',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'channels',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'differentiators',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'preMarketSomShareHypothesis',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'preMarketSomHypothesis',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'actorRoles',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'platformRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'problemScenario',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'solutionMechanism',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'featureSet',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'operatingModel',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'partnerModel',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'providerRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'sellerRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'intermediaryRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'transactionFlow',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'paymentFlow',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'personalDataUsage',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'physicalActivities',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'partnerRequirements',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'qualificationRequirements',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'advertisingClaims',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'}],
   'canonicalHash': 'sha256:af3b6d378978e49a7105b871096ac880e96da4ab1a76f2bebeae9b8fbc8c9958'},
  'finalHypotheses': {'targetRegion': {'value': '한국 전역',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'revenueModel': {'value': '수수료 기반 모델로, 사용자가 예약 시 발생하는 수수료로 수익을 창출한다.',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'price': {'value': '서비스 이용 시 발생하는 예약 수수료는 5%로 설정한다.',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'channels': {'value': '모바일 앱을 통해 사용자와 소통하며, 소셜 미디어를 통한 마케팅을 진행한다.',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'differentiators': {'value': '사용자의 이동 가능 시간과 관심사를 실시간으로 반영한 지원, 숙박 및 체험 예약 페이지와의 원활한 연동',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'preMarketSomShare': {'value': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='주말 여행 시장의 성장과 사용자 편의성 증가에 따른 수요 증가 예상.', assumptions=['주말 여행을 계획하는 직장인 수가 증가할 것', '사용자 경험 개선으로 인한 재사용률 증가']),
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'preMarketSom': {'value': PreMarketSomHypothesis(amount=5000000.0, currency='KRW', period='연간', calculationBasis='주말 여행 예약 수수료 기반으로 추정한 시장 규모', assumptions=['주말 여행 예약 수요가 매년 10% 증가할 것', '경쟁 서비스 대비 차별화된 기능으로 시장 점유율 확보 가능'], confidence='MEDIUM'),
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'}},
  'legalResult': {'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
   'safeSummary': '사용자 데이터 보호 및 개인정보 처리 관련 법령 준수 필요.',
   'requiredControls': ['통신판매업자는 신고를 해야 한다.',
    '통신판매업자는 거래조건에 대한 정보를 제공해야 한다.',
    '소비자는 청약철회를 할 수 있는 권리가 있다.',
    '청약철회 시 소비자는 이미 공급받은 재화를 반환해야 한다.',
    '사업자는 부가가치세의 과세기간을 준수해야 한다.',
    '사업자는 사업자등록을 신청해야 한다.',
    '사업자는 영수증을 발급해야 한다.',
    '사업자는 약관을 한글로 작성해야 한다.',
    '사업자는 부당한 표시ㆍ광고 행위를 해서는 안 된다.',
    '개인정보를 수집할 때 동의를 받아야 한다.'],
   'requiredPartnersAndQualifications': ['숙박 및 체험 제공업체와의 제휴 계약 체결이 필요하다.'],
   'prohibitedVariants': [],
   'requiredDisclosures': ['사용자의 이동 가능 시간과 관심사를 수집하여 맞춤형 여행 일정을 제공한다.'],
   'officialEvidenceReferences': [{'referenceIndex': 0,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제12조',
     'title': '통신판매업자의 신고 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:448fe0bd6a72942700268999bc17abaf1a130dc75ff98338f016366ffccb8d53',
     'boundedProvisionSummary': '통신판매업자는 신고를 해야 한다.',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 1,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제13조',
     'title': '신원 및 거래조건에 대한 정보의 제공',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:6e496bba7781eda4a1e42db7cb6ead3a7f9648a8557ee96ea09e290d3f30b30d',
     'boundedProvisionSummary': '통신판매업자는 거래조건에 대한 정보를 제공해야 한다.',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 2,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제17조',
     'title': '청약철회등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:086921e6e5bc694ea2d723423f266762b50490e33b8739d64e1920b7a13bde5c',
     'boundedProvisionSummary': '소비자는 청약철회를 할 수 있는 권리가 있다.',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 3,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제18조',
     'title': '청약철회등의 효과',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:48bb8d8484384496bed84e6eac658a1ea9dcd53ed91bc5d6291359764c102642',
     'boundedProvisionSummary': '청약철회 시 소비자는 이미 공급받은 재화를 반환해야 한다.',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 4,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001571',
     'officialIdentifier': '276117',
     'lawName': '부가가치세법',
     'articleReference': '제5조',
     'title': '과세기간',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20260102',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:55e12be5d081847f6c347a9be100376c35ba524c561e8d24448e063534c29ca9',
     'boundedProvisionSummary': '사업자는 부가가치세의 과세기간을 준수해야 한다.',
     'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 5,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001571',
     'officialIdentifier': '276117',
     'lawName': '부가가치세법',
     'articleReference': '제8조',
     'title': '사업자등록',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20260102',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:f592e37dcf9ad848267be7603a224ad1645f2b8ef32bd5463d0f81b6296939b2',
     'boundedProvisionSummary': '사업자는 사업자등록을 신청해야 한다.',
     'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 6,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001571',
     'officialIdentifier': '276117',
     'lawName': '부가가치세법',
     'articleReference': '제36조',
     'title': '영수증 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20260102',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:73a2ea65e521a0d7b21520ba72f17ce4be74a0258a17177073833853d88968f2',
     'boundedProvisionSummary': '사업자는 영수증을 발급해야 한다.',
     'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 7,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001571',
     'officialIdentifier': '276117',
     'lawName': '부가가치세법',
     'articleReference': '제53조의2',
     'title': '전자적 용역을 공급하는 국외사업자의 사업자등록 및 납부 등에 관한 특례',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20260102',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:fb9766cb992d59a2c98a513510e00823fbac4ba1662f6afa5554c0e5e1e5dc18',
     'boundedProvisionSummary': '국외사업자는 간편사업자등록을 해야 한다.',
     'queryKey': 'sha256:429aa4f8a57d8492b35af70d9b48863ff9fd0a0c6026ce94f2febbc466f58bb8',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 8,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '000667',
     'officialIdentifier': '260021',
     'lawName': '약관의 규제에 관한 법률',
     'articleReference': '제3조',
     'title': '약관의 작성 및 설명의무 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20240206',
     'effectiveDate': '20240807',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:1616dce193e178dfd11405c2891a1bdea99e8a3b2e06ee7b662ebcb5d99bea23',
     'boundedProvisionSummary': '사업자는 약관을 한글로 작성해야 한다.',
     'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 9,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '000667',
     'officialIdentifier': '260021',
     'lawName': '약관의 규제에 관한 법률',
     'articleReference': '제5조',
     'title': '약관의 해석',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20240206',
     'effectiveDate': '20240807',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:f85b7d1c454d2a8ed12a884b224e377844ab60a45906b658e47469009efc00e6',
     'boundedProvisionSummary': '약관은 신의성실의 원칙에 따라 해석되어야 한다.',
     'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 10,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '000667',
     'officialIdentifier': '260021',
     'lawName': '약관의 규제에 관한 법률',
     'articleReference': '제16조',
     'title': '일부 무효의 특칙',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20240206',
     'effectiveDate': '20240807',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',
     'contentHash': 'sha256:0719bda3584934dc655f86e42d2bd50b5faeedf32df5de39a409256332337d52',
     'boundedProvisionSummary': '약관의 일부 무효 시 계약은 나머지 부분만으로 유효하다.',
     'queryKey': 'sha256:e71cfb4d78c3ba6b3c458d97c9b6b31c2f7d35ec9e1b5418ac514c78d5df3a4d',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 11,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '000667',
     'officialIdentifier': '260021',
     'lawName': '약관의 규제에 관한 법률',
     'articleReference': '제17조',
     'title': '불공정약관조항의 사용금지',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20240206',
     'effectiveDate': '20240807',
     'retrievedAt': '2026-08-10T06:51:33.730046Z',

## 41. Trace

In [42]:
display(show_trace(engine.trace))

,순서,시각,stage,action,entity,parent,status,mode,호출,요약,decision,reasonCode
0,1,2026-08-10T06:48:00.070939+00:00,CREATED,CREATED,NaN,NaN,RUNNING,LIVE,NaN,V2 Lab 실행을 생성했습니다.,NaN,None
1,2,2026-08-10T06:48:09.269618+00:00,SAFETY_CHECKING,IDEA_BRIEF_DERIVED,NaN,NaN,PASS,LIVE,1.0,Idea interpretation/readiness를 보존했습니다: READY_F...,NaN,None
2,3,2026-08-10T06:48:09.269632+00:00,SAFETY_CHECKING,READINESS_INCONSISTENT,NaN,NaN,WARNING,LIVE,NaN,READY_FOR_REVIEW이지만 score=0입니다. V2 gating은 막지 ...,READINESS_INCONSISTENT,None
3,4,2026-08-10T06:48:09.301614+00:00,SEED_ANALYZING,ANALYZED,lab-idea-brief,NaN,PASS,LIVE,NaN,필수 3개와 LOCK 3개를 분류했습니다.,NaN,None
4,5,2026-08-10T06:48:09.301864+00:00,SEED_ANALYZING,DESIGN_SPACE_READY,NaN,NaN,PASS,LIVE,NaN,Open=11 Constrained=0 Breadth=EXPLORE,NaN,None
5,6,2026-08-10T06:48:09.349657+00:00,PLANNING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,최대 5개 동적 plan을 요청합니다.,NaN,None
6,7,2026-08-10T06:48:43.269025+00:00,PLANNING,DRAFTS_GENERATED,NaN,NaN,PASS,LIVE,2.0,Plan draft pool=6,NaN,None
7,8,2026-08-10T06:48:43.270326+00:00,PLANNING,NORMALIZED,NaN,NaN,PASS,LIVE,NaN,System metadata를 부여한 Plan=6,NaN,None
8,9,2026-08-10T06:48:53.958564+00:00,PLANNING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,3.0,low-confidence Plan architecture 6개를 batch 분류했...,NaN,None
9,10,2026-08-10T06:48:53.958609+00:00,PLAN_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Opportunity·LOCK·DUPLICATE/VARIANT/DISTINCT 관계...,NaN,None
10,11,2026-08-10T06:49:11.457591+00:00,PLAN_VALIDATING,SELECTED,NaN,NaN,PASS,LIVE,NaN,Plans=5 Rejected=0,NaN,None
11,12,2026-08-10T06:49:21.706163+00:00,EXPANDING,EXPANDED,C1,P1,PASS,LIVE,9.0,P1 → C1,NaN,None
12,13,2026-08-10T06:49:32.422796+00:00,EXPANDING,EXPANDED,C2,P4,PASS,LIVE,10.0,P4 → C2,NaN,None
13,14,2026-08-10T06:49:42.458939+00:00,EXPANDING,EXPANDED,C3,P3,PASS,LIVE,11.0,P3 → C3,NaN,None
14,15,2026-08-10T06:49:51.685402+00:00,EXPANDING,EXPANDED,C4,P5,PASS,LIVE,12.0,P5 → C4,NaN,None
15,16,2026-08-10T06:50:00.242769+00:00,EXPANDING,EXPANDED,C5,P6,PASS,LIVE,13.0,P6 → C5,NaN,None
16,17,2026-08-10T06:50:00.283992+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,None
17,18,2026-08-10T06:50:10.509247+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,14.0,low-confidence Candidate architecture 5개를 batc...,NaN,None
18,19,2026-08-10T06:50:10.509643+00:00,CANDIDATE_VALIDATING,VALIDATED,C1,NaN,PASS,LIVE,NaN,검사 통과,NaN,None
19,20,2026-08-10T06:50:10.510071+00:00,CANDIDATE_VALIDATING,VALIDATED,C2,NaN,PASS,LIVE,NaN,검사 통과,NaN,None
20,21,2026-08-10T06:50:10.510552+00:00,CANDIDATE_VALIDATING,VALIDATED,C3,NaN,PASS,LIVE,NaN,검사 통과,NaN,None
21,22,2026-08-10T06:50:10.511012+00:00,CANDIDATE_VALIDATING,VALIDATED,C4,NaN,PASS,LIVE,NaN,검사 통과,NaN,None
22,23,2026-08-10T06:50:10.511521+00:00,CANDIDATE_VALIDATING,VALIDATED,C5,NaN,PASS,LIVE,NaN,검사 통과,NaN,None
23,24,2026-08-10T06:50:10.511554+00:00,CANDIDATE_VALIDATING,CANDIDATE_PORTFOLIO_READY,NaN,NaN,PASS,LIVE,NaN,"Candidate Portfolio=5/5, recovered=0",READY_FULL,None
24,25,2026-08-10T06:50:10.540538+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 5개의 법률 사실패턴 완결성을 검사합니다.,NaN,None
25,26,2026-08-10T06:50:13.148866+00:00,LEGAL_RECOVERING,BUSINESS_ROLE_SEMANTIC_BATCH,NaN,NaN,PASS,LIVE,15.0,불명확 역할 4개를 1회 batch로 판정했습니다.,BATCH_COMPLETE,None
26,27,2026-08-10T06:50:21.724408+00:00,LEGAL_RECOVERING,LEGAL_FACT_DEPENDENCY_SEMANTIC_BATCH,NaN,NaN,PASS,LIVE,16.0,불명확 dependency 3개를 1회 batch로 판정했습니다.,BATCH_COMPLETE,None
27,28,2026-08-10T06:50:21.726999+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C1,NaN,COMPLETABLE,LIVE,NaN,동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.,COMPLETABLE,None
28,29,2026-08-10T06:50:25.614029+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,None
29,30,2026-08-10T06:50:29.011922+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,18.0,low-confidence Candidate architecture 1개를 batc...,NaN,None
30,31,2026-08-10T06:50:29.012942+00:00,CANDIDATE_VALIDATING,VALIDATED,C1-F1,NaN,PASS,LIVE,NaN,검사 통과,NaN,None
31,32,2026-08-10T06:50:29.012965+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C2,NaN,COMPLETE,LIVE,NaN,법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.,COMPLETE,None
32,33,2026-08-10T06:50:29.012972+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C3,NaN,COMPLETABLE,LIVE,NaN,동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.,COMPLETABLE,None
33,34,2026-08-10T06:50:33.322049+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C4,NaN,COMPLETABLE,LIVE,NaN,동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.,COMPLETABLE,None
34,35,2026-08-10T06:50:37.634760+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C5,NaN,COMPLETABLE,LIVE,NaN,동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.,COMPLETABLE,None
35,36,2026-08-10T06:50:45.567462+00:00,LEGAL_RECOVERING,BUSINESS_ROLE_SEMANTIC_BATCH,NaN,NaN,PASS,LIVE,22.0,불명확 역할 1개를 1회 batch로 판정했습니다.,BATCH_COMPLETE,None
36,37,2026-08-10T06:51:41.565718+00:00,LEGAL_REVIEWING,REVIEWED,C2,NaN,ACCEPT,LIVE,23.0,사용자 데이터 보호 및 개인정보 처리 관련 법령 준수 필요.,ACCEPT,None
37,38,2026-08-10T06:51:41.589813+00:00,LEGAL_RECOVERING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Legal route별 복구를 수행합니다.,NaN,None
38,39,2026-08-10T06:51:42.110989+00:00,PORTFOLIO_VALIDATING,HANDOFF_VALIDATED,C2,NaN,PASS,LIVE,NaN,downstream contract compatibility=PASS,NaN,None

## 42. Provider/Legal Usage

In [43]:
display(show_provider_usage(engine.gateway.usage))
print('상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.')

,논리 작업,상위 외부 작업,논리 stage별,상위 외부 작업 stage별,재시도,소요(ms),모드별,token,보고 비용
0,23,23,"{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...","{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...",0,220883,{'LIVE': 23},None,None

상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.

## 43. Replay Manifest

In [44]:
display(show_replay_manifest(engine.gateway))

{'status': 'REPLAY_PARTIAL',
 'entries':                    operation  \
 0               LEGAL_REVIEW
 1          SEMANTIC_RELATION
 2    NORMALIZE_ARCHITECTURES
 3                     EXPAND
 4                  PLAN_POOL
 ..                       ...
 425                   EXPAND
 426    LEGAL_FACT_COMPLETION
 427    IDEA_BRIEF_DERIVATION
 428                PLAN_POOL
 429             LEGAL_REVIEW

                                                   hash operationVersion  \
 0    00489dd62bff3c4b9e8711093fb3e398a39dde1547de32...               v3
 1    00c1eeb4f93989a6db3891fb7a22355a71a68800a6f641...               v3
 2    013ebfc11d61a317c1041ddcf75902b1dab0d310e73666...               v1
 3    02bf209b45f806d67ec78f5bdc5e0e24bf99e05fbd297f...               v3
 4    038e1d9753b8c07ad835823495b54906a14fb6542c3c70...               v3
 ..                                                 ...              ...
 425  fc18f5423064548add8b992951606d26f76ac8795cfb7f...               v3
 426  fc333103264d3fbc56f5df306b221a16869fa737da87ab...               v1
 427  fc5b3fe1b2fb09f8b0b6587abc4a067f3c1f1682a4e68c...               v2
 428  fd4ea7d8f4c176971dc390682c54fb6d7bc7428fa2d79a...               v3
 429  ff7ecbd2ee5cb90f030bc7972f25779b05155b203be50c...               v3

                                     promptVersion schemaVersion  recordExists  \
 0                         concept-legal-review-v3           2.0          True
 1                   concept-portfolio-relation-v3           2.0          True
 2    concept-portfolio-architecture-classifier-v1           2.0          True
 3          concept-portfolio-generic-candidate-v3           2.0          True
 4               concept-portfolio-generic-plan-v3           2.0          True
 ..                                            ...           ...           ...
 425        concept-portfolio-generic-candidate-v3           2.0          True
 426              concept-legal-fact-completion-v1           2.0          True
 427                         idea-brief-current-v2           2.0          True
 428             concept-portfolio-generic-plan-v3           2.0          True
 429                       concept-legal-review-v3           2.0          True

                             timestamp  versionCompatible
 0    2026-08-10T05:26:30.277902+00:00               True
 1    2026-08-10T05:23:00.398650+00:00               True
 2    2026-08-10T06:48:53.957430+00:00               True
 3    2026-08-10T04:54:06.673791+00:00               True
 4    2026-08-10T02:15:13.524746+00:00               True
 ..                                ...                ...
 425  2026-08-10T06:50:00.241348+00:00               True
 426  2026-08-10T03:54:15.847132+00:00               True
 427  2026-08-10T05:07:12.765057+00:00               True
 428  2026-08-10T04:53:21.046707+00:00               True
 429  2026-08-10T05:18:41.881979+00:00               True

 [430 rows x 8 columns]}

## 44. One-click MOCK

In [45]:
mock_result = None
if LIVE_TEST_LEVEL == 'FULL_E2E' and MODE != 'LIVE':
    mock_result = await ConceptPortfolioEngine('MOCK').run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=True)
display(show_run_summary(mock_result) if mock_result else {'status': 'SKIPPED'})
assert mock_result is None or (mock_result.handoff and mock_result.handoff.contractStatus == 'CONTRACT_PASS')

{'status': 'SKIPPED'}

## 45. One-click REPLAY

In [46]:
RUN_ONE_CLICK_REPLAY = False
replay_result = None
if RUN_ONE_CLICK_REPLAY:
    replay_gateway = ProviderGateway('REPLAY', recordings_dir=RECORDINGS_DIR)
    replay_result = await ConceptPortfolioEngine('REPLAY', gateway=replay_gateway).run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=False)
display(show_run_summary(replay_result) if replay_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}

## 46. One-click LIVE

In [47]:
RUN_ONE_CLICK_LIVE = True
live_result = None
if RUN_ONE_CLICK_LIVE and LIVE_TEST_LEVEL == 'ONE_CLICK':
    assert MODE == 'LIVE', 'MODE=LIVE를 먼저 명시하세요.'
    one_click_gateway = ProviderGateway('LIVE', recordings_dir=RECORDINGS_DIR)
    one_click_engine = ConceptPortfolioEngine('LIVE', gateway=one_click_gateway)
    live_result = await one_click_engine.run_full(TEST_INPUT, max_concepts=MAX_CONCEPTS,
                                                  auto_confirm_hypotheses=False)
display(show_run_summary(live_result) if live_result else {'status': 'SKIPPED'})
if live_result:
    display(show_live_validation_summary(LIVE_SCENARIO, live_result))
    display(show_required_inputs(live_result))
    display(show_pre_legal_exclusions(live_result))
    display(show_legal_resolutions(live_result))
    if live_result.runStatus.value == 'FAILED':
        display(show_run_failure(live_result))
        display(show_provider_failure(one_click_engine.gateway))
        display(show_provider_usage(live_result.providerUsage))
        display(show_trace(live_result.trace[-20:]))
        display({'unresolvedCandidates': live_result.unresolvedCandidates,
                 'lastSuccessfulStage': live_result.failureDiagnostics.lastSuccessfulStage if live_result.failureDiagnostics else None,
                 'firstFailedStage': live_result.failureDiagnostics.firstFailedStage if live_result.failureDiagnostics else None})

{'status': 'SKIPPED'}