## 00. Quick Start

In [1]:
print('Concept Portfolio V2 Lab — staged와 one-click은 동일 Core를 사용합니다.')
print('LIVE_TEST_LEVEL로 CORE / LEGAL_C1 / FULL_E2E / ONE_CLICK 중 하나만 선택하세요.')

Concept Portfolio V2 Lab — staged와 one-click은 동일 Core를 사용합니다.
LIVE_TEST_LEVEL로 CORE / LEGAL_C1 / FULL_E2E / ONE_CLICK 중 하나만 선택하세요.

## 01. Environment

In [2]:
import os, sys, json
from pathlib import Path
from IPython.display import display
SEARCH_ROOTS = [Path.cwd(), *Path.cwd().parents]
AI_ROOT = next((p for p in SEARCH_ROOTS if (p / 'app').is_dir()), None)
if AI_ROOT is None: AI_ROOT = next((p / 'ai' for p in SEARCH_ROOTS if (p / 'ai' / 'app').is_dir()))
if str(AI_ROOT) not in sys.path: sys.path.insert(0, str(AI_ROOT))
print({'python': sys.version.split()[0], 'aiRoot': str(AI_ROOT)})

{'python': '3.14.5', 'aiRoot': 'C:\\Users\\seewo\\Desktop\\big_proj_01\\new_3\\ai'}

## 02. MODE

In [3]:
MODE = 'LIVE'  # MOCK | REPLAY | LIVE
RECORDINGS_DIR = AI_ROOT / 'recordings' / 'concept_portfolio_v2'
print({'mode': MODE, 'liveExternalOperationsEnabled': MODE == 'LIVE'})

{'mode': 'LIVE', 'liveExternalOperationsEnabled': True}

## 03. Environment Check

In [4]:
LIVE_ENV_KEYS = ['AI_PROVIDER', 'AI_API_KEY', 'AI_MODEL', 'MOLEG_API_KEY', 'LEGAL_REGISTRY_VERSION']
env_status = {key: bool(os.getenv(key)) for key in LIVE_ENV_KEYS}
print(env_status if MODE == 'LIVE' else {'mode': MODE, 'message': '외부 환경변수 불필요'})

{'AI_PROVIDER': True, 'AI_API_KEY': True, 'AI_MODEL': True, 'MOLEG_API_KEY': True, 'LEGAL_REGISTRY_VERSION': True}

## 04. Schema Preflight

In [5]:
from app.concept_portfolio_v2 import ConceptPortfolioEngine, ProviderGateway, ProviderMode
from app.concept_portfolio_v2.adapters import CurrentLegalAdapter
from app.concept_portfolio_v2.diagnostics.notebook_view import *
gateway = ProviderGateway(MODE, recordings_dir=RECORDINGS_DIR)
engine = ConceptPortfolioEngine(MODE, gateway=gateway)
schema_preflight = engine.schema_preflight_report()
display(show_schema_preflight(schema_preflight))
assert schema_preflight.status == 'PASS' and schema_preflight.providerCalls == 0

                                스키마    상태  실패  Provider 호출
0                     PlanDraftPool  PASS  []            0
1             ConceptCandidateDraft  PASS  []            0
2        SemanticDistinctnessResult  PASS  []            0
3            SemanticFidelityResult  PASS  []            0
4         SemanticArchitectureBatch  PASS  []            0
5           SemanticHypothesisBatch  PASS  []            0
6         BusinessRoleSemanticBatch  PASS  []            0
7  LegalFactDependencySemanticBatch  PASS  []            0
8          LegalFactCompletionPatch  PASS  []            0

## 05. Input

In [6]:
SCENARIO_FILE = AI_ROOT / 'fixtures' / 'concept_portfolio_v2' / 'live_scenarios.json'
SCENARIOS = {item['scenarioId']: item for item in json.loads(SCENARIO_FILE.read_text(encoding='utf-8'))}
LIVE_SCENARIO = 'B2B_AI_SALES_ASSISTANT'
LIVE_TEST_LEVEL = 'FULL_E2E'  # CORE | LEGAL_C1 | FULL_E2E | ONE_CLICK
RUN_STAGED_CORE = LIVE_TEST_LEVEL in {'CORE', 'LEGAL_C1', 'FULL_E2E'}
RUN_STAGED_LEGAL = LIVE_TEST_LEVEL in {'LEGAL_C1', 'FULL_E2E'}
RUN_STAGED_FULL = LIVE_TEST_LEVEL == 'FULL_E2E'
scenario = SCENARIOS[LIVE_SCENARIO]
TEST_INPUT = {key: scenario[key] for key in ('ideaOverview', 'problem', 'targetUsers')}
MAX_CONCEPTS = 5
display({'scenario': LIVE_SCENARIO, 'testLevel': LIVE_TEST_LEVEL, 'domain': scenario['domain'],
         'expectedStructuralFeatures': scenario['expectedStructuralFeatures']})

{'scenario': 'B2B_AI_SALES_ASSISTANT',
 'testLevel': 'FULL_E2E',
 'domain': 'B2B AI SaaS',
 'expectedStructuralFeatures': ['디지털 SaaS', '물리 활동 비필수', '비마켓플레이스']}

## 06. Idea Brief Derivation

In [7]:
seed = engine.seed_adapter.adapt(TEST_INPUT)
idea_context = None
if RUN_STAGED_CORE:
    engine._reset()
    idea_context = await engine.derive_idea_brief(seed)
print({'ideaCallComplete': bool(idea_context), 'interpretationPresent': bool(seed.interpretation),
       'stagedCore': RUN_STAGED_CORE})

{'ideaCallComplete': True, 'interpretationPresent': True, 'stagedCore': True}

## 07. Safety

In [8]:
display(idea_context.safetyReview.model_dump(mode='json') if idea_context else {'status': 'SKIPPED'})
assert idea_context is None or idea_context.safetyReview.passed

{'decision': 'ALLOW',
 'categories': [],
 'restrictions': [],
 'userFacingReason': '이 아이디어는 안전하며, 중소기업 영업팀의 효율성을 높이는 데 기여할 수 있습니다.'}

## 08. AI가 이해한 아이디어

In [9]:
display(show_idea_interpretation(idea_context) if idea_context else {'status': 'SKIPPED'})

,항목,AI 이해 결과
0,interpretedProblem,영업 담당자가 회의 및 이메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실...
1,interpretedTargetUsers,별도의 영업 운영 인력이 부족한 중소기업 영업팀을 대상으로 합니다.
2,usageContext,중소기업의 영업팀에서 회의 기록과 이메일을 효율적으로 관리하고 CRM에 입력하는 데...
3,industryCategory,소프트웨어/AI 도구
4,researchScope,중소기업의 영업 효율성 향상에 관한 연구
5,conciseIdeaDefinition,AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후...
6,targetRegionInterpretation,
7,relevantKnownCompetitorContext,

## 09. Readiness / Summary / commitments

In [10]:
display(show_idea_readiness(idea_context) if idea_context else {'status': 'SKIPPED'})

{'readiness': {'status': 'READY_FOR_REVIEW',
  'score': 0,
  'missingFieldKeys': []},
 'readinessDiagnostic': 'READINESS_INCONSISTENT',
 'userFacingSummary': '이 아이디어는 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구입니다.',
 'commitmentCandidates': [],
 'contradictions': [],
 'questions': []}

## 10. Seed Analysis

In [11]:
analysis = await engine.analyze_seed(seed) if RUN_STAGED_CORE else None
display(show_seed_analysis(analysis) if analysis else {'status': 'SKIPPED'})

        구분                                                  값
0     탐색 폭                                            EXPLORE
1  다양성 수용량                                                  5
2       설명  선택 입력 LOCK 0개로 11개 설계 차원이 열려 있습니다. diversityCa...

## 11. Generic Opportunity Kernel

In [12]:
display(analysis.opportunityKernel.model_dump(mode='json') if analysis else {'status': 'SKIPPED'})

{'problemCore': '영업 담당자가 회의 및 이메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어드는 문제를 해결합니다.',
 'targetCore': '별도의 영업 운영 인력이 부족한 중소기업 영업팀을 대상으로 합니다.',
 'useContexts': ['중소기업의 영업팀에서 회의 기록과 이메일을 효율적으로 관리하고 CRM에 입력하는 데 사용됩니다.'],
 'intentComponents': ['AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치',
  '고객별 영업 액션을 제안하는 도구입니다.'],
 'mustPreserve': ['영업 담당자가 회의 및 이메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어드는 문제를 해결합니다.',
  '별도의 영업 운영 인력이 부족한 중소기업 영업팀을 대상으로 합니다.',
  'AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치 및 고객별 영업 액션을 제안하는 도구입니다.'],
 'maySpecialize': ['핵심 대상의 의미 있는 하위 세그먼트',
  '핵심 사용 맥락의 구체화',
  '가치 제안 또는 offer의 구체화'],
 'forbiddenDriftSummary': '핵심 문제와 대상이 모두 무관한 기회로 교체되면 범위를 벗어납니다.'}

## 12. Design Space

In [13]:
display(show_design_space(analysis) if analysis else {'status': 'SKIPPED'})

,분류,필드,값
0,SOURCE_LOCK,ideaOverview,중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별...
1,SOURCE_LOCK,problem,영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고...
2,SOURCE_LOCK,targetUsers,별도 영업 운영 인력이 부족한 중소기업 영업팀
3,SEMANTIC_ANCHOR,ideaOverview,중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별...
4,SEMANTIC_ANCHOR,problem,영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고...
5,SEMANTIC_ANCHOR,targetUsers,별도 영업 운영 인력이 부족한 중소기업 영업팀
6,OPEN,solutionMechanism,변경 가능
7,OPEN,valueDelivery,변경 가능
8,OPEN,operatingModel,변경 가능
9,OPEN,supplyStructure,변경 가능
10,OPEN,partnerModel,변경 가능
11,OPEN,transactionFlow,변경 가능
12,OPEN,fulfillment,변경 가능
13,OPEN,platformRole,변경 가능
14,OPEN,commercialFlow,변경 가능
15,OPEN,dataDependency,변경 가능
16,OPEN,physicalDependency,변경 가능

## 13. Generate and Adaptively Replenish Plan Pool

In [14]:
plan_validation = (await engine.prepare_portfolio_plans(seed, analysis, max_concepts=MAX_CONCEPTS)
                   if RUN_STAGED_CORE else None)
plans = engine._last_plan_pool if plan_validation else []
print({'totalPlans': len(plans),
       'planningRounds': plan_validation.planningRounds if plan_validation else 0,
       'replenishmentRequested': plan_validation.replenishmentRequested if plan_validation else 0})

{'totalPlans': 7, 'planningRounds': 1, 'replenishmentRequested': 0}

## 14. Plan Count / Adaptive Replenishment Check

In [15]:
display(show_plan_pool_status(engine._last_plan_pool_status) if plan_validation else {'status': 'SKIPPED'})
display({'planningRounds': plan_validation.planningRounds if plan_validation else 0,
         'replenishmentRequested': plan_validation.replenishmentRequested if plan_validation else 0,
         'adaptiveReplenishmentUsed': bool(plan_validation and plan_validation.planningRounds > 1)})

,requestedPoolSize,returnedPoolSize,initialTarget,reserveTarget,reserveAvailable,status
0,7,7,5,2,2,RESERVE_READY

{'planningRounds': 1,
 'replenishmentRequested': 0,
 'adaptiveReplenishmentUsed': False}

## 15. Korean Plan Display

In [16]:
display(show_portfolio_plans(plan_validation.acceptedPlans + plan_validation.reservePlans)
        if plan_validation else {'status': 'SKIPPED'})

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P1,중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구,SELECTED,0.8466,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 회의 기록과 이메일을 효율적으로 관리하고 CRM에 입력하는 데...,AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.,AI 기술을 활용하여 회의 및 이메일 내용을 자동으로 정리하고 CRM에 입력합니다.,중소기업 영업팀의 업무 효율성을 높이기 위해 AI 기반의 자동화 도구를 제공합니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 업무 효율성을 높이고 고객 대응 시간을 늘리기 위해 필수적인 도구...
1,P3,중소기업 영업팀의 회의 및 이메일 관리 최적화 도구,SELECTED,0.7753,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 회의 및 이메일을 효율적으로 관리하는 데 사용됩니다.,효율적인 회의 및 이메일 관리로 영업팀의 생산성을 극대화합니다.,회의 및 이메일 내용을 자동으로 정리하여 영업팀의 업무 효율성을 높입니다.,중소기업 영업팀의 회의 및 이메일 관리를 최적화하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 회의 및 이메일 관리를 최적화하여 생산성을 높이는 필수 도구입니다.
2,P2,AI 기반 고객 맞춤형 영업 액션 제안 도구,SELECTED,0.7652,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 기타 운영,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 고객별 맞춤형 영업 전략을 수립하는 데 사용됩니다.,AI를 통해 고객의 행동 패턴을 분석하고 최적의 영업 액션을 제안합니다.,고객 데이터를 분석하여 맞춤형 영업 액션을 자동으로 제안합니다.,중소기업 영업팀이 고객 맞춤형 전략을 쉽게 수립할 수 있도록 지원하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀이 고객 맞춤형 전략을 쉽게 수립할 수 있도록 지원하는 필수 도구입니다.
3,P6,AI 기반 영업팀 성과 분석 도구,SELECTED,0.6090,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 기타 운영,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 성과 분석 및 개선 전략 수립에 사용됩니다.,AI를 통해 영업팀의 성과를 분석하고 최적의 개선점을 제안합니다.,영업팀의 성과 데이터를 분석하여 개선점을 도출합니다.,중소기업 영업팀의 성과 분석을 지원하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 성과 분석을 지원하여 개선점을 제안하는 필수 도구입니다.
4,P4,AI 기반 영업팀 업무 효율성 향상 도구,SELECTED,0.5676,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 업무 효율성을 높이는 데 사용됩니다.,AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.,AI 기술을 활용하여 영업팀의 업무를 자동화합니다.,중소기업 영업팀의 업무 효율성을 높이기 위한 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 업무 효율성을 높이고 고객 대응 시간을 늘리기 위해 필수적인 도구...
5,P5,중소기업 영업팀을 위한 통합 영업 관리 도구,RESERVE,0.6398,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 통합된 영업 관리 도구로 사용됩니다.,효율적인 회의 및 이메일 관리와 고객 맞춤형 영업 액션 제안을 통해 영업팀의 생산성...,회의 및 이메일 내용을 자동으로 정리하고 고객 맞춤형 영업 액션을 제안합니다.,중소기업 영업팀의 업무 효율성을 높이기 위한 통합 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 업무 효율성을 높이고 고객 대응 시간을 늘리기 위해 필수적인 통합...
6,P7,중소기업 영업팀의 CRM 통합 관리 도구,RESERVE,0.6304,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 CRM과 회의 및 이메일 관리를 통합하여 사용됩니다.,효율적인 CRM 관리와 회의 및 이메일 관리를 통해 영업팀의 생산성을 극대화합니다.,CRM과 회의 및 이메일 내용을 자동으로 정리하여 영업팀의 업무 효율성을 높입니다.,중소기업 영업팀의 CRM 관리와 회의 및 이메일 관리를 통합하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 CRM 관리와 회의 및 이메일 관리를 통합하여 생산성을 높이는 필...

## 16. Plan Lock/Intent Validation

In [17]:
display({'accepted': [p.planId for p in plan_validation.acceptedPlans] if plan_validation else [],
         'rejected': [p.model_dump(mode='json') for p in plan_validation.rejectedPlans]
                     if plan_validation else []})

{'accepted': ['P1', 'P3', 'P2', 'P6', 'P4'], 'rejected': []}

## 17. Portfolio Family / Variant / Distinct

In [18]:
display(show_plan_diversity(plan_validation.diversity) if plan_validation else {'status': 'SKIPPED'})

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,P1,P2,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:OTHER,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, customerInteractionModel, useC...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,P1,P3,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, useCaseThesis, value...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,P2,P3,DISTINCT,SAAS_TOOL:OTHER,SAAS_TOOL:PARTNER_NETWORK,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,P1,P4,VARIANT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, useCaseThesis, offer...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
4,P2,P4,DISTINCT,SAAS_TOOL:OTHER,SAAS_TOOL:PARTNER_NETWORK,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
5,P3,P4,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,P1,P5,VARIANT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, useCaseThesis, value...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
7,P2,P5,DISTINCT,SAAS_TOOL:OTHER,SAAS_TOOL:PARTNER_NETWORK,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
8,P3,P5,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,P4,P5,VARIANT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
10,P1,P6,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:OTHER,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, customerInteractionModel, useC...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
11,P2,P6,DISTINCT,SAAS_TOOL:OTHER,SAAS_TOOL:OTHER,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
12,P3,P6,VARIANT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:OTHER,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
13,P4,P6,VARIANT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:OTHER,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
14,P5,P6,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:OTHER,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
15,P1,P7,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, useCaseThesis, value...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
16,P2,P7,DISTINCT,SAAS_TOOL:OTHER,SAAS_TOOL:PARTNER_NETWORK,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
17,P3,P7,VARIANT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
18,P4,P7,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
19,P5,P7,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","useCaseThesis, valuePropositionThesis, offerTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
20,P6,P7,DISTINCT,SAAS_TOOL:OTHER,SAAS_TOOL:PARTNER_NETWORK,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, useCaseThesis, valuePropositio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.

## 18. Selected + Reserve Plans

In [19]:
selected_plans = plan_validation.acceptedPlans if plan_validation else []
reserve_plans = plan_validation.reservePlans if plan_validation else []
display(show_portfolio_plans(selected_plans + reserve_plans))
display({'selected': [p.planId for p in selected_plans], 'reserve': [p.planId for p in reserve_plans]})

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P1,중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구,SELECTED,0.8466,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 회의 기록과 이메일을 효율적으로 관리하고 CRM에 입력하는 데...,AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.,AI 기술을 활용하여 회의 및 이메일 내용을 자동으로 정리하고 CRM에 입력합니다.,중소기업 영업팀의 업무 효율성을 높이기 위해 AI 기반의 자동화 도구를 제공합니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 업무 효율성을 높이고 고객 대응 시간을 늘리기 위해 필수적인 도구...
1,P3,중소기업 영업팀의 회의 및 이메일 관리 최적화 도구,SELECTED,0.7753,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 회의 및 이메일을 효율적으로 관리하는 데 사용됩니다.,효율적인 회의 및 이메일 관리로 영업팀의 생산성을 극대화합니다.,회의 및 이메일 내용을 자동으로 정리하여 영업팀의 업무 효율성을 높입니다.,중소기업 영업팀의 회의 및 이메일 관리를 최적화하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 회의 및 이메일 관리를 최적화하여 생산성을 높이는 필수 도구입니다.
2,P2,AI 기반 고객 맞춤형 영업 액션 제안 도구,SELECTED,0.7652,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 기타 운영,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 고객별 맞춤형 영업 전략을 수립하는 데 사용됩니다.,AI를 통해 고객의 행동 패턴을 분석하고 최적의 영업 액션을 제안합니다.,고객 데이터를 분석하여 맞춤형 영업 액션을 자동으로 제안합니다.,중소기업 영업팀이 고객 맞춤형 전략을 쉽게 수립할 수 있도록 지원하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀이 고객 맞춤형 전략을 쉽게 수립할 수 있도록 지원하는 필수 도구입니다.
3,P6,AI 기반 영업팀 성과 분석 도구,SELECTED,0.6090,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 기타 운영,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 성과 분석 및 개선 전략 수립에 사용됩니다.,AI를 통해 영업팀의 성과를 분석하고 최적의 개선점을 제안합니다.,영업팀의 성과 데이터를 분석하여 개선점을 도출합니다.,중소기업 영업팀의 성과 분석을 지원하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 성과 분석을 지원하여 개선점을 제안하는 필수 도구입니다.
4,P4,AI 기반 영업팀 업무 효율성 향상 도구,SELECTED,0.5676,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 업무 효율성을 높이는 데 사용됩니다.,AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.,AI 기술을 활용하여 영업팀의 업무를 자동화합니다.,중소기업 영업팀의 업무 효율성을 높이기 위한 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 업무 효율성을 높이고 고객 대응 시간을 늘리기 위해 필수적인 도구...
5,P5,중소기업 영업팀을 위한 통합 영업 관리 도구,RESERVE,0.6398,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 통합된 영업 관리 도구로 사용됩니다.,효율적인 회의 및 이메일 관리와 고객 맞춤형 영업 액션 제안을 통해 영업팀의 생산성...,회의 및 이메일 내용을 자동으로 정리하고 고객 맞춤형 영업 액션을 제안합니다.,중소기업 영업팀의 업무 효율성을 높이기 위한 통합 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 업무 효율성을 높이고 고객 대응 시간을 늘리기 위해 필수적인 통합...
6,P7,중소기업 영업팀의 CRM 통합 관리 도구,RESERVE,0.6304,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",SaaS 도구 · 파트너 네트워크,별도의 영업 운영 인력이 부족한 중소기업 영업팀,중소기업의 영업팀에서 CRM과 회의 및 이메일 관리를 통합하여 사용됩니다.,효율적인 CRM 관리와 회의 및 이메일 관리를 통해 영업팀의 생산성을 극대화합니다.,CRM과 회의 및 이메일 내용을 자동으로 정리하여 영업팀의 업무 효율성을 높입니다.,중소기업 영업팀의 CRM 관리와 회의 및 이메일 관리를 통합하는 도구입니다.,"{'businessRole': 'SAAS_TOOL', 'operatingModel'...",중소기업 영업팀의 CRM 관리와 회의 및 이메일 관리를 통합하여 생산성을 높이는 필...

{'selected': ['P1', 'P3', 'P2', 'P6', 'P4'], 'reserve': ['P5', 'P7']}

## 19. Candidate 1

In [20]:
candidate_one = (await engine.expand_plan(seed, selected_plans[0], 1)
                 if RUN_STAGED_CORE and selected_plans else None)
display(show_candidates([candidate_one]) if candidate_one else [])

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구,AI 알고리즘이 회의 및 이메일 내용을 자동으로 분석하고 CRM에 입력합니다.,SaaS 도구 · 파트너 네트워크,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.

## 20. Candidate 1 Korean/Governance

In [21]:
candidate_one_reports = []
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'status': 'PENDING_FULL_CANDIDATE_RECOVERY'})

{'candidateId': 'C1', 'status': 'PENDING_FULL_CANDIDATE_RECOVERY'}

## 21. Candidate 1 Actual Generic Descriptor

In [22]:
display(show_concept_descriptors([candidate_one]) if candidate_one else [])

,entityId,family,dimension,code,confidence,source
0,C1,SAAS_TOOL:PARTNER_NETWORK,businessRole,SAAS_TOOL,HIGH,RULE
1,C1,SAAS_TOOL:PARTNER_NETWORK,operatingModel,PARTNER_NETWORK,HIGH,RULE
2,C1,SAAS_TOOL:PARTNER_NETWORK,partnerModel,PARTNER_NETWORK,HIGH,RULE
3,C1,SAAS_TOOL:PARTNER_NETWORK,deliveryModel,DIGITAL,HIGH,RULE
4,C1,SAAS_TOOL:PARTNER_NETWORK,transactionModel,OTHER,LOW,UNKNOWN
5,C1,SAAS_TOOL:PARTNER_NETWORK,monetizationModel,SUBSCRIPTION,HIGH,RULE
6,C1,SAAS_TOOL:PARTNER_NETWORK,customerInteractionModel,OTHER,LOW,UNKNOWN
7,C1,SAAS_TOOL:PARTNER_NETWORK,dataDependency,MATERIAL,NaN,NaN
8,C1,SAAS_TOOL:PARTNER_NETWORK,physicalDependency,NONE,NaN,NaN

## 22. Candidate 1 Fidelity

In [23]:
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'})

{'candidateId': 'C1',
 'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'}

## 23. Remaining Candidates

In [24]:
remaining_candidates = []
if RUN_STAGED_CORE:
    for i, plan in enumerate(selected_plans[1:], 2):
        remaining_candidates.append(await engine.expand_plan(seed, plan, i))
candidate_drafts = ([candidate_one] if candidate_one else []) + remaining_candidates
display(show_candidates(candidate_drafts))

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구,AI 알고리즘이 회의 및 이메일 내용을 자동으로 분석하고 CRM에 입력합니다.,SaaS 도구 · 파트너 네트워크,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
1,C2,L2,None,중소기업 영업팀의 회의 및 이메일 관리 최적화 도구,AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.,SaaS 도구 · 파트너 네트워크,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
2,C3,L3,None,AI 기반 고객 맞춤형 영업 액션 제안 도구,AI 알고리즘이 고객 데이터를 분석하여 실시간으로 영업 액션을 제안합니다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
3,C4,L4,None,AI 기반 영업팀 성과 분석 도구,AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델(월별 또는 연별 요금제),클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
4,C5,L5,None,AI 기반 영업팀 업무 효율성 향상 도구,AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.,거래 중개 · 파트너 네트워크,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.

## 24. Candidate Actual Generic Descriptors

In [25]:
display(show_concept_descriptors(candidate_drafts))

,entityId,family,dimension,code,confidence,source
0,C1,SAAS_TOOL:PARTNER_NETWORK,businessRole,SAAS_TOOL,HIGH,RULE
1,C1,SAAS_TOOL:PARTNER_NETWORK,operatingModel,PARTNER_NETWORK,HIGH,RULE
2,C1,SAAS_TOOL:PARTNER_NETWORK,partnerModel,PARTNER_NETWORK,HIGH,RULE
3,C1,SAAS_TOOL:PARTNER_NETWORK,deliveryModel,DIGITAL,HIGH,RULE
4,C1,SAAS_TOOL:PARTNER_NETWORK,transactionModel,OTHER,LOW,UNKNOWN
5,C1,SAAS_TOOL:PARTNER_NETWORK,monetizationModel,SUBSCRIPTION,HIGH,RULE
6,C1,SAAS_TOOL:PARTNER_NETWORK,customerInteractionModel,OTHER,LOW,UNKNOWN
7,C1,SAAS_TOOL:PARTNER_NETWORK,dataDependency,MATERIAL,NaN,NaN
8,C1,SAAS_TOOL:PARTNER_NETWORK,physicalDependency,NONE,NaN,NaN
9,C2,SAAS_TOOL:PARTNER_NETWORK,businessRole,SAAS_TOOL,HIGH,RULE
10,C2,SAAS_TOOL:PARTNER_NETWORK,operatingModel,PARTNER_NETWORK,HIGH,RULE
11,C2,SAAS_TOOL:PARTNER_NETWORK,partnerModel,PARTNER_NETWORK,HIGH,RULE
12,C2,SAAS_TOOL:PARTNER_NETWORK,deliveryModel,DIGITAL,HIGH,RULE
13,C2,SAAS_TOOL:PARTNER_NETWORK,transactionModel,OTHER,LOW,UNKNOWN
14,C2,SAAS_TOOL:PARTNER_NETWORK,monetizationModel,SUBSCRIPTION,HIGH,RULE
15,C2,SAAS_TOOL:PARTNER_NETWORK,customerInteractionModel,OTHER,LOW,UNKNOWN
16,C2,SAAS_TOOL:PARTNER_NETWORK,dataDependency,MATERIAL,NaN,NaN
17,C2,SAAS_TOOL:PARTNER_NETWORK,physicalDependency,NONE,NaN,NaN
18,C3,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
19,C3,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
20,C3,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
21,C3,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
22,C3,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
23,C3,OTHER:OTHER,monetizationModel,SUBSCRIPTION,HIGH,RULE
24,C3,OTHER:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
25,C3,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
26,C3,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN
27,C4,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
28,C4,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
29,C4,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
30,C4,INTERMEDIARY:OTHER,deliveryModel,DIGITAL,HIGH,RULE
31,C4,INTERMEDIARY:OTHER,transactionModel,OTHER,LOW,UNKNOWN
32,C4,INTERMEDIARY:OTHER,monetizationModel,SUBSCRIPTION,HIGH,RULE
33,C4,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
34,C4,INTERMEDIARY:OTHER,dataDependency,MATERIAL,NaN,NaN
35,C4,INTERMEDIARY:OTHER,physicalDependency,NONE,NaN,NaN
36,C5,INTERMEDIARY:PARTNER_NETWORK,businessRole,INTERMEDIARY,HIGH,RULE
37,C5,INTERMEDIARY:PARTNER_NETWORK,operatingModel,PARTNER_NETWORK,HIGH,RULE
38,C5,INTERMEDIARY:PARTNER_NETWORK,partnerModel,PARTNER_NETWORK,HIGH,RULE
39,C5,INTERMEDIARY:PARTNER_NETWORK,deliveryModel,DIGITAL,HIGH,RULE
40,C5,INTERMEDIARY:PARTNER_NETWORK,transactionModel,OTHER,LOW,UNKNOWN
41,C5,INTERMEDIARY:PARTNER_NETWORK,monetizationModel,SUBSCRIPTION,HIGH,RULE
42,C5,INTERMEDIARY:PARTNER_NETWORK,customerInteractionModel,OTHER,LOW,UNKNOWN
43,C5,INTERMEDIARY:PARTNER_NETWORK,dataDependency,MATERIAL,NaN,NaN
44,C5,INTERMEDIARY:PARTNER_NETWORK,physicalDependency,NONE,NaN,NaN

## 25. Candidate Recovery / Portfolio Relations

In [26]:
candidate_preparation = (await engine.prepare_candidate_portfolio(
    seed, plan_validation, max_concepts=MAX_CONCEPTS, initial_candidates=candidate_drafts)
    if RUN_STAGED_CORE and plan_validation else None)
candidates = candidate_preparation.candidates if candidate_preparation else []
candidate_reports = candidate_preparation.reports if candidate_preparation else []
display(show_candidate_recovery(candidate_preparation) if candidate_preparation else {'status': 'SKIPPED'})
candidate_pairwise = [engine.compare_candidates(candidates[i], candidates[j])
                      for i in range(len(candidates)) for j in range(i + 1, len(candidates))]
display(show_plan_diversity(candidate_pairwise))

{'summary':    candidateGenerated  candidateAcceptedInitially  candidateRegenerated  \
 0                   5                           5                     0

    candidateRecovered  reservePlansActivated  candidateRecoveryReplans  \
 0                   0                      0                         0

    finalCandidatePortfolio
 0                        5  ,
 'attempts':   candidateId  schemaValid  hardLockPreserved  semanticAnchorPreserved  \
 0          C1         True               True                     True
 1          C2         True               True                     True
 2          C3         True               True                     True
 3          C4         True               True                     True
 4          C5         True               True                     True

    planFidelity anchorDecision fidelityDecision  contentLanguageValid  \
 0          True           PASS             PASS                  True
 1          True           PASS             PASS                  True
 2          True           PASS             PASS                  True
 3          True           PASS          ADAPTED                  True
 4          True           PASS             PASS                  True

    accepted   outcome  semanticFidelityUsed  \
 0      True  ACCEPTED                  True
 1      True  ACCEPTED                  True
 2      True  ACCEPTED                  True
 3      True  ACCEPTED                  True
 4      True  ACCEPTED                  True

                            matchedIdentityComponents  \
 0  [AI 기반 자동화, CRM 통합 기능, 회의 기록 자동 정리, 이메일 내용 자동 분석]
 1      [자동화된 회의 및 이메일 정리, 사용자 친화적인 인터페이스, CRM 통합 기능]
 2              [고객 행동 분석, 맞춤형 제안 기능, 사용자 친화적인 인터페이스]
 3               [성과 데이터 자동 분석, 개선점 제안 기능, CRM 통합 관리]
 4             [AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능]

   missingIdentityComponents reasonCodes safeSummary
 0                        []          []       검사 통과
 1                        []          []       검사 통과
 2                        []          []       검사 통과
 3          [사용자 친화적인 인터페이스]          []       검사 통과
 4                        []          []       검사 통과  ,
 'finalCandidates':   candidateId lineageId parentCandidateId                             이름  \
 0          C1        L1              None  중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구
 1          C2        L2              None   중소기업 영업팀의 회의 및 이메일 관리 최적화 도구
 2          C3        L3              None       AI 기반 고객 맞춤형 영업 액션 제안 도구
 3          C4        L4              None             AI 기반 영업팀 성과 분석 도구
 4          C5        L5              None         AI 기반 영업팀 업무 효율성 향상 도구

                                          핵심 작동방식              family  \
 0    AI 알고리즘이 회의 및 이메일 내용을 자동으로 분석하고 CRM에 입력합니다.  SaaS 도구 · 파트너 네트워크
 1  AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.  SaaS 도구 · 파트너 네트워크
 2      AI 알고리즘이 고객 데이터를 분석하여 실시간으로 영업 액션을 제안합니다.       기타 역할 · 기타 운영
 3  AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.       거래 중개 · 기타 운영
 4  AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.    거래 중개 · 파트너 네트워크

                                           descriptor  \
 0  {'thesis': {'targetSegmentThesis': '별도 영업 운영 인...
 1  {'thesis': {'targetSegmentThesis': '별도 영업 운영 인...
 2  {'thesis': {'targetSegmentThesis': '별도 영업 운영 인...
 3  {'thesis': {'targetSegmentThesis': '별도 영업 운영 인...
 4  {'thesis': {'targetSegmentThesis': '별도 영업 운영 인...

                                        수익  \
 0  구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.
 1  구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.
 2  구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.
 3                     구독 모델(월별 또는 연별 요금제)
 4  구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.

                                                 운영
 0  클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
 1  클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
 2  클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
 3  클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
 4  클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.  }

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,C1,C2,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,SAAS_TOOL:PARTNER_NETWORK,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,C1,C3,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,OTHER:OTHER,"partnerModel, transactionModel, monetizationMo...","businessRole, operatingModel, deliveryModel, p...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,C1,C4,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,INTERMEDIARY:OTHER,"partnerModel, deliveryModel, transactionModel,...","businessRole, operatingModel, valueProposition...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,C1,C5,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,INTERMEDIARY:PARTNER_NETWORK,"operatingModel, partnerModel, deliveryModel, t...","businessRole, offerThesis, solutionThesis",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
4,C2,C3,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,OTHER:OTHER,"partnerModel, transactionModel, monetizationMo...","businessRole, operatingModel, deliveryModel, p...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
5,C2,C4,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,INTERMEDIARY:OTHER,"partnerModel, deliveryModel, transactionModel,...","businessRole, operatingModel, valueProposition...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,C2,C5,DISTINCT,SAAS_TOOL:PARTNER_NETWORK,INTERMEDIARY:PARTNER_NETWORK,"operatingModel, partnerModel, deliveryModel, t...","businessRole, valuePropositionThesis",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,C3,C4,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, partnerModel, transactionModel...","businessRole, deliveryModel, physicalDependenc...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
8,C3,C5,DISTINCT,OTHER:OTHER,INTERMEDIARY:PARTNER_NETWORK,"partnerModel, transactionModel, monetizationMo...","businessRole, operatingModel, deliveryModel, p...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,C4,C5,VARIANT,INTERMEDIARY:OTHER,INTERMEDIARY:PARTNER_NETWORK,"businessRole, partnerModel, deliveryModel, tra...","operatingModel, valuePropositionThesis, offerT...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...

## 26. Legal Fact Completeness + Business Design Completion + C1 Fact Pattern

In [27]:
prechecks = [engine.legal_precheck(item) for item in candidates] if RUN_STAGED_LEGAL else []
display(show_legal_precheck(prechecks))
legal_preparation = (await engine.prepare_legal_candidates(seed, candidates)
                     if RUN_STAGED_LEGAL and candidates else None)
candidates_before_legal = candidates
candidates = legal_preparation.candidates if legal_preparation else candidates
display({'factCompleteness': [item.model_dump(mode='json') for item in legal_preparation.reports]
                              if legal_preparation else [],
         'roleSemanticBatchCalls': legal_preparation.roleSemanticBatchCalls if legal_preparation else 0,
         'dependencySemanticBatchCalls': legal_preparation.dependencySemanticBatchCalls if legal_preparation else 0,
         'completionAttempted': legal_preparation.completionAttempted if legal_preparation else 0,
         'completionValidated': legal_preparation.completionValidated if legal_preparation else 0,
         'completionAccepted': legal_preparation.completionAccepted if legal_preparation else 0,
         'completionExhausted': legal_preparation.completionExhausted if legal_preparation else 0,
         'completionCompliance': [item.model_dump(mode='json') for item in legal_preparation.completionCompliance] if legal_preparation else [],
         'factConsistency': [item.model_dump(mode='json') for item in legal_preparation.consistencyReports] if legal_preparation else [],
         'consistencyRepairAttempted': legal_preparation.consistencyRepairAttempted if legal_preparation else 0,
         'consistencyRepairAccepted': legal_preparation.consistencyRepairAccepted if legal_preparation else 0,
         'consistencyRepairExhausted': legal_preparation.consistencyRepairExhausted if legal_preparation else 0,
         'preLegalExclusions': legal_preparation.excludedCandidates if legal_preparation else []})
display(show_legal_fact_pattern(candidates[0].candidate, seed) if candidates else [])

,candidateId,label,directSeller,intermediary,regulatedPhysicalActivity,personalDataDependency,qualificationDependency,riskHints
0,C1,Structural risk precheck — not final legal review,True,False,False,True,False,[개인정보]
1,C2,Structural risk precheck — not final legal review,True,False,False,True,False,[개인정보]
2,C3,Structural risk precheck — not final legal review,True,False,True,True,False,"[물리 활동, 개인정보]"
3,C4,Structural risk precheck — not final legal review,True,True,False,True,False,[개인정보]
4,C5,Structural risk precheck — not final legal review,True,True,False,True,False,[개인정보]

{'factCompleteness': [{'candidateId': 'C1',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticDecision': 'NOT_REQUIRED',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': 'P2P 판매자·구매자 같은 거래 참가자를 별도 계약·운영 파트너로 자동 간주하지 않음.',
     'consistencyStatus': 'POTENTIAL_CONFLICT'}],
   'structuredCompletionRequirements': [],
   'architectureRoleConsistency': {'status': 'NOT_ENOUGH_EVIDENCE',
    'businessRole': 'SAAS_TOOL',
    'confidence': 'HIGH',
    'safeReason': '진단용 architecture confidence 또는 역할 근거가 충분하지 않습니다.'},
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C2',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [],
   'architectureRoleConsistency': {'status': 'NOT_ENOUGH_EVIDENCE',
    'businessRole': 'SAAS_TOOL',
    'confidence': 'HIGH',
    'safeReason': '진단용 architecture confidence 또는 역할 근거가 충분하지 않습니다.'},
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C4',
   'status': 'COMPLETABLE',
   'missingDesignFacts': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'contradictions': [],
   'completionRequirements': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'affectedFields': ['platformRole'],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MISMATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MISMATCH',
     'finalStatus': 'MISMATCH',
     'safeReason': '다른 역할의 설명이 들어 있어 해당 역할을 다시 명시해야 합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [{'field': 'platformRole',
     'reasonType': 'ROLE_MISMATCH',
     'dependencyType': None,
     'instruction': 'platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'}],
   'architectureRoleConsistency': {'status': 'NOT_ENOUGH_EVIDENCE',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'MEDIUM',
    'safeReason': '진단용 architecture confidence 또는 역할 근거가 충분하지 않습니다.'},
   'safeSummary': '동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.'},
  {'candidateId': 'C5',
   'status': 'COMPLETABLE',
   'missingDesignFacts': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'contradictions': [],
   'completionRequirements': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'affectedFields': ['platformRole'],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MISMATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MISMATCH',
     'finalStatus': 'MISMATCH',
     'safeReason': '다른 역할의 설명이 들어 있어 해당 역할을 다시 명시해야 합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [{'field': 'platformRole',
     'reasonType': 'ROLE_MISMATCH',
     'dependencyType': None,
     'instruction': 'platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'}],
   'architectureRoleConsistency': {'status': 'NOT_ENOUGH_EVIDENCE',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'MEDIUM',
    'safeReason': '진단용 architecture confidence 또는 역할 근거가 충분하지 않습니다.'},
   'safeSummary': '동일 Concept 안에서 누락된 사업 사실을 한 번 보완할 수 있습니다.'},
  {'candidateId': 'C4-F1',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C5-F1',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'roleSemantics': [{'field': 'platformRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'AMBIGUOUS',
     'semanticUsed': True,
     'semanticStatus': 'MATCH',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'providerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'sellerRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'},
    {'field': 'intermediaryRole',
     'status': 'MATCH',
     'presence': 'PRESENT',
     'deterministicStatus': 'MATCH',
     'semanticUsed': False,
     'semanticStatus': 'NOT_RUN',
     'finalStatus': 'MATCH',
     'safeReason': '역할 의미가 필드와 일치합니다.'}],
   'dependencyAssessments': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'structuredCompletionRequirements': [],
   'architectureRoleConsistency': {'status': 'CONSISTENT',
    'businessRole': 'INTERMEDIARY',
    'confidence': 'HIGH',
    'safeReason': '고신뢰 architecture와 Candidate의 중개 역할이 일치합니다.'},
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'}],
 'roleSemanticBatchCalls': 2,
 'dependencySemanticBatchCalls': 1,
 'completionAttempted': 2,
 'completionValidated': 2,
 'completionAccepted': 0,
 'completionExhausted': 3,
 'completionCompliance': [{'candidateId': 'C4-F1',
   'status': 'FAIL',
   'satisfiedRequirements': [],
   'unsatisfiedRequirements': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'changedFields': [],
   'unchangedRequiredFields': ['platformRole'],
   'safeSummary': 'Completion Provider가 요청된 사업 사실을 실제로 보완하지 않았습니다.'},
  {'candidateId': 'C5-F1',
   'status': 'FAIL',
   'satisfiedRequirements': [],
   'unsatisfiedRequirements': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
   'changedFields': [],
   'unchangedRequiredFields': ['platformRole'],
   'safeSummary': 'Completion Provider가 요청된 사업 사실을 실제로 보완하지 않았습니다.'}],
 'factConsistency': [{'candidateId': 'C1',
   'status': 'CONSISTENT',
   'issues': [],
   'safeSummary': '검사 대상 사업 사실 사이에 명백한 모순이 없습니다.'},
  {'candidateId': 'C2',
   'status': 'CONSISTENT',
   'issues': [],
   'safeSummary': '검사 대상 사업 사실 사이에 명백한 모순이 없습니다.'},
  {'candidateId': 'C3',
   'status': 'INVALID_FACT',
   'issues': [{'field': 'physicalActivities',
     'relation': 'SERVICE_PHYSICAL',
     'status': 'INVALID_FACT',
     'safeReason': '순수 디지털 서비스 구조와 배송·방문·설치 등 물리 활동이 동시에 명시되었습니다.',
     'repairInstruction': '서비스 방식에 맞게 physicalActivities의 잘못된 물리 활동만 정정합니다.'},
    {'field': 'intermediaryRole',
     'relation': 'TRANSACTION_INTERMEDIARY',
     'status': 'INVALID_FACT',
     'safeReason': '중개 역할 필드에 파트너 협력 설명만 있고 거래 연결 책임이 없습니다.',
     'repairInstruction': '실제 거래 방식에 맞춰 intermediaryRole의 중개 존재·부재만 정정합니다.'}],
   'safeSummary': 'Legal 전에 정정해야 할 명백한 사업 사실 자기모순이 있습니다.'},
  {'candidateId': 'C4',
   'status': 'CONSISTENT',
   'issues': [],
   'safeSummary': '검사 대상 사업 사실 사이에 명백한 모순이 없습니다.'},
  {'candidateId': 'C5',
   'status': 'CONSISTENT',
   'issues': [],
   'safeSummary': '검사 대상 사업 사실 사이에 명백한 모순이 없습니다.'}],
 'consistencyRepairAttempted': 1,
 'consistencyRepairAccepted': 0,
 'consistencyRepairExhausted': 1,
 'preLegalExclusions': [{'candidateId': 'C3',
   'scope': 'PRE_LEGAL_EXCLUSION',
   'reasonCode': 'CONCEPT_FACT_CONSISTENCY_REPAIR_FAILED',
   'affectedFields': ['physicalActivities', 'intermediaryRole'],
   'consistencyReport': {'candidateId': 'C3',
    'status': 'INVALID_FACT',
    'issues': [{'field': 'physicalActivities',
      'relation': 'SERVICE_PHYSICAL',
      'status': 'INVALID_FACT',
      'safeReason': '순수 디지털 서비스 구조와 배송·방문·설치 등 물리 활동이 동시에 명시되었습니다.',
      'repairInstruction': '서비스 방식에 맞게 physicalActivities의 잘못된 물리 활동만 정정합니다.'},
     {'field': 'intermediaryRole',
      'relation': 'TRANSACTION_INTERMEDIARY',
      'status': 'INVALID_FACT',
      'safeReason': '중개 역할 필드에 파트너 협력 설명만 있고 거래 연결 책임이 없습니다.',
      'repairInstruction': '실제 거래 방식에 맞춰 intermediaryRole의 중개 존재·부재만 정정합니다.'}],
    'safeSummary': 'Legal 전에 정정해야 할 명백한 사업 사실 자기모순이 있습니다.'},
   'recoveryAttempted': True,
   'recoveryResolution': 'PERMANENT_EXECUTION_FAILURE',
   'safeSummary': '사업정보 정합성 targeted patch 응답을 적용할 수 없습니다.'},
  {'candidateId': 'C4-F1',
   'scope': 'PRE_LEGAL_EXCLUSION',
   'reasonCode': 'LEGAL_FACT_COMPLETION_PROVIDER_NONCOMPLIANT',
   'affectedFields': [],
   'dependencyDecisions': [{'candidateId': None,
     'dependencyType': 'PERSONAL_DATA',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '개인 단위 정보의 처리 항목 또는 목적이 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'PHYSICAL_ACTIVITY',
     'deterministicDecision': 'NOT_REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'NOT_REQUIRED',
     'safeReason': '확인된 이행은 순수 디지털이며 물리 활동 신호가 없습니다.',
     'consistencyStatus': 'CONSISTENT'},
    {'candidateId': None,
     'dependencyType': 'BUSINESS_PARTNER',
     'deterministicDecision': 'REQUIRED',
     'semanticUsed': False,
     'semanticDecision': 'NOT_RUN',
     'finalDecision': 'REQUIRED',
     'safeReason': '사업 이행에 필요한 외부 계약·운영 파트너가 명시되었습니다.',
     'consistencyStatus': 'CONSISTENT'}],
   'completionRequirements': [{'field': 'platformRole',
     'reasonType': 'ROLE_MISMATCH',
     'dependencyType': None,
     'instruction': 'platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'}],
   'patchChangedFields': ['platformRole'],
   'completionCompliance': {'candidateId': 'C4-F1',
    'status': 'FAIL',
    'satisfiedRequirements': [],
    'unsatisfiedRequirements': ['platformRole의 역할 존재·부재와 해당 책임을 의미에 맞게 명시해야 합니다.'],
    'changedFields': [],
    'unchangedRequiredFields': ['platformRole'],
    'safeSummary': 'Completion Provider가 요청된 사업 사실을 실제로 보완하지 않았습니다.'},

,field,legalFact,source,authority,decision
0,platformRole,클라우드 기반 SaaS 플랫폼 제공,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
1,providerRole,AI 솔루션 제공업체,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
2,sellerRole,서비스 판매자,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
3,intermediaryRole,CRM 솔루션 제공업체,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
4,transactionFlow,"[사용자가 회의 기록과 이메일을 업로드한다., AI가 내용을 분석하여 CRM에 입력...",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
5,paymentFlow,"[사용자가 구독료를 결제한다., AI 솔루션 제공업체가 수익을 수취한다.]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
6,personalDataUsage,[고객의 회의 및 이메일 내용을 분석하여 CRM에 입력하는 데 사용됩니다.],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
7,physicalActivities,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
8,partnerRequirements,[CRM 솔루션 제공업체와의 기술적 통합이 필요합니다.],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
9,qualificationRequirements,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
10,advertisingClaims,"[AI 기반 자동화로 영업팀의 업무 효율성을 높입니다., CRM 통합으로 고객 대응...",CONCEPT_GENERATED,REVIEWABLE,PROPOSED

## 27. Prepared Legal C1 Evidence Summary

In [28]:
legal_adapter = CurrentLegalAdapter() if RUN_STAGED_LEGAL else None
legal_c1_input = (legal_adapter.task_input(candidates[0].candidate, seed)
                  if legal_adapter and candidates else None)
display({'candidateId': candidates[0].candidateId if candidates else None,
         'externalFacts': legal_c1_input['externalFactContext']['facts'] if legal_c1_input else [],
         'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'})

{'candidateId': 'C1',
 'externalFacts': [],
 'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'}

## 28. Full Evidence Judgment — C1 Staged Smoke

In [29]:
RUN_FULL_LEGAL_C1 = RUN_STAGED_LEGAL
legal_one = None
if RUN_FULL_LEGAL_C1 and candidates:
    try:
        legal_one = (await engine.review_legal(seed, candidates[:1]))[0]
        display(show_legal_result([legal_one]))
    except Exception:
        display(show_legal_failure(candidates[0].candidateId, engine.gateway))
else:
    print('SKIPPED — RUN_FULL_LEGAL_C1=True로 명시해야 실행됩니다.')

,candidateId,route,productionStatus,sourceStatus,evidenceCoverage,reviewPhase,factCompletenessStatus,legalSourceStatus,finalEvidenceJudgmentExecuted,recoveryResolution,...,legalClarificationCount,safeSummary,unknownFacts,requiredControls,requiredPartnersAndQualifications,requiredDisclosures,prohibitedVariants,evidenceCount,evidenceRefs,evidenceDiagnostics
0,C1,ACCEPT,IMPLEMENTABLE_WITH_CONTROLS,SOURCE_PARTIAL,"공식 근거를 바탕으로 구현 가능성을 검토했으나, 일부 법률 소스의 조회 범위에는 제...",LEGAL_SOURCE,None,SOURCE_PARTIAL,True,None,...,0,"AI 기반 자동화 및 CRM 통합 서비스 제공이 법적으로 가능하며, 고영향 인공지능...",[],"[고영향 인공지능에 해당하는지 사전에 검토해야 한다., 고영향 인공지능의 안전성 및...",[CRM 솔루션 제공업체와의 기술적 통합이 필요합니다.],[서비스 이용약관 및 개인정보 처리방침을 명확히 고지해야 한다.],[],10,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...","{'coverageStatus': 'SOURCE_PARTIAL', 'coverage..."

## 29. C1 Route + Staged Redesign/Compliance/Second Legal

In [30]:
c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = ([], [], [], 0, 0)
if legal_one and candidates:
    c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[:1], [legal_one])
display({'initialRoute': legal_one.route.value if legal_one else 'SKIPPED',
         'redesignRequirements': legal_one.redesignRequirements if legal_one else [],
         'recoveryReviews': [item.model_dump(mode='json') for item in c1_legal_all[1:]],
         'requiredInputs': c1_required_inputs, 'terminalCandidates': len(c1_portfolio),
         'redesigned': c1_redesigned, 'replanned': c1_replanned})

{'initialRoute': 'ACCEPT',
 'redesignRequirements': [],
 'recoveryReviews': [],
 'requiredInputs': [],
 'terminalCandidates': 1,
 'redesigned': 0,
 'replanned': 0}

## 30. Remaining 4 Legal + Exhaustive Recovery Summary

In [31]:
RUN_REMAINING_LEGAL = RUN_STAGED_FULL
legal_remaining = []
portfolio, legal_all, required_inputs = (list(c1_portfolio), list(c1_legal_all), list(c1_required_inputs))
redesigned_count, replanned_count = c1_redesigned, c1_replanned
c1_terminal = bool(c1_portfolio or c1_required_inputs or (c1_legal_all and c1_legal_all[-1].route.value == 'SYSTEM_FAILURE'))
if RUN_REMAINING_LEGAL and c1_terminal and len(candidates) > 1:
    legal_remaining = await engine.review_legal(seed, candidates[1:])
    rest_portfolio, rest_legal, rest_inputs, rest_redesigned, rest_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[1:], legal_remaining)
    portfolio += rest_portfolio; legal_all += rest_legal; required_inputs += rest_inputs
    redesigned_count += rest_redesigned; replanned_count += rest_replanned
else:
    print('SKIPPED — C1이 정상 terminal에 도달한 후 remaining Legal을 실행합니다.')
legal_initial = ([legal_one] if legal_one else []) + legal_remaining
display({'recoveryTrace': [item.model_dump(mode='json') for item in legal_all
                           if item.candidateId not in {x.candidateId for x in legal_initial}],
         'requiredInputs': required_inputs, 'metrics': engine._legal_metrics})
print({'Plan Selected': len(selected_plans),
       'Candidate Generated': candidate_preparation.candidateGenerated if candidate_preparation else 0,
       'Candidate Valid Initially': candidate_preparation.candidateAcceptedInitially if candidate_preparation else 0,
       'Candidate Regenerated': candidate_preparation.candidateRegenerated if candidate_preparation else 0,
       'Candidate Recovered': candidate_preparation.candidateRecovered if candidate_preparation else 0,
       'Fact Completion Attempted': legal_preparation.completionAttempted if legal_preparation else 0,
       'Fact Completion Validated': legal_preparation.completionValidated if legal_preparation else 0,
       'Fact Completion Accepted': legal_preparation.completionAccepted if legal_preparation else 0,
       'Dependency Semantic Calls': legal_preparation.dependencySemanticBatchCalls if legal_preparation else 0,
       'Completion Compliance PASS': sum(item.status == 'PASS' for item in legal_preparation.completionCompliance) if legal_preparation else 0,
       'Fact Consistency Invalid': sum(item.status == 'INVALID_FACT' for item in legal_preparation.consistencyReports) if legal_preparation else 0,
       'Consistency Repair Accepted': legal_preparation.consistencyRepairAccepted if legal_preparation else 0,
       'Legal Ready': len(candidates) if legal_preparation else 0,
       'Legal Reviewed': len(legal_initial),
       'Legal Accepted': sum(item.route.value == 'ACCEPT' for item in legal_all),
       'Legal Redesigned': redesigned_count, 'Legal Replanned': replanned_count,
       'Final Portfolio': len(portfolio)})

{'recoveryTrace': [],
 'requiredInputs': [],
 'metrics': {'factAttempted': 2,
  'factValidated': 2,
  'factAccepted': 0,
  'factExhausted': 3,
  'dependencySemanticCalls': 1,
  'completionCompliancePassed': 0,
  'providerNoncompliant': 2,
  'recheckFailed': 0,
  'consistencyInvalid': 1,
  'consistencyRepairAttempted': 1,
  'consistencyRepairAccepted': 0,
  'consistencyRepairExhausted': 1,
  'redesignAttempted': 0,
  'redesignValidated': 0,
  'redesignAccepted': 0,
  'redesignExhausted': 0,
  'replanAttempted': 0,
  'replanValidated': 0,
  'replanAccepted': 0,
  'replanExhausted': 0}}

{'Plan Selected': 5, 'Candidate Generated': 5, 'Candidate Valid Initially': 5, 'Candidate Regenerated': 0, 'Candidate Recovered': 0, 'Fact Completion Attempted': 2, 'Fact Completion Validated': 2, 'Fact Completion Accepted': 0, 'Dependency Semantic Calls': 1, 'Completion Compliance PASS': 0, 'Fact Consistency Invalid': 1, 'Consistency Repair Accepted': 0, 'Legal Ready': 2, 'Legal Reviewed': 2, 'Legal Accepted': 2, 'Legal Redesigned': 0, 'Legal Replanned': 0, 'Final Portfolio': 2}

## 31. Replan

In [32]:
display(show_replan(type('PortfolioView', (), {'concepts': portfolio})()))
print({'replanned': replanned_count, 'reserveAvailable': len(reserve_plans)})

Empty DataFrame
Columns: []
Index: []

{'replanned': 0, 'reserveAvailable': 2}

## 32. Final Portfolio

In [33]:
legal_terminal_status = ('READY_FULL' if len(portfolio) == MAX_CONCEPTS else
    'READY_LIMITED' if portfolio else
    'LEGAL_RECOVERY_COMPLETE_NO_ACCEPTED_CANDIDATE' if legal_initial and len(legal_initial) == len(candidates)
    else 'LEGAL_PENDING')
display(show_final_portfolio(type('PortfolioView', (), {'concepts': portfolio})()) if portfolio else {'status': legal_terminal_status})

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구,AI 알고리즘이 회의 및 이메일 내용을 자동으로 분석하고 CRM에 입력합니다.,SaaS 도구 · 파트너 네트워크,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.
1,C2,L2,None,중소기업 영업팀의 회의 및 이메일 관리 최적화 도구,AI 알고리즘이 자동으로 데이터를 처리하여 고객에게 실시간으로 결과를 제공합니다.,SaaS 도구 · 파트너 네트워크,{'thesis': {'targetSegmentThesis': '별도 영업 운영 인...,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.

## 33. Unresolved Candidate Summary

In [34]:
display(show_required_inputs(required_inputs) if required_inputs else {'unresolved': []})

{'unresolved': []}

## 34. Manual Concept Selection

In [35]:
SELECTED_CANDIDATE_ID = portfolio[0].candidateId if portfolio else None  # 사용자가 수정
selected_concept = next((item for item in portfolio if item.candidateId == SELECTED_CANDIDATE_ID), None)
print({'selectedCandidateId': SELECTED_CANDIDATE_ID})

{'selectedCandidateId': 'C1'}

## 35. 7 Hypotheses

In [36]:
hypotheses = (engine.build_or_load_current_hypothesis_contract(selected_concept)
              if RUN_STAGED_FULL and selected_concept else [])
hypotheses = await engine.resolve_hypothesis_semantics(hypotheses) if hypotheses else []
display(show_hypotheses(hypotheses))
display(show_hypothesis_readiness(hypotheses))

,HypothesisType,ProposedValue,FinalValue,SemanticStatus,SemanticReason,Locked,DecisionStatus,LegalImpact
0,TARGET_REGION,대한민국,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
1,REVENUE_MODEL,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
2,PRICE,월 10만원 또는 연 100만원,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
3,CHANNELS,온라인 마케팅 및 CRM 솔루션 제공업체와의 파트너십을 통한 유통,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
4,DIFFERENTIATORS,"AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능",None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
5,PRE_MARKET_SOM_SHARE,targetSharePercent=15.0 horizonYears=3 rationa...,None,VALID,수치·기간·산식 가설이 명시되었습니다.,False,PROPOSED,NONE
6,PRE_MARKET_SOM,amount=50000000.0 currency='KRW' period='1년' c...,None,VALID,수치·기간·산식 가설이 명시되었습니다.,False,PROPOSED,NONE

{'All Values Semantically Valid': True,
 'All Decisions Confirmed': False,
 'Ready For Handoff': False,
 'status': 'NOT_READY',
 'reason': 'UNRESOLVED_HYPOTHESES',
 'unresolvedHypotheses': ['TARGET_REGION',
  'REVENUE_MODEL',
  'PRICE',
  'CHANNELS',
  'DIFFERENTIATORS',
  'PRE_MARKET_SOM_SHARE',
  'PRE_MARKET_SOM']}

## 36. Confirm / Edit

In [37]:
CONFIRM_ALL_PROPOSED = True
HYPOTHESIS_EDITS = {
    # 'PRICE': '월 17,900원',
}
confirmed_hypotheses = engine.confirm_hypotheses(
    hypotheses, HYPOTHESIS_EDITS, confirm_all_proposed=CONFIRM_ALL_PROPOSED) if hypotheses else []
display(show_hypotheses(confirmed_hypotheses))
hypothesis_readiness = show_hypothesis_readiness(confirmed_hypotheses)
display(hypothesis_readiness)

,HypothesisType,ProposedValue,FinalValue,SemanticStatus,SemanticReason,Locked,DecisionStatus,LegalImpact
0,TARGET_REGION,대한민국,대한민국,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
1,REVENUE_MODEL,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
2,PRICE,월 10만원 또는 연 100만원,월 10만원 또는 연 100만원,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
3,CHANNELS,온라인 마케팅 및 CRM 솔루션 제공업체와의 파트너십을 통한 유통,온라인 마케팅 및 CRM 솔루션 제공업체와의 파트너십을 통한 유통,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
4,DIFFERENTIATORS,"AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능","AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능",VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
5,PRE_MARKET_SOM_SHARE,targetSharePercent=15.0 horizonYears=3 rationa...,targetSharePercent=15.0 horizonYears=3 rationa...,VALID,수치·기간·산식 가설이 명시되었습니다.,False,ACCEPTED,NONE
6,PRE_MARKET_SOM,amount=50000000.0 currency='KRW' period='1년' c...,amount=50000000.0 currency='KRW' period='1년' c...,VALID,수치·기간·산식 가설이 명시되었습니다.,False,ACCEPTED,NONE

{'All Values Semantically Valid': True,
 'All Decisions Confirmed': True,
 'Ready For Handoff': True,
 'status': 'READY',
 'reason': None,
 'unresolvedHypotheses': []}

## 37. Actual Delta Legal

In [38]:
RUN_DELTA_LEGAL = True
delta_legal_result = None
if RUN_STAGED_FULL and RUN_DELTA_LEGAL and selected_concept and any(h.deltaLegalRequired for h in confirmed_hypotheses):
    delta_legal_result = await engine.review_delta_legal(seed, selected_concept, confirmed_hypotheses)
    confirmed_hypotheses = engine.mark_delta_legal_reviewed(confirmed_hypotheses, delta_legal_result)
display(delta_legal_result.model_dump(mode='json') if delta_legal_result else {'status': 'NOT_REQUIRED_OR_SKIPPED'})

{'status': 'NOT_REQUIRED_OR_SKIPPED'}

## 38. Market Seed

In [39]:
handoff = None
if selected_concept and legal_all and hypothesis_readiness['Ready For Handoff']:
    handoff = engine.build_downstream_handoff(seed, selected_concept, confirmed_hypotheses, legal_all)
display(handoff.marketAnalysisSeedSnapshot if handoff else {
    'status': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'contract': 'market-analysis-seed-snapshot-v1',
 'schemaVersion': '2.0',
 'snapshotId': 'lab-market-seed',
 'projectId': 0,
 'selectionId': 0,
 'conceptId': 'C1',
 'createdAt': '2026-08-10T08:48:03.272905+00:00',
 'sourceSnapshotHash': 'sha256:6717e04a7f68fe3097441aa4506ba39be19ac05e1879555177e24f135909dced',
 'originalSeed': {'ideaOverview': '중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구',
  'fields': {'ideaOverview': {'value': '중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'},
   'problem': {'value': '영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어든다.',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'},
   'targetUsers': {'value': '별도 영업 운영 인력이 부족한 중소기업 영업팀',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'}}},
 'aiInterpretation': {'interpretedProblem': '영업 담당자가 회의 및 이메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어드는 문제를 해결합니다.',
  'interpretedTargetUsers': '별도의 영업 운영 인력이 부족한 중소기업 영업팀을 대상으로 합니다.',
  'usageContext': '중소기업의 영업팀에서 회의 기록과 이메일을 효율적으로 관리하고 CRM에 입력하는 데 사용됩니다.',
  'industryCategory': '소프트웨어/AI 도구',
  'researchScope': '중소기업의 영업 효율성 향상에 관한 연구',
  'conciseIdeaDefinition': 'AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치 및 고객별 영업 액션을 제안하는 도구입니다.',
  'targetRegionInterpretation': '',
  'relevantKnownCompetitorContext': ''},
 'selectedConcept': {'identity': {'conceptName': '중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구',
   'conceptDefinition': 'AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치 및 고객별 영업 액션을 제안하는 도구입니다.',
   'introduction': '중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구입니다.',
   'coreValue': 'AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.',
   'targetUsers': '별도 영업 운영 인력이 부족한 중소기업 영업팀',
   'industryCategory': '소프트웨어/AI 도구',
   'researchScope': '중소기업의 영업 효율성 향상에 관한 연구'},
  'solution': {'problemScenario': '영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어든다.',
   'solutionMechanism': 'AI 알고리즘이 회의 및 이메일 내용을 자동으로 분석하고 CRM에 입력합니다.',
   'featureSet': ['회의 기록 자동 정리', '이메일 내용 자동 분석', 'CRM 통합 기능']},
  'operation': {'actorRoles': ['영업팀', 'CRM 제공업체', 'AI 시스템'],
   'platformRole': '클라우드 기반 SaaS 플랫폼 제공',
   'operatingModel': '클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.',
   'partnerModel': 'CRM 솔루션 제공업체와의 파트너십을 통해 통합 서비스를 제공합니다.',
   'providerRole': 'AI 솔루션 제공업체',
   'sellerRole': '서비스 판매자',
   'intermediaryRole': 'CRM 솔루션 제공업체',
   'transactionFlow': ['사용자가 회의 기록과 이메일을 업로드한다.',
    'AI가 내용을 분석하여 CRM에 입력한다.',
    '사용자가 결과를 확인한다.'],
   'paymentFlow': ['사용자가 구독료를 결제한다.', 'AI 솔루션 제공업체가 수익을 수취한다.'],
   'personalDataUsage': ['고객의 회의 및 이메일 내용을 분석하여 CRM에 입력하는 데 사용됩니다.'],
   'physicalActivities': [],
   'partnerRequirements': ['CRM 솔루션 제공업체와의 기술적 통합이 필요합니다.'],
   'qualificationRequirements': []},
  'valueSemantics': [{'fieldKey': 'conceptName',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'conceptDefinition',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'introduction',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'coreValue',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'targetUsers',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'industryCategory',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'researchScope',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'targetRegion',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'revenueModel',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'price',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'channels',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'differentiators',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'preMarketSomShareHypothesis',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'preMarketSomHypothesis',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'actorRoles',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'platformRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'problemScenario',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'solutionMechanism',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'featureSet',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'operatingModel',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'partnerModel',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'providerRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'sellerRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'intermediaryRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'transactionFlow',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'paymentFlow',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'personalDataUsage',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'physicalActivities',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'partnerRequirements',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'qualificationRequirements',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'advertisingClaims',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'}],
  'canonicalHash': 'sha256:677484c43beefacf17581aa35bfc5f63e6ca96c68c4818baa41be17095c702b5'},
 'finalHypotheses': {'targetRegion': {'value': '대한민국',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'revenueModel': {'value': '구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'price': {'value': '월 10만원 또는 연 100만원',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'channels': {'value': '온라인 마케팅 및 CRM 솔루션 제공업체와의 파트너십을 통한 유통',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'differentiators': {'value': 'AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'preMarketSomShare': {'value': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='중소기업 시장의 CRM 자동화 수요 증가에 따른 점유율 목표.', assumptions=['중소기업의 CRM 도입률 증가', 'AI 기술에 대한 신뢰도 향상']),
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'preMarketSom': {'value': PreMarketSomHypothesis(amount=50000000.0, currency='KRW', period='1년', calculationBasis='중소기업 영업팀의 수와 평균 구독료를 기반으로 한 추정치.', assumptions=['중소기업의 평균 영업팀 규모는 5명', '연간 1000개의 중소기업이 신규 도입할 것으로 예상'], confidence='MEDIUM'),
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'}},
 'legalResult': {'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
  'safeSummary': 'AI 기반 자동화 및 CRM 통합 서비스 제공이 법적으로 가능하며, 고영향 인공지능 관련 법령 준수 및 소비자 보호를 위한 통제조건이 필요합니다.',
  'requiredControls': ['고영향 인공지능에 해당하는지 사전에 검토해야 한다.',
   '고영향 인공지능의 안전성 및 신뢰성을 확보하기 위한 조치를 이행해야 한다.',
   '고영향 인공지능을 이용한 제품 또는 서비스의 영향을 평가해야 한다.',
   '정보통신서비스 제공자는 이용자를 보호하고 안전한 서비스를 제공해야 한다.',
   '정보통신망 이용촉진 및 정보보호 시책을 마련해야 한다.',
   '사업자는 소비자를 속이거나 잘못 알게 할 우려가 있는 광고를 해서는 안 된다.',
   '사업자는 광고 내용에 대해 실증할 수 있어야 한다.'],
  'requiredPartnersAndQualifications': ['CRM 솔루션 제공업체와의 기술적 통합이 필요합니다.'],
  'prohibitedVariants': [],
  'requiredDisclosures': ['서비스 이용약관 및 개인정보 처리방침을 명확히 고지해야 한다.'],
  'officialEvidenceReferences': [{'referenceIndex': 0,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '014820',
    'officialIdentifier': '282791',
    'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
    'articleReference': '제3조',
    'title': '기본원칙 및 국가 등의 책무',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:d3af532ea737d1273289ec05ed2ff55c735bccac16c517b64292d7beeccd5312',
    'boundedProvisionSummary': '인공지능기술과 인공지능산업은 안전성과 신뢰성을 제고하여 국민의 삶의 질을 향상시키는 방향으로 발전되어야 한다.',
    'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 1,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '014820',
    'officialIdentifier': '282791',
    'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
    'articleReference': '제33조',
    'title': '고영향 인공지능의 확인',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:3fc48c2346668bf69d17684a6ea9e0adf2b1e2deb1409e8094281cbeefa8b48d',
    'boundedProvisionSummary': '인공지능사업자는 고영향 인공지능에 해당하는지 사전에 검토해야 한다.',
    'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 2,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '014820',
    'officialIdentifier': '282791',
    'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
    'articleReference': '제34조',
    'title': '고영향 인공지능과 관련한 사업자의 책무',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:617313212eede73a9fa4de775860b754747632549637a3da96e8e1b7fc0677c4',
    'boundedProvisionSummary': '고영향 인공지능의 안전성 및 신뢰성을 확보하기 위한 조치를 이행해야 한다.',
    'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 3,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '014820',
    'officialIdentifier': '282791',
    'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
    'articleReference': '제35조',
    'title': '고영향 인공지능 영향평가',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:fb8ebf040c2029dd28b2bd73badb7e225880c1a211d422abac790f568fb5d8c5',
    'boundedProvisionSummary': '고영향 인공지능을 이용한 제품 또는 서비스의 영향을 평가해야 한다.',
    'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 4,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '000030',
    'officialIdentifier': '282481',
    'lawName': '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
    'articleReference': '제3조',
    'title': '정보통신서비스 제공자 및 이용자의 책무',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0%EB%A7%9D%20%EC%9D%B4%EC%9A%A9%EC%B4%89%EC%A7%84%20%EB%B0%8F%20%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260106',
    'effectiveDate': '20260707',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:0f8a92d020f0e4f81e3020f1fae1178b3a63b92768de88a28f48449d7d37dd83',
    'boundedProvisionSummary': '정보통신서비스 제공자는 이용자를 보호하고 안전한 서비스를 제공해야 한다.',
    'queryKey': 'sha256:7950518a36e66a586195226f8a68f7683de9c44930cbffec85bfe270ccd8cc59',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 5,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '000030',
    'officialIdentifier': '282481',
    'lawName': '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
    'articleReference': '제4조',
    'title': '정보통신망 이용촉진 및 정보보호등에 관한 시책의 마련',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0%EB%A7%9D%20%EC%9D%B4%EC%9A%A9%EC%B4%89%EC%A7%84%20%EB%B0%8F%20%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260106',
    'effectiveDate': '20260707',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:fa6d134f7eaa58efaed72e7d30f93e2d19c6edf8b92fb43c9f1ce70e616989e1',
    'boundedProvisionSummary': '정보통신망 이용촉진 및 정보보호 시책을 마련해야 한다.',
    'queryKey': 'sha256:7950518a36e66a586195226f8a68f7683de9c44930cbffec85bfe270ccd8cc59',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 6,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '002011',
    'officialIdentifier': '268659',
    'lawName': '표시ㆍ광고의 공정화에 관한 법률',
    'articleReference': '제3조',
    'title': '부당한 표시ㆍ광고 행위의 금지',
    'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250121',
    'effectiveDate': '20250121',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:8a232304b3941209cf6afb47ff8485dec72a80b22d8ea0bd5f72b07f583b5826',
    'boundedProvisionSummary': '사업자는 소비자를 속이거나 잘못 알게 할 우려가 있는 광고를 해서는 안 된다.',
    'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 7,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '002011',
    'officialIdentifier': '268659',
    'lawName': '표시ㆍ광고의 공정화에 관한 법률',
    'articleReference': '제5조',
    'title': '표시ㆍ광고 내용의 실증 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250121',
    'effectiveDate': '20250121',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:175e1d20e79b88964eddbcfa658507a8968209ddba38fe094bc7005015b0ba30',
    'boundedProvisionSummary': '사업자는 광고 내용에 대해 실증할 수 있어야 한다.',
    'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 8,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '002011',
    'officialIdentifier': '268659',
    'lawName': '표시ㆍ광고의 공정화에 관한 법률',
    'articleReference': '제10조',
    'title': '손해배상책임',
    'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250121',
    'effectiveDate': '20250121',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:9e32cfffe5aee496b1832d5e3707961c9f4280d83dc0f91deaf66f0318f1de73',
    'boundedProvisionSummary': '부당한 광고 행위로 피해를 입은 자에게 손해배상 책임을 진다.',
    'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 9,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '002011',
    'officialIdentifier': '268659',
    'lawName': '표시ㆍ광고의 공정화에 관한 법률',
    'articleReference': '제17조',
    'title': '벌칙',
    'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250121',
    'effectiveDate': '20250121',
    'retrievedAt': '2026-08-10T08:47:36.808707Z',
    'contentHash': 'sha256:f8efc781c87796884bf25f8d680b1efcd4e223f5e470a5b156122d6d82e15692',
    'boundedProvisionSummary': '부당한 광고 행위를 한 자에게 징역형 또는 벌금형에 처한다.',
    'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
    'registryVersion': 'legal-registry-v1'}],
  'deltaLegalReviews': []}}

## 39. Marketing Source

In [40]:
display(handoff.marketingSourceSnapshot if handoff else {
    'status': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'contract': 'marketing-source-snapshot-v1',
 'schemaVersion': '2.0',
 'snapshotId': 'lab-marketing-source',
 'projectId': 0,
 'selectionId': 0,
 'conceptId': 'C1',
 'marketAnalysisSeedSnapshotId': 'lab-market-seed',
 'marketAnalysisSeedSnapshotHash': 'sha256:441e70a038466b564bdaf9fc225545dd6941846e7374ff9c6d547a83ad58896a',
 'createdAt': '2026-08-10T08:48:03.272905+00:00',
 'conceptName': '중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구',
 'targetSegment': '별도 영업 운영 인력이 부족한 중소기업 영업팀',
 'problem': '영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어든다.',
 'valueProposition': 'AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.',
 'positioning': 'AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치 및 고객별 영업 액션을 제안하는 도구입니다.',
 'keyFeatures': ['회의 기록 자동 정리', '이메일 내용 자동 분석', 'CRM 통합 기능'],
 'targetRegion': '대한민국',
 'revenueModel': '구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.',
 'price': '월 10만원 또는 연 100만원',
 'pricing': '구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다. · 월 10만원 또는 연 100만원',
 'channels': ['온라인 마케팅 및 CRM 솔루션 제공업체와의 파트너십을 통한 유통'],
 'competitorDifferentiators': ['AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능'],
 'preMarketSomShare': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='중소기업 시장의 CRM 자동화 수요 증가에 따른 점유율 목표.', assumptions=['중소기업의 CRM 도입률 증가', 'AI 기술에 대한 신뢰도 향상']),
 'preMarketSom': PreMarketSomHypothesis(amount=50000000.0, currency='KRW', period='1년', calculationBasis='중소기업 영업팀의 수와 평균 구독료를 기반으로 한 추정치.', assumptions=['중소기업의 평균 영업팀 규모는 5명', '연간 1000개의 중소기업이 신규 도입할 것으로 예상'], confidence='MEDIUM'),
 'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
 'allowedClaims': ['AI 기반 자동화로 영업팀의 업무 효율성을 높입니다.',
  'CRM 통합으로 고객 대응 시간을 단축합니다.'],
 'prohibitedClaims': [],
 'requiredDisclosures': ['서비스 이용약관 및 개인정보 처리방침을 명확히 고지해야 한다.'],
 'requiredControls': ['고영향 인공지능에 해당하는지 사전에 검토해야 한다.',
  '고영향 인공지능의 안전성 및 신뢰성을 확보하기 위한 조치를 이행해야 한다.',
  '고영향 인공지능을 이용한 제품 또는 서비스의 영향을 평가해야 한다.',
  '정보통신서비스 제공자는 이용자를 보호하고 안전한 서비스를 제공해야 한다.',
  '정보통신망 이용촉진 및 정보보호 시책을 마련해야 한다.',
  '사업자는 소비자를 속이거나 잘못 알게 할 우려가 있는 광고를 해서는 안 된다.',
  '사업자는 광고 내용에 대해 실증할 수 있어야 한다.'],
 'communicationRequiredControls': ['고영향 인공지능에 해당하는지 사전에 검토해야 한다.',
  '고영향 인공지능의 안전성 및 신뢰성을 확보하기 위한 조치를 이행해야 한다.',
  '고영향 인공지능을 이용한 제품 또는 서비스의 영향을 평가해야 한다.',
  '정보통신서비스 제공자는 이용자를 보호하고 안전한 서비스를 제공해야 한다.',
  '정보통신망 이용촉진 및 정보보호 시책을 마련해야 한다.',
  '사업자는 소비자를 속이거나 잘못 알게 할 우려가 있는 광고를 해서는 안 된다.',
  '사업자는 광고 내용에 대해 실증할 수 있어야 한다.'],
 'officialEvidenceReferences': [{'referenceIndex': 0,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '014820',
   'officialIdentifier': '282791',
   'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
   'articleReference': '제3조',
   'title': '기본원칙 및 국가 등의 책무',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:d3af532ea737d1273289ec05ed2ff55c735bccac16c517b64292d7beeccd5312',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 1,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '014820',
   'officialIdentifier': '282791',
   'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
   'articleReference': '제33조',
   'title': '고영향 인공지능의 확인',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:3fc48c2346668bf69d17684a6ea9e0adf2b1e2deb1409e8094281cbeefa8b48d',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 2,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '014820',
   'officialIdentifier': '282791',
   'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
   'articleReference': '제34조',
   'title': '고영향 인공지능과 관련한 사업자의 책무',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:617313212eede73a9fa4de775860b754747632549637a3da96e8e1b7fc0677c4',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 3,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '014820',
   'officialIdentifier': '282791',
   'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
   'articleReference': '제35조',
   'title': '고영향 인공지능 영향평가',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:fb8ebf040c2029dd28b2bd73badb7e225880c1a211d422abac790f568fb5d8c5',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 4,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000030',
   'officialIdentifier': '282481',
   'lawName': '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
   'articleReference': '제3조',
   'title': '정보통신서비스 제공자 및 이용자의 책무',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0%EB%A7%9D%20%EC%9D%B4%EC%9A%A9%EC%B4%89%EC%A7%84%20%EB%B0%8F%20%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260106',
   'effectiveDate': '20260707',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:0f8a92d020f0e4f81e3020f1fae1178b3a63b92768de88a28f48449d7d37dd83',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 5,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000030',
   'officialIdentifier': '282481',
   'lawName': '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
   'articleReference': '제4조',
   'title': '정보통신망 이용촉진 및 정보보호등에 관한 시책의 마련',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0%EB%A7%9D%20%EC%9D%B4%EC%9A%A9%EC%B4%89%EC%A7%84%20%EB%B0%8F%20%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260106',
   'effectiveDate': '20260707',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:fa6d134f7eaa58efaed72e7d30f93e2d19c6edf8b92fb43c9f1ce70e616989e1',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 6,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제3조',
   'title': '부당한 표시ㆍ광고 행위의 금지',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:8a232304b3941209cf6afb47ff8485dec72a80b22d8ea0bd5f72b07f583b5826',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 7,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제5조',
   'title': '표시ㆍ광고 내용의 실증 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:175e1d20e79b88964eddbcfa658507a8968209ddba38fe094bc7005015b0ba30',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 8,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제10조',
   'title': '손해배상책임',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:9e32cfffe5aee496b1832d5e3707961c9f4280d83dc0f91deaf66f0318f1de73',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 9,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '002011',
   'officialIdentifier': '268659',
   'lawName': '표시ㆍ광고의 공정화에 관한 법률',
   'articleReference': '제17조',
   'title': '벌칙',
   'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250121',
   'effectiveDate': '20250121',
   'retrievedAt': '2026-08-10T08:47:36.808707Z',
   'contentHash': 'sha256:f8efc781c87796884bf25f8d680b1efcd4e223f5e470a5b156122d6d82e15692',
   'registryVersion': 'legal-registry-v1'}],
 'hash': 'sha256:5deba9b3da192c6925283cc6f992e1a16313a8aa52d447f568b615295c6ec583',
 'sourceSnapshotHash': 'sha256:5deba9b3da192c6925283cc6f992e1a16313a8aa52d447f568b615295c6ec583'}

## 40. Contract Compatibility

In [41]:
display(show_downstream_handoff(handoff) if handoff else {
    'contract': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'호환성': 'PASS',
 '구조': 'STRUCTURE_PASS',
 '계약': 'CONTRACT_PASS',
 '필드 매핑':                        v2Field                             downstreamField  \
 0        candidate.conceptName        selectedConcept.identity.conceptName
 1  candidate.solutionMechanism  selectedConcept.solution.solutionMechanism
 2                hypotheses[*]                             finalHypotheses
 3                        legal                                 legalResult

               source  transformed  required
 0  CONCEPT_GENERATED        False      True
 1  CONCEPT_GENERATED        False      True
 2     USER_CONFIRMED         True      True
 3  OFFICIAL_EVIDENCE         True      True  ,
 'Market payload': {'contract': 'market-analysis-seed-snapshot-v1',
  'schemaVersion': '2.0',
  'snapshotId': 'lab-market-seed',
  'projectId': 0,
  'selectionId': 0,
  'conceptId': 'C1',
  'createdAt': '2026-08-10T08:48:03.272905+00:00',
  'sourceSnapshotHash': 'sha256:6717e04a7f68fe3097441aa4506ba39be19ac05e1879555177e24f135909dced',
  'originalSeed': {'ideaOverview': '중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구',
   'fields': {'ideaOverview': {'value': '중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'},
    'problem': {'value': '영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어든다.',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'},
    'targetUsers': {'value': '별도 영업 운영 인력이 부족한 중소기업 영업팀',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'}}},
  'aiInterpretation': {'interpretedProblem': '영업 담당자가 회의 및 이메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어드는 문제를 해결합니다.',
   'interpretedTargetUsers': '별도의 영업 운영 인력이 부족한 중소기업 영업팀을 대상으로 합니다.',
   'usageContext': '중소기업의 영업팀에서 회의 기록과 이메일을 효율적으로 관리하고 CRM에 입력하는 데 사용됩니다.',
   'industryCategory': '소프트웨어/AI 도구',
   'researchScope': '중소기업의 영업 효율성 향상에 관한 연구',
   'conciseIdeaDefinition': 'AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치 및 고객별 영업 액션을 제안하는 도구입니다.',
   'targetRegionInterpretation': '',
   'relevantKnownCompetitorContext': ''},
  'selectedConcept': {'identity': {'conceptName': '중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구',
    'conceptDefinition': 'AI를 활용하여 중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치 및 고객별 영업 액션을 제안하는 도구입니다.',
    'introduction': '중소기업 영업팀의 회의 기록과 이메일을 정리하고 CRM에 입력할 후속 조치와 고객별 영업 액션을 제안하는 AI 업무 도구입니다.',
    'coreValue': 'AI를 통해 영업팀의 업무 부담을 줄이고 고객 대응 시간을 늘립니다.',
    'targetUsers': '별도 영업 운영 인력이 부족한 중소기업 영업팀',
    'industryCategory': '소프트웨어/AI 도구',
    'researchScope': '중소기업의 영업 효율성 향상에 관한 연구'},
   'solution': {'problemScenario': '영업 담당자가 회의·메일 내용을 수작업으로 정리하고 CRM을 업데이트하느라 실제 고객 대응 시간이 줄어든다.',
    'solutionMechanism': 'AI 알고리즘이 회의 및 이메일 내용을 자동으로 분석하고 CRM에 입력합니다.',
    'featureSet': ['회의 기록 자동 정리', '이메일 내용 자동 분석', 'CRM 통합 기능']},
   'operation': {'actorRoles': ['영업팀', 'CRM 제공업체', 'AI 시스템'],
    'platformRole': '클라우드 기반 SaaS 플랫폼 제공',
    'operatingModel': '클라우드 기반의 SaaS 모델로 제공되어 사용자가 언제 어디서나 접근할 수 있습니다.',
    'partnerModel': 'CRM 솔루션 제공업체와의 파트너십을 통해 통합 서비스를 제공합니다.',
    'providerRole': 'AI 솔루션 제공업체',
    'sellerRole': '서비스 판매자',
    'intermediaryRole': 'CRM 솔루션 제공업체',
    'transactionFlow': ['사용자가 회의 기록과 이메일을 업로드한다.',
     'AI가 내용을 분석하여 CRM에 입력한다.',
     '사용자가 결과를 확인한다.'],
    'paymentFlow': ['사용자가 구독료를 결제한다.', 'AI 솔루션 제공업체가 수익을 수취한다.'],
    'personalDataUsage': ['고객의 회의 및 이메일 내용을 분석하여 CRM에 입력하는 데 사용됩니다.'],
    'physicalActivities': [],
    'partnerRequirements': ['CRM 솔루션 제공업체와의 기술적 통합이 필요합니다.'],
    'qualificationRequirements': []},
   'valueSemantics': [{'fieldKey': 'conceptName',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'conceptDefinition',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'introduction',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'coreValue',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'targetUsers',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'industryCategory',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'researchScope',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'targetRegion',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'revenueModel',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'price',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'channels',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'differentiators',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'preMarketSomShareHypothesis',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'preMarketSomHypothesis',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'actorRoles',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'platformRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'problemScenario',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'solutionMechanism',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'featureSet',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'operatingModel',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'partnerModel',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'providerRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'sellerRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'intermediaryRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'transactionFlow',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'paymentFlow',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'personalDataUsage',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'physicalActivities',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'partnerRequirements',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'qualificationRequirements',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'advertisingClaims',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'}],
   'canonicalHash': 'sha256:677484c43beefacf17581aa35bfc5f63e6ca96c68c4818baa41be17095c702b5'},
  'finalHypotheses': {'targetRegion': {'value': '대한민국',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'revenueModel': {'value': '구독 모델을 통해 월별 또는 연별 요금제로 서비스 이용이 가능합니다.',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'price': {'value': '월 10만원 또는 연 100만원',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'channels': {'value': '온라인 마케팅 및 CRM 솔루션 제공업체와의 파트너십을 통한 유통',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'differentiators': {'value': 'AI 기반 자동화, 사용자 친화적인 인터페이스, CRM 통합 기능',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'preMarketSomShare': {'value': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='중소기업 시장의 CRM 자동화 수요 증가에 따른 점유율 목표.', assumptions=['중소기업의 CRM 도입률 증가', 'AI 기술에 대한 신뢰도 향상']),
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'preMarketSom': {'value': PreMarketSomHypothesis(amount=50000000.0, currency='KRW', period='1년', calculationBasis='중소기업 영업팀의 수와 평균 구독료를 기반으로 한 추정치.', assumptions=['중소기업의 평균 영업팀 규모는 5명', '연간 1000개의 중소기업이 신규 도입할 것으로 예상'], confidence='MEDIUM'),
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'}},
  'legalResult': {'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
   'safeSummary': 'AI 기반 자동화 및 CRM 통합 서비스 제공이 법적으로 가능하며, 고영향 인공지능 관련 법령 준수 및 소비자 보호를 위한 통제조건이 필요합니다.',
   'requiredControls': ['고영향 인공지능에 해당하는지 사전에 검토해야 한다.',
    '고영향 인공지능의 안전성 및 신뢰성을 확보하기 위한 조치를 이행해야 한다.',
    '고영향 인공지능을 이용한 제품 또는 서비스의 영향을 평가해야 한다.',
    '정보통신서비스 제공자는 이용자를 보호하고 안전한 서비스를 제공해야 한다.',
    '정보통신망 이용촉진 및 정보보호 시책을 마련해야 한다.',
    '사업자는 소비자를 속이거나 잘못 알게 할 우려가 있는 광고를 해서는 안 된다.',
    '사업자는 광고 내용에 대해 실증할 수 있어야 한다.'],
   'requiredPartnersAndQualifications': ['CRM 솔루션 제공업체와의 기술적 통합이 필요합니다.'],
   'prohibitedVariants': [],
   'requiredDisclosures': ['서비스 이용약관 및 개인정보 처리방침을 명확히 고지해야 한다.'],
   'officialEvidenceReferences': [{'referenceIndex': 0,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '014820',
     'officialIdentifier': '282791',
     'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
     'articleReference': '제3조',
     'title': '기본원칙 및 국가 등의 책무',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:d3af532ea737d1273289ec05ed2ff55c735bccac16c517b64292d7beeccd5312',
     'boundedProvisionSummary': '인공지능기술과 인공지능산업은 안전성과 신뢰성을 제고하여 국민의 삶의 질을 향상시키는 방향으로 발전되어야 한다.',
     'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 1,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '014820',
     'officialIdentifier': '282791',
     'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
     'articleReference': '제33조',
     'title': '고영향 인공지능의 확인',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:3fc48c2346668bf69d17684a6ea9e0adf2b1e2deb1409e8094281cbeefa8b48d',
     'boundedProvisionSummary': '인공지능사업자는 고영향 인공지능에 해당하는지 사전에 검토해야 한다.',
     'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 2,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '014820',
     'officialIdentifier': '282791',
     'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
     'articleReference': '제34조',
     'title': '고영향 인공지능과 관련한 사업자의 책무',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:617313212eede73a9fa4de775860b754747632549637a3da96e8e1b7fc0677c4',
     'boundedProvisionSummary': '고영향 인공지능의 안전성 및 신뢰성을 확보하기 위한 조치를 이행해야 한다.',
     'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 3,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '014820',
     'officialIdentifier': '282791',
     'lawName': '인공지능 발전과 신뢰 기반 조성 등에 관한 기본법',
     'articleReference': '제35조',
     'title': '고영향 인공지능 영향평가',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EB%B0%9C%EC%A0%84%EA%B3%BC%20%EC%8B%A0%EB%A2%B0%20%EA%B8%B0%EB%B0%98%20%EC%A1%B0%EC%84%B1%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EA%B8%B0%EB%B3%B8%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:fb8ebf040c2029dd28b2bd73badb7e225880c1a211d422abac790f568fb5d8c5',
     'boundedProvisionSummary': '고영향 인공지능을 이용한 제품 또는 서비스의 영향을 평가해야 한다.',
     'queryKey': 'sha256:5df7a84e71ddb6c9bbd565f0fbe1a0986b1c9b0ac7bb1179c4e7c0753c8175d9',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 4,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '000030',
     'officialIdentifier': '282481',
     'lawName': '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
     'articleReference': '제3조',
     'title': '정보통신서비스 제공자 및 이용자의 책무',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0%EB%A7%9D%20%EC%9D%B4%EC%9A%A9%EC%B4%89%EC%A7%84%20%EB%B0%8F%20%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260106',
     'effectiveDate': '20260707',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:0f8a92d020f0e4f81e3020f1fae1178b3a63b92768de88a28f48449d7d37dd83',
     'boundedProvisionSummary': '정보통신서비스 제공자는 이용자를 보호하고 안전한 서비스를 제공해야 한다.',
     'queryKey': 'sha256:7950518a36e66a586195226f8a68f7683de9c44930cbffec85bfe270ccd8cc59',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 5,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '000030',
     'officialIdentifier': '282481',
     'lawName': '정보통신망 이용촉진 및 정보보호 등에 관한 법률',
     'articleReference': '제4조',
     'title': '정보통신망 이용촉진 및 정보보호등에 관한 시책의 마련',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0%EB%A7%9D%20%EC%9D%B4%EC%9A%A9%EC%B4%89%EC%A7%84%20%EB%B0%8F%20%EC%A0%95%EB%B3%B4%EB%B3%B4%ED%98%B8%20%EB%93%B1%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260106',
     'effectiveDate': '20260707',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:fa6d134f7eaa58efaed72e7d30f93e2d19c6edf8b92fb43c9f1ce70e616989e1',
     'boundedProvisionSummary': '정보통신망 이용촉진 및 정보보호 시책을 마련해야 한다.',
     'queryKey': 'sha256:7950518a36e66a586195226f8a68f7683de9c44930cbffec85bfe270ccd8cc59',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 6,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '002011',
     'officialIdentifier': '268659',
     'lawName': '표시ㆍ광고의 공정화에 관한 법률',
     'articleReference': '제3조',
     'title': '부당한 표시ㆍ광고 행위의 금지',
     'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250121',
     'effectiveDate': '20250121',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:8a232304b3941209cf6afb47ff8485dec72a80b22d8ea0bd5f72b07f583b5826',
     'boundedProvisionSummary': '사업자는 소비자를 속이거나 잘못 알게 할 우려가 있는 광고를 해서는 안 된다.',
     'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 7,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '002011',
     'officialIdentifier': '268659',
     'lawName': '표시ㆍ광고의 공정화에 관한 법률',
     'articleReference': '제5조',
     'title': '표시ㆍ광고 내용의 실증 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250121',
     'effectiveDate': '20250121',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:175e1d20e79b88964eddbcfa658507a8968209ddba38fe094bc7005015b0ba30',
     'boundedProvisionSummary': '사업자는 광고 내용에 대해 실증할 수 있어야 한다.',
     'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 8,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '002011',
     'officialIdentifier': '268659',
     'lawName': '표시ㆍ광고의 공정화에 관한 법률',
     'articleReference': '제10조',
     'title': '손해배상책임',
     'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250121',
     'effectiveDate': '20250121',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:9e32cfffe5aee496b1832d5e3707961c9f4280d83dc0f91deaf66f0318f1de73',
     'boundedProvisionSummary': '부당한 광고 행위로 피해를 입은 자에게 손해배상 책임을 진다.',
     'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 9,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '002011',
     'officialIdentifier': '268659',
     'lawName': '표시ㆍ광고의 공정화에 관한 법률',
     'articleReference': '제17조',
     'title': '벌칙',
     'officialSourceUri': 'https://www.law.go.kr/법령/%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%9D%98%20%EA%B3%B5%EC%A0%95%ED%99%94%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250121',
     'effectiveDate': '20250121',
     'retrievedAt': '2026-08-10T08:47:36.808707Z',
     'contentHash': 'sha256:f8efc781c87796884bf25f8d680b1efcd4e223f5e470a5b156122d6d82e15692',
     'boundedProvisionSummary': '부당한 광고 행위를 한 자에게 징역형 또는 벌금형에 처한다.',
     'queryKey': 'sha256:90d9771bc75e6de6069905fe746a5d12ae11896159015fd6e37c2f5d242dbfbe',
     'registryVersion': 'legal-registry-v1'}],
   'deltaLegalReviews': []}},
 'Marketing payload': {'contract': 'marketing-source-snapshot-v1',
  'schemaVersion': '2.0',
  'snapshotId': 'lab-marketing-source',
  'projectId': 0,
  'selectionId': 0,
  'conceptId': 'C1',
  'marketAnalysisSeedSnapshotId': 'lab-market-seed',
  'marketAnalysisSeedSnapshotHash': 'sha256:441e70a038466b564bdaf9fc225545dd6941846e7374ff9c6d547a83ad58896a',
  'createdAt': '2026-08-10T08:48:03.272905+00:00',
  'conceptName': '중소기업 영업팀을 위한 AI 기반 CRM 자동화 도구',
  'targetSegment': '별도 영업 운영 인력이 부족한 중소기업 영업팀',

## 41. Trace

In [42]:
display(show_trace(engine.trace))

,순서,시각,stage,action,entity,parent,status,mode,호출,요약,decision,reasonCode
0,1,2026-08-10T08:43:41.248608+00:00,CREATED,CREATED,NaN,NaN,RUNNING,LIVE,NaN,V2 Lab 실행을 생성했습니다.,NaN,NaN
1,2,2026-08-10T08:43:47.908378+00:00,SAFETY_CHECKING,IDEA_BRIEF_DERIVED,NaN,NaN,PASS,LIVE,1.0,Idea interpretation/readiness를 보존했습니다: READY_F...,NaN,NaN
2,3,2026-08-10T08:43:47.908402+00:00,SAFETY_CHECKING,READINESS_INCONSISTENT,NaN,NaN,WARNING,LIVE,NaN,READY_FOR_REVIEW이지만 score=0입니다. V2 gating은 막지 ...,READINESS_INCONSISTENT,NaN
3,4,2026-08-10T08:43:47.963651+00:00,SEED_ANALYZING,ANALYZED,lab-idea-brief,NaN,PASS,LIVE,NaN,필수 3개와 LOCK 3개를 분류했습니다.,NaN,NaN
4,5,2026-08-10T08:43:47.964038+00:00,SEED_ANALYZING,DESIGN_SPACE_READY,NaN,NaN,PASS,LIVE,NaN,Open=11 Constrained=0 Breadth=EXPLORE,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
60,61,2026-08-10T08:47:42.977500+00:00,LEGAL_RECOVERING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Legal route별 복구를 수행합니다.,NaN,NaN
61,62,2026-08-10T08:47:42.986138+00:00,LEGAL_REVIEWING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,공식 Legal contract route를 실행합니다.,NaN,NaN
62,63,2026-08-10T08:48:03.187642+00:00,LEGAL_REVIEWING,REVIEWED,C2,NaN,ACCEPT,LIVE,27.0,이 서비스는 사용자의 회의 및 이메일 내용을 분석하여 생산성을 높이는 AI 기반 솔...,ACCEPT,NaN
63,64,2026-08-10T08:48:03.187665+00:00,LEGAL_RECOVERING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Legal route별 복구를 수행합니다.,NaN,NaN
64,65,2026-08-10T08:48:03.278621+00:00,PORTFOLIO_VALIDATING,HANDOFF_VALIDATED,C1,NaN,PASS,LIVE,NaN,downstream contract compatibility=PASS,NaN,NaN

## 42. Provider/Legal Usage

In [43]:
display(show_provider_usage(engine.gateway.usage))
print('상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.')

,논리 작업,상위 외부 작업,논리 stage별,상위 외부 작업 stage별,재시도,소요(ms),모드별,token,보고 비용
0,27,27,"{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...","{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...",0,261143,{'LIVE': 27},None,None

상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.

## 43. Replay Manifest

In [44]:
display(show_replay_manifest(engine.gateway))

{'status': 'REPLAY_PARTIAL',
 'entries':                    operation  \
 0               LEGAL_REVIEW
 1          SEMANTIC_RELATION
 2              PLAN_FIDELITY
 3                     EXPAND
 4    NORMALIZE_ARCHITECTURES
 ..                       ...
 632    IDEA_BRIEF_DERIVATION
 633       PLAN_REPLENISHMENT
 634                PLAN_POOL
 635  NORMALIZE_ARCHITECTURES
 636             LEGAL_REVIEW

                                                   hash operationVersion  \
 0    00489dd62bff3c4b9e8711093fb3e398a39dde1547de32...               v3
 1    00c1eeb4f93989a6db3891fb7a22355a71a68800a6f641...               v3
 2    00e62d4c1a15307c38d9024cb66e28f8d13300af644fff...               v3
 3    0120f755ef50e68db6e1d7d1adb0563892b2f762578608...               v3
 4    013ebfc11d61a317c1041ddcf75902b1dab0d310e73666...               v1
 ..                                                 ...              ...
 632  fc5b3fe1b2fb09f8b0b6587abc4a067f3c1f1682a4e68c...               v2
 633  fcc0dde517404bc3712e16384ce9f3a9c44ca5d5f06242...               v3
 634  fd4ea7d8f4c176971dc390682c54fb6d7bc7428fa2d79a...               v3
 635  fea1f1598d55de131f0c6485d3428dcec697b958ef73af...               v1
 636  ff7ecbd2ee5cb90f030bc7972f25779b05155b203be50c...               v3

                                     promptVersion schemaVersion  recordExists  \
 0                         concept-legal-review-v3           2.0          True
 1                   concept-portfolio-relation-v3           2.0          True
 2                   concept-portfolio-fidelity-v3           2.0          True
 3          concept-portfolio-generic-candidate-v3           2.0          True
 4    concept-portfolio-architecture-classifier-v1           2.0          True
 ..                                            ...           ...           ...
 632                         idea-brief-current-v2           2.0          True
 633             concept-portfolio-generic-plan-v3           2.0          True
 634             concept-portfolio-generic-plan-v3           2.0          True
 635  concept-portfolio-architecture-classifier-v2           2.0          True
 636                       concept-legal-review-v3           2.0          True

                             timestamp  versionCompatible
 0    2026-08-10T05:26:30.277902+00:00               True
 1    2026-08-10T05:23:00.398650+00:00               True
 2    2026-08-10T08:46:11.451002+00:00               True
 3    2026-08-10T07:53:56.875008+00:00               True
 4    2026-08-10T06:48:53.957430+00:00               True
 ..                                ...                ...
 632  2026-08-10T08:44:30.967742+00:00               True
 633  2026-08-10T07:55:41.833711+00:00               True
 634  2026-08-10T04:53:21.046707+00:00               True
 635  2026-08-10T08:46:56.440111+00:00               True
 636  2026-08-10T05:18:41.881979+00:00               True

 [637 rows x 8 columns]}

## 44. One-click MOCK

In [45]:
mock_result = None
if LIVE_TEST_LEVEL == 'FULL_E2E' and MODE != 'LIVE':
    mock_result = await ConceptPortfolioEngine('MOCK').run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=True)
display(show_run_summary(mock_result) if mock_result else {'status': 'SKIPPED'})
assert mock_result is None or (mock_result.handoff and mock_result.handoff.contractStatus == 'CONTRACT_PASS')

{'status': 'SKIPPED'}

## 45. One-click REPLAY

In [46]:
RUN_ONE_CLICK_REPLAY = False
replay_result = None
if RUN_ONE_CLICK_REPLAY:
    replay_gateway = ProviderGateway('REPLAY', recordings_dir=RECORDINGS_DIR)
    replay_result = await ConceptPortfolioEngine('REPLAY', gateway=replay_gateway).run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=False)
display(show_run_summary(replay_result) if replay_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}

## 46. One-click LIVE

In [47]:
RUN_ONE_CLICK_LIVE = True
live_result = None
if RUN_ONE_CLICK_LIVE and LIVE_TEST_LEVEL == 'ONE_CLICK':
    assert MODE == 'LIVE', 'MODE=LIVE를 먼저 명시하세요.'
    one_click_gateway = ProviderGateway('LIVE', recordings_dir=RECORDINGS_DIR)
    one_click_engine = ConceptPortfolioEngine('LIVE', gateway=one_click_gateway)
    live_result = await one_click_engine.run_full(TEST_INPUT, max_concepts=MAX_CONCEPTS,
                                                  auto_confirm_hypotheses=False)
display(show_run_summary(live_result) if live_result else {'status': 'SKIPPED'})
if live_result:
    display(show_live_validation_summary(LIVE_SCENARIO, live_result))
    display(show_required_inputs(live_result))
    display(show_pre_legal_exclusions(live_result))
    display(show_legal_resolutions(live_result))
    if live_result.runStatus.value == 'FAILED':
        display(show_run_failure(live_result))
        display(show_provider_failure(one_click_engine.gateway))
        display(show_provider_usage(live_result.providerUsage))
        display(show_trace(live_result.trace[-20:]))
        display({'unresolvedCandidates': live_result.unresolvedCandidates,
                 'lastSuccessfulStage': live_result.failureDiagnostics.lastSuccessfulStage if live_result.failureDiagnostics else None,
                 'firstFailedStage': live_result.failureDiagnostics.firstFailedStage if live_result.failureDiagnostics else None})

{'status': 'SKIPPED'}