## 00. Quick Start

In [1]:
print('Concept Portfolio V2 Lab — 기본 MODE는 MOCK입니다.')
print('LIVE는 06→28 순서의 staged 검증 후 46의 가드를 직접 켜야 합니다.')

Concept Portfolio V2 Lab — 기본 MODE는 MOCK입니다.
LIVE는 06→28 순서의 staged 검증 후 46의 가드를 직접 켜야 합니다.

## 01. Environment

In [2]:
import os, sys, json
from pathlib import Path
from IPython.display import display
SEARCH_ROOTS = [Path.cwd(), *Path.cwd().parents]
AI_ROOT = next((p for p in SEARCH_ROOTS if (p / 'app').is_dir()), None)
if AI_ROOT is None: AI_ROOT = next((p / 'ai' for p in SEARCH_ROOTS if (p / 'ai' / 'app').is_dir()))
if str(AI_ROOT) not in sys.path: sys.path.insert(0, str(AI_ROOT))
print({'python': sys.version.split()[0], 'aiRoot': str(AI_ROOT)})

{'python': '3.14.5', 'aiRoot': 'C:\\Users\\seewo\\Desktop\\big_proj_01\\new_3\\ai'}

## 02. MODE

In [3]:
MODE = 'LIVE'  # MOCK | REPLAY | LIVE
RECORDINGS_DIR = AI_ROOT / 'recordings' / 'concept_portfolio_v2'
print({'mode': MODE, 'liveExternalOperationsEnabled': MODE == 'LIVE'})

{'mode': 'LIVE', 'liveExternalOperationsEnabled': True}

## 03. Environment Check

In [4]:
LIVE_ENV_KEYS = ['AI_PROVIDER', 'AI_API_KEY', 'AI_MODEL', 'MOLEG_API_KEY', 'LEGAL_REGISTRY_VERSION']
env_status = {key: bool(os.getenv(key)) for key in LIVE_ENV_KEYS}
print(env_status if MODE == 'LIVE' else {'mode': MODE, 'message': '외부 환경변수 불필요'})

{'AI_PROVIDER': True, 'AI_API_KEY': True, 'AI_MODEL': True, 'MOLEG_API_KEY': True, 'LEGAL_REGISTRY_VERSION': True}

## 04. Schema Preflight

In [5]:
from app.concept_portfolio_v2 import ConceptPortfolioEngine, ProviderGateway, ProviderMode
from app.concept_portfolio_v2.adapters import CurrentLegalAdapter
from app.concept_portfolio_v2.diagnostics.notebook_view import *
gateway = ProviderGateway(MODE, recordings_dir=RECORDINGS_DIR)
engine = ConceptPortfolioEngine(MODE, gateway=gateway)
schema_preflight = engine.schema_preflight_report()
display(show_schema_preflight(schema_preflight))
assert schema_preflight.status == 'PASS' and schema_preflight.providerCalls == 0

                          스키마    상태  실패  Provider 호출
0               PlanDraftPool  PASS  []            0
1       ConceptCandidateDraft  PASS  []            0
2  SemanticDistinctnessResult  PASS  []            0
3      SemanticFidelityResult  PASS  []            0
4   SemanticArchitectureBatch  PASS  []            0

## 05. Input

In [6]:
TEST_INPUT = {
    'ideaOverview': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
    'problem': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다',
    'targetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
}
MAX_CONCEPTS = 5

## 06. Idea Brief Derivation

In [7]:
engine._reset()
seed = engine.seed_adapter.adapt(TEST_INPUT)
idea_context = await engine.derive_idea_brief(seed)
print({'ideaCallComplete': True, 'interpretationPresent': bool(seed.interpretation)})

{'ideaCallComplete': True, 'interpretationPresent': True}

## 07. Safety

In [8]:
display(idea_context.safetyReview.model_dump(mode='json'))
assert idea_context.safetyReview.passed

{'decision': 'ALLOW',
 'categories': [],
 'restrictions': [],
 'userFacingReason': '이 아이디어는 안전하며, 개인 맞춤형 식재료 제공과 관련된 문제를 해결하는 데 기여할 수 있습니다.'}

## 08. AI가 이해한 아이디어

In [9]:
display(show_idea_interpretation(idea_context))

                               항목                                 AI 이해 결과
0              interpretedProblem  1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.
1          interpretedTargetUsers       요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구.
2                    usageContext  소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.
3                industryCategory                              식품 및 요리 서비스
4                   researchScope        소량 식재료 제공 및 레시피 안내 서비스에 대한 시장 조사.
5           conciseIdeaDefinition         개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.
6      targetRegionInterpretation                     특정 지역에 대한 정보가 필요합니다.
7  relevantKnownCompetitorContext                       경쟁자에 대한 정보가 필요합니다.

## 09. Readiness / Summary / commitments

In [10]:
display(show_idea_readiness(idea_context))

{'readiness': {'status': 'READY_FOR_REVIEW',
  'score': 0,
  'missingFieldKeys': []},
 'readinessDiagnostic': 'READINESS_INCONSISTENT',
 'userFacingSummary': '이 서비스는 개인 맞춤형 소량 식재료를 제공하고, 남은 재료를 활용할 수 있는 레시피를 안내하여 1~2인 가구의 음식물 쓰레기 문제를 해결하는 데 도움을 줄 수 있습니다.',
 'commitmentCandidates': [],
 'contradictions': [],
 'questions': []}

## 10. Seed Analysis

In [11]:
analysis = await engine.analyze_seed(seed)
display(show_seed_analysis(analysis))

        구분                                                  값
0     탐색 폭                                            EXPLORE
1  다양성 수용량                                                  5
2       설명  선택 입력 LOCK 0개로 11개 설계 차원이 열려 있습니다. diversityCa...

## 11. Generic Opportunity Kernel

In [12]:
display(analysis.opportunityKernel.model_dump(mode='json'))

{'problemCore': '1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.',
 'targetCore': '요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구.',
 'useContexts': ['소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.'],
 'intentComponents': ['개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.'],
 'mustPreserve': ['1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.',
  '요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구.',
  '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.'],
 'maySpecialize': ['핵심 대상의 의미 있는 하위 세그먼트',
  '핵심 사용 맥락의 구체화',
  '가치 제안 또는 offer의 구체화'],
 'forbiddenDriftSummary': '핵심 문제와 대상이 모두 무관한 기회로 교체되면 범위를 벗어납니다.'}

## 12. Design Space

In [13]:
display(show_design_space(analysis))

,분류,필드,값
0,SOURCE_LOCK,ideaOverview,개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스
1,SOURCE_LOCK,problem,1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다
2,SOURCE_LOCK,targetUsers,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구
3,SEMANTIC_ANCHOR,ideaOverview,개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스
4,SEMANTIC_ANCHOR,problem,1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다
5,SEMANTIC_ANCHOR,targetUsers,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구
6,OPEN,solutionMechanism,변경 가능
7,OPEN,valueDelivery,변경 가능
8,OPEN,operatingModel,변경 가능
9,OPEN,supplyStructure,변경 가능
10,OPEN,partnerModel,변경 가능
11,OPEN,transactionFlow,변경 가능
12,OPEN,fulfillment,변경 가능
13,OPEN,platformRole,변경 가능
14,OPEN,commercialFlow,변경 가능
15,OPEN,dataDependency,변경 가능
16,OPEN,physicalDependency,변경 가능

## 13. Generate and Adaptively Replenish Plan Pool

In [14]:
plan_validation = await engine.prepare_portfolio_plans(seed, analysis, max_concepts=MAX_CONCEPTS)
plans = engine._last_plan_pool
print({'totalPlans': len(plans), 'planningRounds': plan_validation.planningRounds,
       'replenishmentRequested': plan_validation.replenishmentRequested})

{'totalPlans': 7, 'planningRounds': 1, 'replenishmentRequested': 0}

## 14. Plan Count / Adaptive Replenishment Check

In [15]:
display(show_plan_pool_status(engine._last_plan_pool_status))
display({'planningRounds': plan_validation.planningRounds,
         'replenishmentRequested': plan_validation.replenishmentRequested,
         'adaptiveReplenishmentUsed': plan_validation.planningRounds > 1})

,requestedPoolSize,returnedPoolSize,initialTarget,reserveTarget,reserveAvailable,status
0,7,7,5,2,2,RESERVE_READY

{'planningRounds': 1,
 'replenishmentRequested': 0,
 'adaptiveReplenishmentUsed': False}

## 15. Korean Plan Display

In [16]:
display(show_portfolio_plans(plan_validation.acceptedPlans + plan_validation.reservePlans))

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P7,요리 초보를 위한 맞춤형 서비스,SELECTED,0.8373,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,요리 초보를 위한 맞춤형 식재료와 레시피를 제공하여 요리의 즐거움을 더한다.,요리 초보를 위한 맞춤형 식재료와 레시피 제공으로 요리의 즐거움을 더한다.,요리 초보를 위한 소량 식재료와 간편한 레시피를 통해 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리 초보의 문제를 해결하기 위한 핵심 서비스.
1,P1,소량 맞춤형 식재료 서비스,SELECTED,0.8302,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료를 제공하여 음식물 쓰레기를 줄이고 요리를 쉽게 할 수 있도록 ...,소량의 식재료와 레시피를 제공하여 1~2인 가구의 요리 경험을 개선한다.,"개인 맞춤형 식재료와 레시피를 통해 요리의 번거로움을 줄이고, 음식물 쓰레기를 최소...","{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 요리 문제를 해결하기 위한 핵심 서비스.
2,P3,간편 요리 키트 서비스,SELECTED,0.7430,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,간편하게 요리할 수 있는 키트를 제공하여 요리의 번거로움을 줄인다.,간편 요리 키트를 통해 요리의 즐거움을 제공한다.,소량의 식재료와 간편한 레시피를 통해 요리의 접근성을 높인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리의 번거로움을 줄이고 1~2인 가구의 문제를 해결하는 서비스.
3,P4,맞춤형 식사 계획 서비스,SELECTED,0.6346,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,개인 맞춤형 식사 계획을 통해 요리의 효율성을 높인다.,맞춤형 식사 계획과 소량 식재료 제공으로 요리의 편리함을 더한다.,고객의 식사 스타일에 맞춘 식사 계획과 식재료 제공으로 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 식사 문제를 해결하기 위한 핵심 서비스.
4,P5,건강한 소량 식재료 서비스,SELECTED,0.5475,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,건강한 소량 식재료를 제공하여 요리의 질을 높인다.,건강한 식재료를 소량으로 제공하여 요리의 질을 높인다.,소량의 건강한 식재료를 통해 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",건강한 식재료를 제공하여 1~2인 가구의 문제를 해결하는 서비스.
5,P2,레시피 기반 식재료 패키지,RESERVE,0.6939,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,레시피에 맞춘 소량의 식재료를 제공하여 요리의 편리함을 더한다.,레시피에 최적화된 식재료 패키지를 제공하여 요리의 효율성을 높인다.,고객의 요리 스타일에 맞춘 식재료 패키지를 통해 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리의 편리함을 제공하여 1~2인 가구의 문제를 해결하는 서비스.
6,P6,신선한 재료 정기 배송 서비스,RESERVE,0.6825,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,신선한 식재료를 정기적으로 제공하여 요리의 질을 높인다.,신선한 식재료를 정기적으로 제공하여 요리의 질을 높인다.,정기 배송을 통해 신선한 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",신선한 식재료를 제공하여 1~2인 가구의 문제를 해결하는 서비스.

## 16. Plan Lock/Intent Validation

In [17]:
display({'accepted': [p.planId for p in plan_validation.acceptedPlans],
         'rejected': [p.model_dump(mode='json') for p in plan_validation.rejectedPlans]})

{'accepted': ['P7', 'P1', 'P3', 'P4', 'P5'], 'rejected': []}

## 17. Portfolio Family / Variant / Distinct

In [18]:
display(show_plan_diversity(plan_validation.diversity))

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,P1,P2,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,P1,P3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, customerInteractionModel, valueP...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,P2,P3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,P1,P4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, customerInteractionModel, valueP...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
4,P2,P4,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
5,P3,P4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,P1,P5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,P2,P5,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
8,P3,P5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,P4,P5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
10,P1,P6,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
11,P2,P6,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
12,P3,P6,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
13,P4,P6,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
14,P5,P6,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...",solutionThesis,MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
15,P1,P7,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, customerInteractionModel, valueP...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
16,P2,P7,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
17,P3,P7,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
18,P4,P7,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
19,P5,P7,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
20,P6,P7,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.

## 18. Selected + Reserve Plans

In [19]:
selected_plans = plan_validation.acceptedPlans
reserve_plans = plan_validation.reservePlans
display(show_portfolio_plans(selected_plans + reserve_plans))
display({'selected': [p.planId for p in selected_plans], 'reserve': [p.planId for p in reserve_plans]})

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P7,요리 초보를 위한 맞춤형 서비스,SELECTED,0.8373,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,요리 초보를 위한 맞춤형 식재료와 레시피를 제공하여 요리의 즐거움을 더한다.,요리 초보를 위한 맞춤형 식재료와 레시피 제공으로 요리의 즐거움을 더한다.,요리 초보를 위한 소량 식재료와 간편한 레시피를 통해 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리 초보의 문제를 해결하기 위한 핵심 서비스.
1,P1,소량 맞춤형 식재료 서비스,SELECTED,0.8302,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료를 제공하여 음식물 쓰레기를 줄이고 요리를 쉽게 할 수 있도록 ...,소량의 식재료와 레시피를 제공하여 1~2인 가구의 요리 경험을 개선한다.,"개인 맞춤형 식재료와 레시피를 통해 요리의 번거로움을 줄이고, 음식물 쓰레기를 최소...","{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 요리 문제를 해결하기 위한 핵심 서비스.
2,P3,간편 요리 키트 서비스,SELECTED,0.7430,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,간편하게 요리할 수 있는 키트를 제공하여 요리의 번거로움을 줄인다.,간편 요리 키트를 통해 요리의 즐거움을 제공한다.,소량의 식재료와 간편한 레시피를 통해 요리의 접근성을 높인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리의 번거로움을 줄이고 1~2인 가구의 문제를 해결하는 서비스.
3,P4,맞춤형 식사 계획 서비스,SELECTED,0.6346,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,개인 맞춤형 식사 계획을 통해 요리의 효율성을 높인다.,맞춤형 식사 계획과 소량 식재료 제공으로 요리의 편리함을 더한다.,고객의 식사 스타일에 맞춘 식사 계획과 식재료 제공으로 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 식사 문제를 해결하기 위한 핵심 서비스.
4,P5,건강한 소량 식재료 서비스,SELECTED,0.5475,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,건강한 소량 식재료를 제공하여 요리의 질을 높인다.,건강한 식재료를 소량으로 제공하여 요리의 질을 높인다.,소량의 건강한 식재료를 통해 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",건강한 식재료를 제공하여 1~2인 가구의 문제를 해결하는 서비스.
5,P2,레시피 기반 식재료 패키지,RESERVE,0.6939,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,레시피에 맞춘 소량의 식재료를 제공하여 요리의 편리함을 더한다.,레시피에 최적화된 식재료 패키지를 제공하여 요리의 효율성을 높인다.,고객의 요리 스타일에 맞춘 식재료 패키지를 통해 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리의 편리함을 제공하여 1~2인 가구의 문제를 해결하는 서비스.
6,P6,신선한 재료 정기 배송 서비스,RESERVE,0.6825,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",기타 역할 · 기타 운영,요리할 시간이 적고 식재료 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,신선한 식재료를 정기적으로 제공하여 요리의 질을 높인다.,신선한 식재료를 정기적으로 제공하여 요리의 질을 높인다.,정기 배송을 통해 신선한 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",신선한 식재료를 제공하여 1~2인 가구의 문제를 해결하는 서비스.

{'selected': ['P7', 'P1', 'P3', 'P4', 'P5'], 'reserve': ['P2', 'P6']}

## 19. Candidate 1

In [20]:
candidate_one = await engine.expand_plan(seed, selected_plans[0], 1) if selected_plans else None
display(show_candidates([candidate_one]) if candidate_one else [])

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,요리 초보를 위한 맞춤형 서비스,요리 초보를 위한 소량 식재료와 간편한 레시피를 통해 음식물 쓰레기를 줄인다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 및 일회성 구매 옵션 제공,요리 초보 맞춤형 서비스 운영

## 20. Candidate 1 Korean/Governance

In [21]:
candidate_one_reports = []
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'status': 'PENDING_FULL_CANDIDATE_RECOVERY'})

{'candidateId': 'C1', 'status': 'PENDING_FULL_CANDIDATE_RECOVERY'}

## 21. Candidate 1 Actual Generic Descriptor

In [22]:
display(show_concept_descriptors([candidate_one]) if candidate_one else [])

,entityId,family,dimension,code,confidence,source
0,C1,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
1,C1,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
2,C1,INTERMEDIARY:OTHER,partnerModel,OTHER,LOW,UNKNOWN
3,C1,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
4,C1,INTERMEDIARY:OTHER,transactionModel,OTHER,LOW,UNKNOWN
5,C1,INTERMEDIARY:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
6,C1,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
7,C1,INTERMEDIARY:OTHER,dataDependency,NONE,NaN,NaN
8,C1,INTERMEDIARY:OTHER,physicalDependency,NONE,NaN,NaN

## 22. Candidate 1 Fidelity

In [23]:
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'})

{'candidateId': 'C1',
 'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'}

## 23. Remaining Candidates

In [24]:
remaining_candidates = []
for i, plan in enumerate(selected_plans[1:], 2):
    remaining_candidates.append(await engine.expand_plan(seed, plan, i))
candidate_drafts = ([candidate_one] if candidate_one else []) + remaining_candidates
display(show_candidates(candidate_drafts))

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,요리 초보를 위한 맞춤형 서비스,요리 초보를 위한 소량 식재료와 간편한 레시피를 통해 음식물 쓰레기를 줄인다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 및 일회성 구매 옵션 제공,요리 초보 맞춤형 서비스 운영
1,C2,L2,None,소량 맞춤형 식재료 서비스,"개인 맞춤형 식재료와 레시피를 통해 요리의 번거로움을 줄이고, 음식물 쓰레기를 최소...",기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 옵션 제공,고객 맞춤형 주문 시스템 운영
2,C3,L3,None,간편 요리 키트 서비스,주문 후 1~2일 이내 배송되는 간편 요리 키트를 통해 요리의 즐거움을 제공한다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 및 일회성 구매 옵션 제공,고객 맞춤형 요리 키트 운영
3,C4,L4,None,맞춤형 식사 계획 서비스,고객의 식사 스타일에 맞춘 식사 계획과 식재료 제공으로 음식물 쓰레기를 줄인다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 및 일회성 구매 옵션 제공,고객 맞춤형 식사 계획 운영
4,C5,L5,None,건강한 소량 식재료 서비스,소량의 건강한 식재료를 통해 음식물 쓰레기를 줄인다.,거래 중개 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 및 일회성 구매 옵션 제공,건강한 식재료 패키지 운영

## 24. Candidate Actual Generic Descriptors

In [25]:
display(show_concept_descriptors(candidate_drafts))

,entityId,family,dimension,code,confidence,source
0,C1,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
1,C1,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
2,C1,INTERMEDIARY:OTHER,partnerModel,OTHER,LOW,UNKNOWN
3,C1,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
4,C1,INTERMEDIARY:OTHER,transactionModel,OTHER,LOW,UNKNOWN
5,C1,INTERMEDIARY:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
6,C1,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
7,C1,INTERMEDIARY:OTHER,dataDependency,NONE,NaN,NaN
8,C1,INTERMEDIARY:OTHER,physicalDependency,NONE,NaN,NaN
9,C2,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
10,C2,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
11,C2,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
12,C2,OTHER:OTHER,deliveryModel,DIGITAL,HIGH,RULE
13,C2,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
14,C2,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
15,C2,OTHER:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
16,C2,OTHER:OTHER,dataDependency,NONE,NaN,NaN
17,C2,OTHER:OTHER,physicalDependency,NONE,NaN,NaN
18,C3,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
19,C3,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
20,C3,OTHER:OTHER,partnerModel,OTHER,LOW,UNKNOWN
21,C3,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
22,C3,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
23,C3,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
24,C3,OTHER:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
25,C3,OTHER:OTHER,dataDependency,NONE,NaN,NaN
26,C3,OTHER:OTHER,physicalDependency,NONE,NaN,NaN
27,C4,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
28,C4,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
29,C4,OTHER:OTHER,partnerModel,OTHER,LOW,UNKNOWN
30,C4,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
31,C4,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
32,C4,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
33,C4,OTHER:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
34,C4,OTHER:OTHER,dataDependency,NONE,NaN,NaN
35,C4,OTHER:OTHER,physicalDependency,NONE,NaN,NaN
36,C5,INTERMEDIARY:OTHER,businessRole,INTERMEDIARY,HIGH,RULE
37,C5,INTERMEDIARY:OTHER,operatingModel,OTHER,LOW,UNKNOWN
38,C5,INTERMEDIARY:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
39,C5,INTERMEDIARY:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
40,C5,INTERMEDIARY:OTHER,transactionModel,OTHER,LOW,UNKNOWN
41,C5,INTERMEDIARY:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
42,C5,INTERMEDIARY:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
43,C5,INTERMEDIARY:OTHER,dataDependency,NONE,NaN,NaN
44,C5,INTERMEDIARY:OTHER,physicalDependency,NONE,NaN,NaN

## 25. Candidate Recovery / Portfolio Relations

In [26]:
candidate_preparation = await engine.prepare_candidate_portfolio(
    seed, plan_validation, max_concepts=MAX_CONCEPTS, initial_candidates=candidate_drafts)
candidates = candidate_preparation.candidates
candidate_reports = candidate_preparation.reports
display(show_candidate_recovery(candidate_preparation))
candidate_pairwise = [engine.compare_candidates(candidates[i], candidates[j])
                      for i in range(len(candidates)) for j in range(i + 1, len(candidates))]
display(show_plan_diversity(candidate_pairwise))

{'summary':    candidateGenerated  candidateAcceptedInitially  candidateRegenerated  \
 0                   5                           5                     0

    candidateRecovered  reservePlansActivated  candidateRecoveryReplans  \
 0                   0                      0                         0

    finalCandidatePortfolio
 0                        5  ,
 'attempts':   candidateId  schemaValid  hardLockPreserved  semanticAnchorPreserved  \
 0          C1         True               True                     True
 1          C2         True               True                     True
 2          C3         True               True                     True
 3          C4         True               True                     True
 4          C5         True               True                     True

    planFidelity anchorDecision fidelityDecision  contentLanguageValid  \
 0          True           PASS          ADAPTED                  True
 1          True           PASS          ADAPTED                  True
 2          True           PASS             PASS                  True
 3          True           PASS          ADAPTED                  True
 4          True           PASS          ADAPTED                  True

    accepted   outcome  semanticFidelityUsed  \
 0      True  ACCEPTED                 False
 1      True  ACCEPTED                 False
 2      True  ACCEPTED                  True
 3      True  ACCEPTED                 False
 4      True  ACCEPTED                 False

                            matchedIdentityComponents  \
 0  [targetSegmentThesis, valuePropositionThesis, ...
 1  [targetSegmentThesis, valuePropositionThesis, ...
 2          [주문형 맞춤형 식재료 제공, 간편 요리 레시피 제공, 정기 배송 서비스]
 3  [targetSegmentThesis, valuePropositionThesis, ...
 4  [targetSegmentThesis, valuePropositionThesis, ...

       missingIdentityComponents reasonCodes safeSummary
 0  [useCaseThesis, offerThesis]          []       검사 통과
 1  [useCaseThesis, offerThesis]          []       검사 통과
 2                            []          []       검사 통과
 3  [useCaseThesis, offerThesis]          []       검사 통과
 4  [useCaseThesis, offerThesis]          []       검사 통과  ,
 'finalCandidates':   candidateId lineageId parentCandidateId                 이름  \
 0          C1        L1              None  요리 초보를 위한 맞춤형 서비스
 1          C2        L2              None     소량 맞춤형 식재료 서비스
 2          C3        L3              None       간편 요리 키트 서비스
 3          C4        L4              None      맞춤형 식사 계획 서비스
 4          C5        L5              None     건강한 소량 식재료 서비스

                                              핵심 작동방식         family  \
 0        요리 초보를 위한 소량 식재료와 간편한 레시피를 통해 음식물 쓰레기를 줄인다.  거래 중개 · 기타 운영
 1  개인 맞춤형 식재료와 레시피를 통해 요리의 번거로움을 줄이고, 음식물 쓰레기를 최소...  기타 역할 · 기타 운영
 2      주문 후 1~2일 이내 배송되는 간편 요리 키트를 통해 요리의 즐거움을 제공한다.  기타 역할 · 기타 운영
 3       고객의 식사 스타일에 맞춘 식사 계획과 식재료 제공으로 음식물 쓰레기를 줄인다.  기타 역할 · 기타 운영
 4                      소량의 건강한 식재료를 통해 음식물 쓰레기를 줄인다.  거래 중개 · 기타 운영

                                           descriptor                    수익  \
 0  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...     구독 및 일회성 구매 옵션 제공
 1  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...  구독 모델 및 일회성 구매 옵션 제공
 2  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...     구독 및 일회성 구매 옵션 제공
 3  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...     구독 및 일회성 구매 옵션 제공
 4  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...     구독 및 일회성 구매 옵션 제공

                  운영
 0  요리 초보 맞춤형 서비스 운영
 1  고객 맞춤형 주문 시스템 운영
 2   고객 맞춤형 요리 키트 운영
 3   고객 맞춤형 식사 계획 운영
 4    건강한 식재료 패키지 운영  }

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,C1,C2,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, transactionModel, monetization...","businessRole, partnerModel, deliveryModel, val...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,C1,C3,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,C1,C4,DISTINCT,INTERMEDIARY:OTHER,OTHER:OTHER,"operatingModel, partnerModel, deliveryModel, t...","businessRole, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,C1,C5,DISTINCT,INTERMEDIARY:OTHER,INTERMEDIARY:OTHER,"businessRole, operatingModel, deliveryModel, t...","partnerModel, valuePropositionThesis, offerThe...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
4,C2,C3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, transactionModel...","partnerModel, deliveryModel, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
5,C2,C4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, transactionModel...","partnerModel, deliveryModel, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,C2,C5,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, partnerModel, transactionModel...","businessRole, deliveryModel, valuePropositionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,C3,C4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
8,C3,C5,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, deliveryModel, transactionMode...","businessRole, partnerModel, valuePropositionTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,C4,C5,DISTINCT,OTHER:OTHER,INTERMEDIARY:OTHER,"operatingModel, deliveryModel, transactionMode...","businessRole, partnerModel, valuePropositionTh...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.

## 26. Legal Fact Completeness + Business Design Completion + C1 Fact Pattern

In [27]:
prechecks = [engine.legal_precheck(item) for item in candidates]
display(show_legal_precheck(prechecks))
legal_preparation = await engine.prepare_legal_candidates(seed, candidates)
candidates_before_legal = candidates
candidates = legal_preparation.candidates
display({'factCompleteness': [item.model_dump(mode='json') for item in legal_preparation.reports],
         'completionAttempted': legal_preparation.completionAttempted,
         'completionValidated': legal_preparation.completionValidated,
         'completionAccepted': legal_preparation.completionAccepted,
         'completionExhausted': legal_preparation.completionExhausted,
         'excludedCandidates': legal_preparation.excludedCandidates})
display(show_legal_fact_pattern(candidates[0].candidate, seed) if candidates else [])

,candidateId,label,directSeller,intermediary,regulatedPhysicalActivity,personalDataDependency,qualificationDependency,riskHints
0,C1,Structural risk precheck — not final legal review,True,True,False,False,False,[]
1,C2,Structural risk precheck — not final legal review,True,False,False,False,False,[]
2,C3,Structural risk precheck — not final legal review,False,False,False,False,False,[]
3,C4,Structural risk precheck — not final legal review,True,False,False,False,False,[]
4,C5,Structural risk precheck — not final legal review,True,True,False,False,False,[]

,field,legalFact,source,authority,decision
0,platformRole,소비자와 공급자를 연결하는 플랫폼 역할,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
1,providerRole,식재료 및 레시피 제공자,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
2,sellerRole,소비자에게 판매하는 역할,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
3,intermediaryRole,소비자와 공급자 간의 중개 역할,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
4,transactionFlow,"[소비자가 앱을 통해 주문, 주문 후 1~2일 이내 배송]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
5,paymentFlow,"[구독 결제, 일회성 구매 결제]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
6,personalDataUsage,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
7,physicalActivities,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
8,partnerRequirements,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
9,qualificationRequirements,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
10,advertisingClaims,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED

## 27. Prepared Legal C1 Evidence Summary

In [28]:
legal_adapter = CurrentLegalAdapter()
legal_c1_input = legal_adapter.task_input(candidates[0].candidate, seed) if candidates else None
display({'candidateId': candidates[0].candidateId if candidates else None,
         'externalFacts': legal_c1_input['externalFactContext']['facts'] if legal_c1_input else [],
         'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'})

{'candidateId': 'C1',
 'externalFacts': [],
 'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'}

## 28. Full Evidence Judgment — C1 Staged Smoke

In [29]:
RUN_FULL_LEGAL_C1 = True  # staged LIVE 확인 후 True
legal_one = None
if RUN_FULL_LEGAL_C1 and candidates:
    try:
        legal_one = await engine.review_legal_candidate(seed, candidates[0])
        display(show_legal_result([legal_one]))
    except Exception:
        display(show_legal_failure(candidates[0].candidateId, engine.gateway))
else:
    print('SKIPPED — RUN_FULL_LEGAL_C1=True로 명시해야 실행됩니다.')

,candidateId,route,productionStatus,source,safeSummary,requiredControls,requiredPartnersAndQualifications,requiredDisclosures,prohibitedVariants,evidenceCount,evidenceRefs,evidenceDiagnostics
0,C1,REDESIGN_WITHIN_LINEAGE,REDESIGNABLE,OFFICIAL_EVIDENCE,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,[],[],[],[],16,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...",{}

## 29. C1 Route + Staged Redesign/Compliance/Second Legal

In [30]:
c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = ([], [], [], 0, 0)
if legal_one and candidates:
    c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[:1], [legal_one])
display({'initialRoute': legal_one.route.value if legal_one else 'SKIPPED',
         'redesignRequirements': legal_one.redesignRequirements if legal_one else [],
         'recoveryReviews': [item.model_dump(mode='json') for item in c1_legal_all[1:]],
         'requiredInputs': c1_required_inputs, 'terminalCandidates': len(c1_portfolio),
         'redesigned': c1_redesigned, 'replanned': c1_replanned})

,candidateId,route,productionStatus,source,safeSummary,requiredControls,requiredPartnersAndQualifications,requiredDisclosures,prohibitedVariants,evidenceCount,evidenceRefs,evidenceDiagnostics
0,C2,REDESIGN_WITHIN_LINEAGE,REDESIGNABLE,OFFICIAL_EVIDENCE,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,[],[],[],[],16,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...",{}
1,C3,REDESIGN_WITHIN_LINEAGE,REDESIGNABLE,OFFICIAL_EVIDENCE,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,[],[],[],[],11,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...",{}
2,C4,REDESIGN_WITHIN_LINEAGE,REDESIGNABLE,OFFICIAL_EVIDENCE,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,[],[],[],[],16,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...",{}
3,C5,REDESIGN_WITHIN_LINEAGE,REDESIGNABLE,OFFICIAL_EVIDENCE,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,[],[],[],[],20,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...",{}

{'Plan Selected': 5,
 'Candidate Generated': 5,
 'Candidate Accepted': 5,
 'Legal Reviewed': 5}

## 30. Remaining 4 Legal + Exhaustive Recovery Summary

In [31]:
RUN_REMAINING_LEGAL = True
legal_remaining = []
portfolio, legal_all, required_inputs = (list(c1_portfolio), list(c1_legal_all), list(c1_required_inputs))
redesigned_count, replanned_count = c1_redesigned, c1_replanned
c1_terminal = bool(c1_portfolio or c1_required_inputs or (c1_legal_all and c1_legal_all[-1].route.value == 'SYSTEM_FAILURE'))
if RUN_REMAINING_LEGAL and c1_terminal and len(candidates) > 1:
    legal_remaining = await engine.review_legal(seed, candidates[1:])
    rest_portfolio, rest_legal, rest_inputs, rest_redesigned, rest_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[1:], legal_remaining)
    portfolio += rest_portfolio; legal_all += rest_legal; required_inputs += rest_inputs
    redesigned_count += rest_redesigned; replanned_count += rest_replanned
else:
    print('SKIPPED — C1이 정상 terminal에 도달한 후 remaining Legal을 실행합니다.')
legal_initial = ([legal_one] if legal_one else []) + legal_remaining
display({'recoveryTrace': [item.model_dump(mode='json') for item in legal_all
                           if item.candidateId not in {x.candidateId for x in legal_initial}],
         'requiredInputs': required_inputs, 'metrics': engine._legal_metrics})
print({'Plan Selected': len(selected_plans),
       'Candidate Generated': candidate_preparation.candidateGenerated,
       'Candidate Accepted': len(candidates),
       'Legal Accepted': sum(item.route.value == 'ACCEPT' for item in legal_all),
       'Legal Redesigned': redesigned_count, 'Legal Replanned': replanned_count,
       'Final Portfolio': len(portfolio)})

{'Plan Selected': 5, 'Candidate Generated': 5, 'Candidate Accepted': 5, 'Legal Accepted': 0, 'Legal Redesigned': 0, 'Legal Replanned': 0, 'Final Portfolio': 0}

## 31. Replan

In [32]:
display(show_replan(type('PortfolioView', (), {'concepts': portfolio})()))
print({'replanned': replanned_count, 'reserveAvailable': len(reserve_plans)})

Empty DataFrame
Columns: []
Index: []

{'replanned': 0, 'reserveAvailable': 2}

## 32. Final Portfolio

In [33]:
legal_terminal_status = ('READY' if portfolio else
    'LEGAL_RECOVERY_COMPLETE_NO_ACCEPTED_CANDIDATE' if legal_initial and len(legal_initial) == len(candidates)
    else 'LEGAL_PENDING')
display(show_final_portfolio(type('PortfolioView', (), {'concepts': portfolio})()) if portfolio else {'status': legal_terminal_status})

{'status': 'LEGAL_PENDING'}

## 33. Unresolved Candidate Summary

In [34]:
display(required_inputs if required_inputs else {'unresolved': []})

{'unresolved': []}

## 34. Manual Concept Selection

In [35]:
SELECTED_CANDIDATE_ID = portfolio[0].candidateId if portfolio else None  # 사용자가 수정
selected_concept = next((item for item in portfolio if item.candidateId == SELECTED_CANDIDATE_ID), None)
print({'selectedCandidateId': SELECTED_CANDIDATE_ID})

{'selectedCandidateId': None}

## 35. 7 Hypotheses

In [36]:
hypotheses = engine.build_or_load_current_hypothesis_contract(selected_concept) if selected_concept else []
display(show_hypotheses(hypotheses))

Empty DataFrame
Columns: []
Index: []

## 36. Confirm / Edit

In [37]:
CONFIRM_ALL_PROPOSED = True
HYPOTHESIS_EDITS = {
    # 'PRICE': '월 17,900원',
}
confirmed_hypotheses = engine.confirm_hypotheses(
    hypotheses, HYPOTHESIS_EDITS, confirm_all_proposed=CONFIRM_ALL_PROPOSED) if hypotheses else []
display(show_hypotheses(confirmed_hypotheses))

Empty DataFrame
Columns: []
Index: []

## 37. Actual Delta Legal

In [38]:
RUN_DELTA_LEGAL = True
delta_legal_result = None
if RUN_DELTA_LEGAL and selected_concept and any(h.deltaLegalRequired for h in confirmed_hypotheses):
    delta_legal_result = await engine.review_delta_legal(seed, selected_concept, confirmed_hypotheses)
    confirmed_hypotheses = engine.mark_delta_legal_reviewed(confirmed_hypotheses, delta_legal_result)
display(delta_legal_result.model_dump(mode='json') if delta_legal_result else {'status': 'NOT_REQUIRED_OR_SKIPPED'})

{'status': 'NOT_REQUIRED_OR_SKIPPED'}

## 38. Market Seed

In [39]:
handoff = None
if selected_concept and legal_all:
    handoff = engine.build_downstream_handoff(seed, selected_concept, confirmed_hypotheses, legal_all)
display(handoff.marketAnalysisSeedSnapshot if handoff else {'status': 'NOT_READY'})

{'status': 'NOT_READY'}

## 39. Marketing Source

In [40]:
display(handoff.marketingSourceSnapshot if handoff else {'status': 'NOT_READY'})

{'status': 'NOT_READY'}

## 40. Contract Compatibility

In [41]:
display(show_downstream_handoff(handoff) if handoff else {'contract': 'NOT_READY'})

{'contract': 'NOT_READY'}

## 41. Trace

In [42]:
display(show_trace(engine.trace))

,순서,시각,stage,action,entity,parent,status,mode,호출,요약,decision,reasonCode
0,1,2026-08-10T00:12:27.630898+00:00,CREATED,CREATED,NaN,NaN,RUNNING,LIVE,NaN,V2 Lab 실행을 생성했습니다.,NaN,NaN
1,2,2026-08-10T00:12:32.438772+00:00,SAFETY_CHECKING,IDEA_BRIEF_DERIVED,NaN,NaN,PASS,LIVE,1.0,Idea interpretation/readiness를 보존했습니다: READY_F...,NaN,NaN
2,3,2026-08-10T00:12:32.438796+00:00,SAFETY_CHECKING,READINESS_INCONSISTENT,NaN,NaN,WARNING,LIVE,NaN,READY_FOR_REVIEW이지만 score=0입니다. V2 gating은 막지 ...,READINESS_INCONSISTENT,NaN
3,4,2026-08-10T00:12:32.508904+00:00,SEED_ANALYZING,ANALYZED,lab-idea-brief,NaN,PASS,LIVE,NaN,필수 3개와 LOCK 3개를 분류했습니다.,NaN,NaN
4,5,2026-08-10T00:12:32.509154+00:00,SEED_ANALYZING,DESIGN_SPACE_READY,NaN,NaN,PASS,LIVE,NaN,Open=11 Constrained=0 Breadth=EXPLORE,NaN,NaN
5,6,2026-08-10T00:12:32.568279+00:00,PLANNING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,최대 5개 동적 plan을 요청합니다.,NaN,NaN
6,7,2026-08-10T00:12:58.652230+00:00,PLANNING,DRAFTS_GENERATED,NaN,NaN,PASS,LIVE,2.0,Plan draft pool=7,NaN,NaN
7,8,2026-08-10T00:12:58.654566+00:00,PLANNING,NORMALIZED,NaN,NaN,PASS,LIVE,NaN,System metadata를 부여한 Plan=7,NaN,NaN
8,9,2026-08-10T00:13:06.555897+00:00,PLANNING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,3.0,low-confidence Plan architecture 7개를 batch 분류했...,NaN,NaN
9,10,2026-08-10T00:13:06.555928+00:00,PLAN_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Opportunity·LOCK·DUPLICATE/VARIANT/DISTINCT 관계...,NaN,NaN
10,11,2026-08-10T00:13:15.288606+00:00,PLAN_VALIDATING,SELECTED,NaN,NaN,PASS,LIVE,NaN,Plans=5 Rejected=0,NaN,NaN
11,12,2026-08-10T00:13:24.704486+00:00,EXPANDING,EXPANDED,C1,P7,PASS,LIVE,8.0,P7 → C1,NaN,NaN
12,13,2026-08-10T00:13:33.022309+00:00,EXPANDING,EXPANDED,C2,P1,PASS,LIVE,9.0,P1 → C2,NaN,NaN
13,14,2026-08-10T00:13:41.325899+00:00,EXPANDING,EXPANDED,C3,P3,PASS,LIVE,10.0,P3 → C3,NaN,NaN
14,15,2026-08-10T00:13:49.599808+00:00,EXPANDING,EXPANDED,C4,P4,PASS,LIVE,11.0,P4 → C4,NaN,NaN
15,16,2026-08-10T00:13:57.266651+00:00,EXPANDING,EXPANDED,C5,P5,PASS,LIVE,12.0,P5 → C5,NaN,NaN
16,17,2026-08-10T00:13:57.345799+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
17,18,2026-08-10T00:14:03.395457+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,13.0,low-confidence Candidate architecture 5개를 batc...,NaN,NaN
18,19,2026-08-10T00:14:03.395906+00:00,CANDIDATE_VALIDATING,VALIDATED,C1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
19,20,2026-08-10T00:14:03.396421+00:00,CANDIDATE_VALIDATING,VALIDATED,C2,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
20,21,2026-08-10T00:14:03.396743+00:00,CANDIDATE_VALIDATING,FIDELITY_AMBIGUOUS,C3,NaN,RUNNING,LIVE,NaN,lexical 판정이 불확실해 semantic fidelity를 요청합니다.,NaN,CANDIDATE_FIDELITY_RECOVERABLE
21,22,2026-08-10T00:14:05.920256+00:00,CANDIDATE_VALIDATING,SEMANTIC_FIDELITY_CHECKED,C3,NaN,PASS,LIVE,14.0,"개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스로, 요리의 접근성을 높이고...",PASS,NaN
22,23,2026-08-10T00:14:05.920572+00:00,CANDIDATE_VALIDATING,VALIDATED,C3,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
23,24,2026-08-10T00:14:05.921267+00:00,CANDIDATE_VALIDATING,VALIDATED,C4,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
24,25,2026-08-10T00:14:05.921935+00:00,CANDIDATE_VALIDATING,VALIDATED,C5,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
25,26,2026-08-10T00:14:05.921987+00:00,CANDIDATE_VALIDATING,CANDIDATE_PORTFOLIO_READY,NaN,NaN,PASS,LIVE,NaN,"Candidate Portfolio=5/5, recovered=0",READY_FULL,NaN
26,27,2026-08-10T00:14:29.970222+00:00,LEGAL_REVIEWING,REVIEWED,C1,NaN,REDESIGN_WITHIN_LINEAGE,LIVE,15.0,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,REDESIGN_WITHIN_LINEAGE,NaN
27,28,2026-08-10T00:14:30.000638+00:00,LEGAL_REVIEWING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,공식 Legal contract route를 실행합니다.,NaN,NaN
28,29,2026-08-10T00:14:40.880758+00:00,LEGAL_REVIEWING,REVIEWED,C2,NaN,REDESIGN_WITHIN_LINEAGE,LIVE,16.0,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,REDESIGN_WITHIN_LINEAGE,NaN
29,30,2026-08-10T00:14:51.072535+00:00,LEGAL_REVIEWING,REVIEWED,C3,NaN,REDESIGN_WITHIN_LINEAGE,LIVE,17.0,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,REDESIGN_WITHIN_LINEAGE,NaN
30,31,2026-08-10T00:15:03.351190+00:00,LEGAL_REVIEWING,REVIEWED,C4,NaN,REDESIGN_WITHIN_LINEAGE,LIVE,18.0,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,REDESIGN_WITHIN_LINEAGE,NaN
31,32,2026-08-10T00:15:18.827998+00:00,LEGAL_REVIEWING,REVIEWED,C5,NaN,REDESIGN_WITHIN_LINEAGE,LIVE,19.0,법률검토 전에 Concept의 사업 구조를 보완해야 합니다.,REDESIGN_WITHIN_LINEAGE,NaN
32,33,2026-08-10T00:15:18.869893+00:00,LEGAL_RECOVERING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Legal route별 복구를 수행합니다.,NaN,NaN
33,34,2026-08-10T00:15:25.847389+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
34,35,2026-08-10T00:15:28.961459+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,21.0,low-confidence Candidate architecture 1개를 batc...,NaN,NaN
35,36,2026-08-10T00:15:28.961971+00:00,CANDIDATE_VALIDATING,VALIDATED,C1-R1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
36,37,2026-08-10T00:15:48.772871+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
37,38,2026-08-10T00:15:51.763004+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,24.0,low-confidence Candidate architecture 1개를 batc...,NaN,NaN
38,39,2026-08-10T00:15:51.763520+00:00,CANDIDATE_VALIDATING,VALIDATED,C2-R1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
39,40,2026-08-10T00:16:12.145460+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
40,41,2026-08-10T00:16:16.597076+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,27.0,low-confidence Candidate architecture 1개를 batc...,NaN,NaN
41,42,2026-08-10T00:16:16.597472+00:00,CANDIDATE_VALIDATING,FIDELITY_AMBIGUOUS,C3-R1,NaN,RUNNING,LIVE,NaN,lexical 판정이 불확실해 semantic fidelity를 요청합니다.,NaN,CANDIDATE_FIDELITY_RECOVERABLE
42,43,2026-08-10T00:16:18.743772+00:00,CANDIDATE_VALIDATING,SEMANTIC_FIDELITY_CHECKED,C3-R1,NaN,PASS,LIVE,28.0,"개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스로, 1~2인 가구의 음식물...",PASS,NaN
43,44,2026-08-10T00:16:18.743812+00:00,CANDIDATE_VALIDATING,VALIDATED,C3-R1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
44,45,2026-08-10T00:16:49.090489+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
45,46,2026-08-10T00:16:51.929447+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,31.0,low-confidence Candidate architecture 1개를 batc...,NaN,NaN
46,47,2026-08-10T00:16:51.930055+00:00,CANDIDATE_VALIDATING,VALIDATED,C4-R1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
47,48,2026-08-10T00:17:09.989821+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
48,49,2026-08-10T00:17:12.444581+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,34.0,low-confidence Candidate architecture 1개를 batc...,NaN,NaN
49,50,2026-08-10T00:17:12.445024+00:00,CANDIDATE_VALIDATING,VALIDATED,C5-R1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN

## 42. Provider/Legal Usage

In [43]:
display(show_provider_usage(engine.gateway.usage))
print('상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.')

,논리 작업,상위 외부 작업,논리 stage별,상위 외부 작업 stage별,재시도,소요(ms),모드별,token,보고 비용
0,35,35,"{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...","{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...",0,304806,{'LIVE': 35},None,None

상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.

## 43. Replay Manifest

In [44]:
display(show_replay_manifest(engine.gateway))

{'status': 'REPLAY_PARTIAL',
 'entries':                   operation  \
 0                 PLAN_POOL
 1         SEMANTIC_RELATION
 2     IDEA_BRIEF_DERIVATION
 3              LEGAL_REVIEW
 4              LEGAL_REVIEW
 5                    EXPAND
 6              LEGAL_REVIEW
 7   NORMALIZE_ARCHITECTURES
 8   NORMALIZE_ARCHITECTURES
 9                    EXPAND
 10                   EXPAND
 11             LEGAL_REVIEW
 12             LEGAL_REVIEW
 13  NORMALIZE_ARCHITECTURES
 14                   EXPAND
 15                   EXPAND
 16                   EXPAND
 17  NORMALIZE_ARCHITECTURES
 18                   EXPAND
 19  NORMALIZE_ARCHITECTURES
 20        SEMANTIC_RELATION
 21  NORMALIZE_ARCHITECTURES
 22  NORMALIZE_ARCHITECTURES
 23             LEGAL_REVIEW
 24                   EXPAND
 25                   EXPAND
 26        SEMANTIC_RELATION
 27                 REDESIGN
 28             LEGAL_REVIEW
 29                   EXPAND
 30             LEGAL_REVIEW
 31                   EXPAND
 32                PLAN_POOL
 33                   EXPAND
 34                 REDESIGN
 35                 REDESIGN
 36                PLAN_POOL
 37            PLAN_FIDELITY
 38             LEGAL_REVIEW
 39             LEGAL_REVIEW
 40                   EXPAND
 41                PLAN_POOL
 42                   EXPAND
 43        SEMANTIC_RELATION
 44        SEMANTIC_RELATION
 45                 REDESIGN
 46                   EXPAND
 47                 REDESIGN
 48                   EXPAND

                                                  hash operationVersion  \
 0   03b73ea7d485636893670a848e28d49e239cc8bc0c5239...             v2.1
 1   05680e1eabb667cd53d8bbde75192650b626fd5dfaa3fd...               v3
 2   07c6209c7795158bce16bf1d386c8f6cd1322277337ef9...               v2
 3   114572fe54444de15af5f070a0267a87cb9af640574242...               v3
 4   192b70f6f311c55224b0542e7bec6c3208f30fb9b0b5ea...               v3
 5   1af5fde74ee67196097d4ed11be725ac3964b73a8255f9...              NaN
 6   238d8ea9130a116b2ac7a3ffeb8dc77f6ec9ea61ced881...               v3
 7   24508ed8af4adcbc77e6350b2a140f55cee08faf1af73d...               v1
 8   2697fb8bfac3768d3773bab4038567ff44d6efd2967ad0...               v1
 9   2cefb5e202d4c20d4c7d7c8fae69e3a36509850c74fd33...               v3
 10  3c5d54226c8e1dc67a781ee23b621f351adc0856e1bf95...               v3
 11  3e1929a4545c4514ef7b1cdc29c46cbb89a806ea085c4c...               v3
 12  4fa93b3636ea3d3ae88a5aa557cab8b402cf99c9ccf250...               v3
 13  5150bed8fa31612ccb123669f410b22a95d731a247a09e...               v1
 14  556e5f98f2df8637dba833e5db9fd4ec8c15636afcd164...               v3
 15  56691ac0644f2037ba4073abb93e5c41db18feb2695b74...               v3
 16  5ea7858cc4a88f9b3cf7f584ca6c4ef6ffd65b9825722d...              NaN
 17  5f252fc394106444d333dcb4bdba8f2c44309d0a681795...               v1
 18  61d2d7d5e82b70244be247aaf3fd19143faf7374f2b5d2...               v3
 19  64304f735b0cd3931eb54e30bbe6b881c003007d288415...               v1
 20  73c739015a32c2d75f20a567513dc7b995792049b26fbc...               v3
 21  74971afbd222a2e2ae8fd739e8acdf57b97a3bbe26b475...               v1
 22  7bd1694be75767e750398c914f88ba3b982666c86ad84a...               v1
 23  7dd57a2c756921ec86a38edb08f5e21c54b2303b78e9cc...               v3
 24  803c35256a386c06a427b5dc9bec4638ecdb98007a597c...               v3
 25  8153e8981bf092861864149480a7a14306dd5747ae563f...             v2.1
 26  8451ca960b88c7e00400bc7d746482f7faeb58ab1d6a0e...               v3
 27  867ea4b6eea58d4a26ff6f84b0fa60ee7d9fdce72dfd68...               v3
 28  90871ce449b5425f63a95e54780a698947a5a7427640ac...               v3
 29  945dade2f5ba6344e63dfed5e609ecf02c92ae92a51ad2...              NaN
 30  94e5989fd9e5545f34cfb9ec06002b5bed2917dcf4e6c5...               v3
 31  9f1396fec8ea20c3c32e9c46d343e153d671147c2ad81e...               v3
 32  a176f97804a370f8d668c37d27f5c797f7d759f979d119...               v3
 33  a1c06aec125f601725e120c8765675e340d7f09b94db4a...               v3
 34  a53386a713a88ed0a61f7befa2b9697b8f09de4d4f515b...               v3
 35  a5f2b250a000be57e21b2f207064620c64195b560f6446...               v3
 36  a77ef8dfd8e946c2ce16a423408fc787216aa72ccd38ee...               v3
 37  a9ee8b1df94e56e7372f464808003743530b98b5013e90...               v3
 38  ac895dab47216dee9f98d536f7b30d2f884ede1ea48adc...               v3
 39  b05f0c5d8b24067bc9739664e454d91b1fc4d7e47ae620...               v3
 40  b516afbff977d7ecd1fcd44e75f12adff0757b4ea82569...               v3
 41  c98df36191fe679624cf311dd5e671864c0bdedd03a338...              NaN
 42  d2aa5afd9111547a50e0ec850d3f40f68f2b64ebdcdf57...              NaN
 43  d40aa9fe13dc975293c1a92b582e3d0ddaca0c5ea40f15...               v3
 44  def5fa41adbaa2fa2ba6effd3407d9e10232a0447a9ea1...               v3
 45  e1f00b4299a6f184485ef2e095448c90d70b545e62eeb2...               v3
 46  fa3806ec6a088c6605461f5c94b877d4038d6d51a2faa2...               v3
 47  fb3d9fe4d14b27f3087a013761b18ba1d2e7b680c90c17...               v3
 48  fb6986c6b42d538d7e6633cd0b5e8695331b5eab5748d2...              NaN

                                    promptVersion schemaVersion  recordExists  \
 0                    concept-portfolio-plan-v2.1           2.0          True
 1                  concept-portfolio-relation-v3           2.0          True
 2                          idea-brief-current-v2           2.0          True
 3                        concept-legal-review-v3           2.0          True
 4                        concept-legal-review-v3           2.0          True
 5                                            NaN           2.0          True
 6                        concept-legal-review-v3           2.0          True
 7   concept-portfolio-architecture-classifier-v1           2.0          True
 8   concept-portfolio-architecture-classifier-v1           2.0          True
 9         concept-portfolio-generic-candidate-v3           2.0          True
 10        concept-portfolio-generic-candidate-v3           2.0          True
 11                       concept-legal-review-v3           2.0          True
 12                       concept-legal-review-v3           2.0          True
 13  concept-portfolio-architecture-classifier-v1           2.0          True
 14        concept-portfolio-generic-candidate-v3           2.0          True
 15        concept-portfolio-generic-candidate-v3           2.0          True
 16                                           NaN           2.0          True
 17  concept-portfolio-architecture-classifier-v1           2.0          True
 18        concept-portfolio-generic-candidate-v3           2.0          True
 19  concept-portfolio-architecture-classifier-v1           2.0          True
 20                 concept-portfolio-relation-v3           2.0          True
 21  concept-portfolio-architecture-classifier-v1           2.0          True
 22  concept-portfolio-architecture-classifier-v1           2.0          True
 23                       concept-legal-review-v3           2.0          True
 24        concept-portfolio-generic-candidate-v3           2.0          True
 25              concept-portfolio-candidate-v2.1           2.0          True
 26                 concept-portfolio-relation-v3           2.0          True
 27                           concept-redesign-v3           2.0          True
 28                       concept-legal-review-v3           2.0          True
 29                                           NaN           2.0          True
 30                       concept-legal-review-v3           2.0          True
 31        concept-portfolio-generic-candidate-v3           2.0          True
 32             concept-portfolio-generic-plan-v3           2.0          True
 33        concept-portfolio-generic-candidate-v3           2.0          True
 34                           concept-redesign-v3           2.0          True
 35                           concept-redesign-v3           2.0          True
 36             concept-portfolio-generic-plan-v3           2.0          True
 37                 concept-portfolio-fidelity-v3           2.0          True
 38                       concept-legal-review-v3           2.0          True
 39                       concept-legal-review-v3           2.0          True
 40        concept-portfolio-generic-candidate-v3           2.0          True
 41                                           NaN           2.0          True
 42                                           NaN           2.0          True
 43                 concept-portfolio-relation-v3           2.0          True
 44                 concept-portfolio-relation-v3           2.0          True
 45                           concept-redesign-v3           2.0          True
 46        concept-portfolio-generic-candidate-v3           2.0          True
 47                           concept-redesign-v3           2.0          True
 48                                           NaN           2.0          True

                            timestamp  versionCompatible
 0   2026-08-09T22:07:18.877351+00:00               True
 1   2026-08-09T23:08:53.044335+00:00               True
 2   2026-08-10T00:12:32.437097+00:00               True
 3   2026-08-10T00:14:29.968514+00:00               True
 4   2026-08-10T00:17:02.167808+00:00               True
 5   2026-08-09T15:57:26.931257+00:00              False
 6   2026-08-10T00:15:03.349877+00:00               True
 7   2026-08-10T00:14:03.394446+00:00               True
 8   2026-08-10T00:15:51.762107+00:00               True
 9   2026-08-10T00:13:33.018574+00:00               True
 10  2026-08-09T23:09:22.421630+00:00               True
 11  2026-08-10T00:17:33.166595+00:00               True
 12  2026-08-10T00:16:42.275890+00:00               True
 13  2026-08-10T00:15:28.960466+00:00               True
 14  2026-08-10T00:13:49.598691+00:00               True
 15  2026-08-09T23:09:15.058753+00:00               True
 16  2026-08-09T15:56:56.379364+00:00              False
 17  2026-08-10T00:16:16.596259+00:00               True
 18  2026-08-10T00:13:41.324510+00:00               True
 19  2026-08-10T00:17:12.443620+00:00               True
 20  2026-08-10T00:13:15.278487+00:00               True
 21  2026-08-10T00:16:51.918768+00:00               True
 22  2026-08-10T00:13:06.555033+00:00               True
 23  2026-08-10T00:16:05.327426+00:00               True
 24  2026-08-09T23:09:00.553826+00:00               True
 25  2026-08-09T22:07:26.091646+00:00               True
 26  2026-08-10T00:13:10.742008+00:00               True
 27  2026-08-10T00:16:49.089000+00:00               True
 28  2026-08-10T00:14:51.071761+00:00               True
 29  2026-08-09T15:57:33.741497+00:00              False
 30  2026-08-10T00:14:40.879824+00:00               True
 31  2026-08-09T23:09:07.793971+00:00               True
 32  2026-08-10T00:12:58.650557+00:00               True
 33  2026-08-10T00:13:57.264661+00:00               True
 34  2026-08-10T00:17:09.987729+00:00               True
 35  2026-08-10T00:15:25.845715+00:00               True
 36  2026-08-09T23:08:50.513875+00:00               True
 37  2026-08-10T00:16:18.743013+00:00               True
 38  2026-08-10T00:15:18.826589+00:00               True
 39  2026-08-10T00:15:43.215665+00:00               True
 40  2026-08-09T23:09:28.844031+00:00               True
 41  2026-08-09T15:55:40.653020+00:00              False
 42  2026-08-09T15:57:21.293137+00:00              False
 43  2026-08-10T00:13:12.939041+00:00               True
 44  2026-08-10T00:13:08.753038+00:00               True
 45  2026-08-10T00:16:12.143934+00:00               True
 46  2026-08-10T00:13:24.693228+00:00               True
 47  2026-08-10T00:15:48.771228+00:00               True
 48  2026-08-09T15:57:14.211269+00:00              False  }

## 44. One-click MOCK

In [45]:
mock_result = await ConceptPortfolioEngine('MOCK').run_full(
    TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=True)
display(show_run_summary(mock_result))
assert mock_result.handoff and mock_result.handoff.contractStatus == 'CONTRACT_PASS'

,safety,requestedMaximum,planned,planDuplicatesRemoved,candidatesExpanded,candidateGenerated,candidateAcceptedInitially,candidateRegenerated,candidateRecovered,reservePlansActivated,candidateRecoveryReplans,legalAccepted,legalRedesigned,replanned,finalPortfolio,portfolioStatus,selectedConcept,downstreamHandoff,providerCalls,totalDurationMs
0,PASS,5,7,0,5,5,5,0,0,0,0,5,0,0,5,READY_FULL,직접 운영 핵심형,PASS,0,52

## 45. One-click REPLAY

In [46]:
RUN_ONE_CLICK_REPLAY = False
replay_result = None
if RUN_ONE_CLICK_REPLAY:
    replay_gateway = ProviderGateway('REPLAY', recordings_dir=RECORDINGS_DIR)
    replay_result = await ConceptPortfolioEngine('REPLAY', gateway=replay_gateway).run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=False)
display(show_run_summary(replay_result) if replay_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}

## 46. One-click LIVE

In [47]:
RUN_ONE_CLICK_LIVE = False
live_result = None
if RUN_ONE_CLICK_LIVE:
    assert MODE == 'LIVE', 'MODE=LIVE를 먼저 명시하세요.'
    assert RUN_FULL_LEGAL_C1 and RUN_REMAINING_LEGAL, 'staged LIVE Legal 확인이 먼저입니다.'
    live_result = await engine.run_full(TEST_INPUT, max_concepts=MAX_CONCEPTS,
                                        auto_confirm_hypotheses=False)
display(show_run_summary(live_result) if live_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}