## 00. Quick Start

In [1]:
print('Concept Portfolio V2 Lab — 기본 MODE는 MOCK입니다.')
print('LIVE는 06→28 순서의 staged 검증 후 46의 가드를 직접 켜야 합니다.')

Concept Portfolio V2 Lab — 기본 MODE는 MOCK입니다.
LIVE는 06→28 순서의 staged 검증 후 46의 가드를 직접 켜야 합니다.

## 01. Environment

In [2]:
import os, sys, json
from pathlib import Path
from IPython.display import display
SEARCH_ROOTS = [Path.cwd(), *Path.cwd().parents]
AI_ROOT = next((p for p in SEARCH_ROOTS if (p / 'app').is_dir()), None)
if AI_ROOT is None: AI_ROOT = next((p / 'ai' for p in SEARCH_ROOTS if (p / 'ai' / 'app').is_dir()))
if str(AI_ROOT) not in sys.path: sys.path.insert(0, str(AI_ROOT))
print({'python': sys.version.split()[0], 'aiRoot': str(AI_ROOT)})

{'python': '3.14.5', 'aiRoot': 'C:\\Users\\seewo\\Desktop\\big_proj_01\\new_3\\ai'}

## 02. MODE

In [3]:
MODE = 'LIVE'  # MOCK | REPLAY | LIVE
RECORDINGS_DIR = AI_ROOT / 'recordings' / 'concept_portfolio_v2'
print({'mode': MODE, 'liveExternalOperationsEnabled': MODE == 'LIVE'})

{'mode': 'LIVE', 'liveExternalOperationsEnabled': True}

## 03. Environment Check

In [4]:
LIVE_ENV_KEYS = ['AI_PROVIDER', 'AI_API_KEY', 'AI_MODEL', 'MOLEG_API_KEY', 'LEGAL_REGISTRY_VERSION']
env_status = {key: bool(os.getenv(key)) for key in LIVE_ENV_KEYS}
print(env_status if MODE == 'LIVE' else {'mode': MODE, 'message': '외부 환경변수 불필요'})

{'AI_PROVIDER': True, 'AI_API_KEY': True, 'AI_MODEL': True, 'MOLEG_API_KEY': True, 'LEGAL_REGISTRY_VERSION': True}

## 04. Schema Preflight

In [5]:
from app.concept_portfolio_v2 import ConceptPortfolioEngine, ProviderGateway, ProviderMode
from app.concept_portfolio_v2.adapters import CurrentLegalAdapter
from app.concept_portfolio_v2.diagnostics.notebook_view import *
gateway = ProviderGateway(MODE, recordings_dir=RECORDINGS_DIR)
engine = ConceptPortfolioEngine(MODE, gateway=gateway)
schema_preflight = engine.schema_preflight_report()
display(show_schema_preflight(schema_preflight))
assert schema_preflight.status == 'PASS' and schema_preflight.providerCalls == 0

                          스키마    상태  실패  Provider 호출
0               PlanDraftPool  PASS  []            0
1       ConceptCandidateDraft  PASS  []            0
2  SemanticDistinctnessResult  PASS  []            0
3      SemanticFidelityResult  PASS  []            0
4   SemanticArchitectureBatch  PASS  []            0

## 05. Input

In [6]:
TEST_INPUT = {
    'ideaOverview': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
    'problem': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다',
    'targetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
}
MAX_CONCEPTS = 5

## 06. Idea Brief Derivation

In [7]:
engine._reset()
seed = engine.seed_adapter.adapt(TEST_INPUT)
idea_context = await engine.derive_idea_brief(seed)
print({'ideaCallComplete': True, 'interpretationPresent': bool(seed.interpretation)})

{'ideaCallComplete': True, 'interpretationPresent': True}

## 07. Safety

In [8]:
display(idea_context.safetyReview.model_dump(mode='json'))
assert idea_context.safetyReview.passed

{'decision': 'ALLOW',
 'categories': [],
 'restrictions': [],
 'userFacingReason': '이 아이디어는 안전하며, 개인 맞춤형 식재료 제공과 관련된 문제를 해결하는 데 기여할 수 있습니다.'}

## 08. AI가 이해한 아이디어

In [9]:
display(show_idea_interpretation(idea_context))

                               항목                                 AI 이해 결과
0              interpretedProblem  1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.
1          interpretedTargetUsers           요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.
2                    usageContext  소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.
3                industryCategory                              식품 및 요리 서비스
4                   researchScope           소량 식재료 및 레시피 제공 서비스에 대한 시장 조사.
5           conciseIdeaDefinition         개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.
6      targetRegionInterpretation                     특정 지역에 대한 정보가 필요합니다.
7  relevantKnownCompetitorContext                       경쟁자에 대한 정보가 필요합니다.

## 09. Readiness / Summary / commitments

In [10]:
display(show_idea_readiness(idea_context))

{'readiness': {'status': 'READY_FOR_REVIEW',
  'score': 0,
  'missingFieldKeys': []},
 'readinessDiagnostic': 'READINESS_INCONSISTENT',
 'userFacingSummary': '이 서비스는 개인 맞춤형 소량 식재료를 제공하고, 남은 재료를 활용할 수 있는 레시피를 안내하여 1~2인 가구의 음식물 쓰레기 문제를 해결하는 데 도움을 줄 수 있습니다.',
 'commitmentCandidates': [],
 'contradictions': [],
 'questions': []}

## 10. Seed Analysis

In [11]:
analysis = await engine.analyze_seed(seed)
display(show_seed_analysis(analysis))

        구분                                                  값
0     탐색 폭                                            EXPLORE
1  다양성 수용량                                                  5
2       설명  선택 입력 LOCK 0개로 11개 설계 차원이 열려 있습니다. diversityCa...

## 11. Generic Opportunity Kernel

In [12]:
display(analysis.opportunityKernel.model_dump(mode='json'))

{'problemCore': '1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.',
 'targetCore': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.',
 'useContexts': ['소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.'],
 'intentComponents': ['개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.'],
 'mustPreserve': ['1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.',
  '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.',
  '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.'],
 'maySpecialize': ['핵심 대상의 의미 있는 하위 세그먼트',
  '핵심 사용 맥락의 구체화',
  '가치 제안 또는 offer의 구체화'],
 'forbiddenDriftSummary': '핵심 문제와 대상이 모두 무관한 기회로 교체되면 범위를 벗어납니다.'}

## 12. Design Space

In [13]:
display(show_design_space(analysis))

,분류,필드,값
0,SOURCE_LOCK,ideaOverview,개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스
1,SOURCE_LOCK,problem,1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다
2,SOURCE_LOCK,targetUsers,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구
3,SEMANTIC_ANCHOR,ideaOverview,개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스
4,SEMANTIC_ANCHOR,problem,1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다
5,SEMANTIC_ANCHOR,targetUsers,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구
6,OPEN,solutionMechanism,변경 가능
7,OPEN,valueDelivery,변경 가능
8,OPEN,operatingModel,변경 가능
9,OPEN,supplyStructure,변경 가능
10,OPEN,partnerModel,변경 가능
11,OPEN,transactionFlow,변경 가능
12,OPEN,fulfillment,변경 가능
13,OPEN,platformRole,변경 가능
14,OPEN,commercialFlow,변경 가능
15,OPEN,dataDependency,변경 가능
16,OPEN,physicalDependency,변경 가능

## 13. Generate and Adaptively Replenish Plan Pool

In [14]:
plan_validation = await engine.prepare_portfolio_plans(seed, analysis, max_concepts=MAX_CONCEPTS)
plans = engine._last_plan_pool
print({'totalPlans': len(plans), 'planningRounds': plan_validation.planningRounds,
       'replenishmentRequested': plan_validation.replenishmentRequested})

{'totalPlans': 6, 'planningRounds': 1, 'replenishmentRequested': 0}

## 14. Plan Count / Adaptive Replenishment Check

In [15]:
display(show_plan_pool_status(engine._last_plan_pool_status))
display({'planningRounds': plan_validation.planningRounds,
         'replenishmentRequested': plan_validation.replenishmentRequested,
         'adaptiveReplenishmentUsed': plan_validation.planningRounds > 1})

,requestedPoolSize,returnedPoolSize,initialTarget,reserveTarget,reserveAvailable,status
0,7,6,5,2,1,RESERVE_SHORTFALL

{'planningRounds': 1,
 'replenishmentRequested': 0,
 'adaptiveReplenishmentUsed': False}

## 15. Korean Plan Display

In [16]:
display(show_portfolio_plans(plan_validation.acceptedPlans + plan_validation.reservePlans))

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P3,1~2인 가구 맞춤형 요리 서비스,SELECTED,0.8281,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료와 요리 레시피를 제공하여 요리를 쉽게 할 수 있도록 돕는다.,1~2인 가구에 최적화된 요리 솔루션을 제공한다.,소량 식재료와 레시피를 통해 요리의 즐거움을 제공한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 요리 문제를 해결하기 위한 혁신적인 접근 방식.
1,P1,소량 맞춤형 식재료 서비스,SELECTED,0.8207,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료를 제공하여 음식물 쓰레기를 줄이고 요리를 쉽게 할 수 있도록 ...,소량의 식재료와 활용 레시피를 통해 요리의 즐거움을 제공한다.,개인 맞춤형 식재료 패키지를 통해 1~2인 가구의 요리 문제를 해결한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 음식물 쓰레기 문제를 해결하기 위한 혁신적인 접근 방식.
2,P6,간편한 소량 식재료 제공 서비스,SELECTED,0.7309,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,간편하게 필요한 만큼의 식재료를 제공하여 요리를 쉽게 할 수 있도록 돕는다.,간편한 소량 식재료 패키지를 제공한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",간편하게 소량 식재료를 제공하여 음식물 쓰레기를 줄이는 혁신적인 서비스.
3,P2,레시피 기반 소량 식재료 서비스,SELECTED,0.5459,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,레시피에 맞춘 소량 식재료를 제공하여 요리의 편리함과 낭비를 줄인다.,레시피에 최적화된 소량 식재료 패키지를 제공한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",레시피 기반으로 소량 식재료를 제공하여 음식물 쓰레기를 줄이는 혁신적인 서비스.
4,P4,신선한 소량 식재료 배달 서비스,SELECTED,0.4659,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,신선한 소량 식재료를 제공하여 요리의 편리함과 낭비를 줄인다.,신선한 소량 식재료를 고객에게 직접 배달한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",신선한 소량 식재료를 제공하여 음식물 쓰레기를 줄이는 혁신적인 서비스.
5,P5,요리 시간 절약 소량 식재료 서비스,RESERVE,0.7059,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,요리 시간을 절약하고 음식물 쓰레기를 줄일 수 있도록 돕는다.,요리 시간 절약을 위한 소량 식재료 패키지를 제공한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리 시간을 절약하고 음식물 쓰레기를 줄이는 혁신적인 서비스.

## 16. Plan Lock/Intent Validation

In [17]:
display({'accepted': [p.planId for p in plan_validation.acceptedPlans],
         'rejected': [p.model_dump(mode='json') for p in plan_validation.rejectedPlans]})

{'accepted': ['P3', 'P1', 'P6', 'P2', 'P4'], 'rejected': []}

## 17. Portfolio Family / Variant / Distinct

In [18]:
display(show_plan_diversity(plan_validation.diversity))

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,P1,P2,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,P1,P3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,P2,P3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,P1,P4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
4,P2,P4,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...",offerThesis,MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
5,P3,P4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,P1,P5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,P2,P5,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
8,P3,P5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,P4,P5,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
10,P1,P6,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","offerThesis, solutionThesis",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
11,P2,P6,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...",valuePropositionThesis,MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
12,P3,P6,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","offerThesis, solutionThesis",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
13,P4,P6,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
14,P5,P6,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...

## 18. Selected + Reserve Plans

In [19]:
selected_plans = plan_validation.acceptedPlans
reserve_plans = plan_validation.reservePlans
display(show_portfolio_plans(selected_plans + reserve_plans))
display({'selected': [p.planId for p in selected_plans], 'reserve': [p.planId for p in reserve_plans]})

,planId,제목,선택 상태,selectionScore,selectionReason,relationToPortfolio,Concept Family,Target Thesis,Use Context,Value Thesis,Offer Thesis,Solution Thesis,Architecture,비교 가치
0,P3,1~2인 가구 맞춤형 요리 서비스,SELECTED,0.8281,Opportunity fit과 Concept clarity가 가장 높은 대표안,PORTFOLIO_SEED,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료와 요리 레시피를 제공하여 요리를 쉽게 할 수 있도록 돕는다.,1~2인 가구에 최적화된 요리 솔루션을 제공한다.,소량 식재료와 레시피를 통해 요리의 즐거움을 제공한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 요리 문제를 해결하기 위한 혁신적인 접근 방식.
1,P1,소량 맞춤형 식재료 서비스,SELECTED,0.8207,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,필요한 만큼의 식재료를 제공하여 음식물 쓰레기를 줄이고 요리를 쉽게 할 수 있도록 ...,소량의 식재료와 활용 레시피를 통해 요리의 즐거움을 제공한다.,개인 맞춤형 식재료 패키지를 통해 1~2인 가구의 요리 문제를 해결한다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",1~2인 가구의 음식물 쓰레기 문제를 해결하기 위한 혁신적인 접근 방식.
2,P6,간편한 소량 식재료 제공 서비스,SELECTED,0.7309,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,간편하게 필요한 만큼의 식재료를 제공하여 요리를 쉽게 할 수 있도록 돕는다.,간편한 소량 식재료 패키지를 제공한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",간편하게 소량 식재료를 제공하여 음식물 쓰레기를 줄이는 혁신적인 서비스.
3,P2,레시피 기반 소량 식재료 서비스,SELECTED,0.5459,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,레시피에 맞춘 소량 식재료를 제공하여 요리의 편리함과 낭비를 줄인다.,레시피에 최적화된 소량 식재료 패키지를 제공한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",레시피 기반으로 소량 식재료를 제공하여 음식물 쓰레기를 줄이는 혁신적인 서비스.
4,P4,신선한 소량 식재료 배달 서비스,SELECTED,0.4659,현재 Portfolio에 주요 사업 선택의 비교 범위를 추가,DISTINCT,기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,신선한 소량 식재료를 제공하여 요리의 편리함과 낭비를 줄인다.,신선한 소량 식재료를 고객에게 직접 배달한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",신선한 소량 식재료를 제공하여 음식물 쓰레기를 줄이는 혁신적인 서비스.
5,P5,요리 시간 절약 소량 식재료 서비스,RESERVE,0.7059,Selected Portfolio 대비 marginal value가 낮아 reser...,"DISTINCT,VARIANT",기타 역할 · 기타 운영,요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구,소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황,요리 시간을 절약하고 음식물 쓰레기를 줄일 수 있도록 돕는다.,요리 시간 절약을 위한 소량 식재료 패키지를 제공한다.,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,"{'businessRole': 'OTHER', 'operatingModel': 'O...",요리 시간을 절약하고 음식물 쓰레기를 줄이는 혁신적인 서비스.

{'selected': ['P3', 'P1', 'P6', 'P2', 'P4'], 'reserve': ['P5']}

## 19. Candidate 1

In [20]:
candidate_one = await engine.expand_plan(seed, selected_plans[0], 1) if selected_plans else None
display(show_candidates([candidate_one]) if candidate_one else [])

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,1~2인 가구 맞춤형 요리 서비스,"고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하고, 남은 재료를 활용할 수 ...",기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.

## 20. Candidate 1 Korean/Governance

In [21]:
candidate_one_reports = []
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'status': 'PENDING_FULL_CANDIDATE_RECOVERY'})

{'candidateId': 'C1', 'status': 'PENDING_FULL_CANDIDATE_RECOVERY'}

## 21. Candidate 1 Actual Generic Descriptor

In [22]:
display(show_concept_descriptors([candidate_one]) if candidate_one else [])

,entityId,family,dimension,code,confidence,source
0,C1,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
1,C1,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
2,C1,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
3,C1,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
4,C1,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
5,C1,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
6,C1,OTHER:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
7,C1,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
8,C1,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN

## 22. Candidate 1 Fidelity

In [23]:
display({'candidateId': candidate_one.candidateId if candidate_one else None,
         'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'})

{'candidateId': 'C1',
 'fidelity': '전체 Candidate Recovery 단계에서 semantic fallback 포함 검증'}

## 23. Remaining Candidates

In [24]:
remaining_candidates = []
for i, plan in enumerate(selected_plans[1:], 2):
    remaining_candidates.append(await engine.expand_plan(seed, plan, i))
candidate_drafts = ([candidate_one] if candidate_one else []) + remaining_candidates
display(show_candidates(candidate_drafts))

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,1~2인 가구 맞춤형 요리 서비스,"고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하고, 남은 재료를 활용할 수 ...",기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
1,C2,L2,None,소량 맞춤형 식재료 서비스,개인 맞춤형 식재료 패키지를 통해 1~2인 가구의 요리 문제를 해결합니다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
2,C3,L3,None,간편한 소량 식재료 제공 서비스,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
3,C4,L4,None,레시피 기반 소량 식재료 서비스,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,레시피에 따라 필요한 식재료를 조합하여 제공한다.
4,C5,L5,None,신선한 소량 식재료 배달 서비스,고객 맞춤형 식재료 패키지를 제공하여 요리 스타일에 맞춘 소량의 재료를 배송한다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.

## 24. Candidate Actual Generic Descriptors

In [25]:
display(show_concept_descriptors(candidate_drafts))

,entityId,family,dimension,code,confidence,source
0,C1,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
1,C1,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
2,C1,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
3,C1,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
4,C1,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
5,C1,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
6,C1,OTHER:OTHER,customerInteractionModel,OTHER,LOW,UNKNOWN
7,C1,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
8,C1,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN
9,C2,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
10,C2,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
11,C2,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
12,C2,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
13,C2,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
14,C2,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
15,C2,OTHER:OTHER,customerInteractionModel,APP,HIGH,RULE
16,C2,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
17,C2,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN
18,C3,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
19,C3,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
20,C3,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
21,C3,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
22,C3,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
23,C3,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
24,C3,OTHER:OTHER,customerInteractionModel,APP,HIGH,RULE
25,C3,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
26,C3,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN
27,C4,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
28,C4,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
29,C4,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
30,C4,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
31,C4,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
32,C4,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
33,C4,OTHER:OTHER,customerInteractionModel,APP,HIGH,RULE
34,C4,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
35,C4,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN
36,C5,OTHER:OTHER,businessRole,OTHER,LOW,UNKNOWN
37,C5,OTHER:OTHER,operatingModel,OTHER,LOW,UNKNOWN
38,C5,OTHER:OTHER,partnerModel,PARTNER_NETWORK,HIGH,RULE
39,C5,OTHER:OTHER,deliveryModel,OTHER,LOW,UNKNOWN
40,C5,OTHER:OTHER,transactionModel,OTHER,LOW,UNKNOWN
41,C5,OTHER:OTHER,monetizationModel,OTHER,LOW,UNKNOWN
42,C5,OTHER:OTHER,customerInteractionModel,APP,HIGH,RULE
43,C5,OTHER:OTHER,dataDependency,MATERIAL,NaN,NaN
44,C5,OTHER:OTHER,physicalDependency,MATERIAL,NaN,NaN

## 25. Candidate Recovery / Portfolio Relations

In [26]:
candidate_preparation = await engine.prepare_candidate_portfolio(
    seed, plan_validation, max_concepts=MAX_CONCEPTS, initial_candidates=candidate_drafts)
candidates = candidate_preparation.candidates
candidate_reports = candidate_preparation.reports
display(show_candidate_recovery(candidate_preparation))
candidate_pairwise = [engine.compare_candidates(candidates[i], candidates[j])
                      for i in range(len(candidates)) for j in range(i + 1, len(candidates))]
display(show_plan_diversity(candidate_pairwise))

{'summary':    candidateGenerated  candidateAcceptedInitially  candidateRegenerated  \
 0                   5                           5                     0

    candidateRecovered  reservePlansActivated  candidateRecoveryReplans  \
 0                   0                      0                         0

    finalCandidatePortfolio
 0                        5  ,
 'attempts':   candidateId  schemaValid  hardLockPreserved  semanticAnchorPreserved  \
 0          C1         True               True                     True
 1          C2         True               True                     True
 2          C3         True               True                     True
 3          C4         True               True                     True
 4          C5         True               True                     True

    planFidelity anchorDecision fidelityDecision  contentLanguageValid  \
 0          True           PASS             PASS                  True
 1          True           PASS          ADAPTED                  True
 2          True           PASS          ADAPTED                  True
 3          True           PASS          ADAPTED                  True
 4          True           PASS          ADAPTED                  True

    accepted   outcome  semanticFidelityUsed  \
 0      True  ACCEPTED                  True
 1      True  ACCEPTED                 False
 2      True  ACCEPTED                 False
 3      True  ACCEPTED                 False
 4      True  ACCEPTED                 False

                            matchedIdentityComponents  \
 0             [고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치]
 1  [targetSegmentThesis, valuePropositionThesis, ...
 2  [targetSegmentThesis, valuePropositionThesis, ...
 3  [targetSegmentThesis, valuePropositionThesis, ...
 4  [targetSegmentThesis, valuePropositionThesis, ...

       missingIdentityComponents reasonCodes safeSummary
 0                            []          []       검사 통과
 1  [useCaseThesis, offerThesis]          []       검사 통과
 2  [useCaseThesis, offerThesis]          []       검사 통과
 3  [useCaseThesis, offerThesis]          []       검사 통과
 4  [useCaseThesis, offerThesis]          []       검사 통과  ,
 'finalCandidates':   candidateId lineageId parentCandidateId                  이름  \
 0          C1        L1              None  1~2인 가구 맞춤형 요리 서비스
 1          C2        L2              None      소량 맞춤형 식재료 서비스
 2          C3        L3              None   간편한 소량 식재료 제공 서비스
 3          C4        L4              None   레시피 기반 소량 식재료 서비스
 4          C5        L5              None   신선한 소량 식재료 배달 서비스

                                              핵심 작동방식         family  \
 0  고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하고, 남은 재료를 활용할 수 ...  기타 역할 · 기타 운영
 1          개인 맞춤형 식재료 패키지를 통해 1~2인 가구의 요리 문제를 해결합니다.  기타 역할 · 기타 운영
 2          고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.  기타 역할 · 기타 운영
 3          고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.  기타 역할 · 기타 운영
 4      고객 맞춤형 식재료 패키지를 제공하여 요리 스타일에 맞춘 소량의 재료를 배송한다.  기타 역할 · 기타 운영

                                           descriptor                 수익  \
 0  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...  구독 모델 및 일회성 구매 모델
 1  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...  구독 모델 및 일회성 구매 모델
 2  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...  구독 모델 및 일회성 구매 모델
 3  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...  구독 모델 및 일회성 구매 모델
 4  {'thesis': {'targetSegmentThesis': '요리할 시간이 적고...  구독 모델 및 일회성 구매 모델

                                 운영
 0  고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
 1  고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
 2  고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
 3      레시피에 따라 필요한 식재료를 조합하여 제공한다.
 4  고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.  }

,A,B,판정,Family A,Family B,겹침,실질 차이,단계,semantic judge,관계 설명
0,C1,C2,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
1,C1,C3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, offerThesis, solutio...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
2,C1,C4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
3,C1,C5,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","customerInteractionModel, valuePropositionThes...",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
4,C2,C3,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
5,C2,C4,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
6,C2,C5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, solutionThesis",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
7,C3,C4,VARIANT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis",MEANINGFUL_THESIS_VARIANT,False,Architecture family는 유사하지만 target/use case/val...
8,C3,C5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","valuePropositionThesis, offerThesis, solutionT...",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.
9,C4,C5,DISTINCT,OTHER:OTHER,OTHER:OTHER,"businessRole, operatingModel, partnerModel, de...","offerThesis, solutionThesis",PRIMARY_BUSINESS_CHOICE,False,핵심 solution 또는 주요 Business Architecture 선택이 다릅니다.

## 26. Legal Fact Completeness + Business Design Completion + C1 Fact Pattern

In [27]:
prechecks = [engine.legal_precheck(item) for item in candidates]
display(show_legal_precheck(prechecks))
legal_preparation = await engine.prepare_legal_candidates(seed, candidates)
candidates_before_legal = candidates
candidates = legal_preparation.candidates
display({'factCompleteness': [item.model_dump(mode='json') for item in legal_preparation.reports],
         'completionAttempted': legal_preparation.completionAttempted,
         'completionValidated': legal_preparation.completionValidated,
         'completionAccepted': legal_preparation.completionAccepted,
         'completionExhausted': legal_preparation.completionExhausted,
         'excludedCandidates': legal_preparation.excludedCandidates})
display(show_legal_fact_pattern(candidates[0].candidate, seed) if candidates else [])

,candidateId,label,directSeller,intermediary,regulatedPhysicalActivity,personalDataDependency,qualificationDependency,riskHints
0,C1,Structural risk precheck — not final legal review,False,False,True,True,False,"[물리 활동, 개인정보]"
1,C2,Structural risk precheck — not final legal review,False,False,True,True,False,"[물리 활동, 개인정보]"
2,C3,Structural risk precheck — not final legal review,False,False,True,True,False,"[물리 활동, 개인정보]"
3,C4,Structural risk precheck — not final legal review,True,False,True,True,False,"[물리 활동, 개인정보]"
4,C5,Structural risk precheck — not final legal review,False,False,True,True,False,"[물리 활동, 개인정보]"

{'factCompleteness': [{'candidateId': 'C1',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C2',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C3',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C4',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'},
  {'candidateId': 'C5',
   'status': 'COMPLETE',
   'missingDesignFacts': [],
   'contradictions': [],
   'completionRequirements': [],
   'affectedFields': [],
   'safeSummary': '법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.'}],
 'completionAttempted': 0,
 'completionValidated': 0,
 'completionAccepted': 0,
 'completionExhausted': 0,
 'excludedCandidates': []}

,field,legalFact,source,authority,decision
0,platformRole,온라인 플랫폼 운영 및 관리,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
1,providerRole,식재료 공급 및 레시피 제공,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
2,sellerRole,고객과의 거래 및 서비스 제공,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
3,intermediaryRole,배송 서비스 제공,CONCEPT_GENERATED,REVIEWABLE,PROPOSED
4,transactionFlow,"[고객이 온라인 플랫폼에서 식재료와 레시피를 선택한다., 주문이 접수되면 시스템이 ...",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
5,paymentFlow,"[고객이 온라인 플랫폼에서 결제한다., 결제 확인 후 주문이 처리된다., 배송 완료...",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
6,personalDataUsage,"[고객의 선호도 분석을 위한 데이터 수집, 주문 이력 관리]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
7,physicalActivities,"[식재료 포장 및 배송, 레시피 개발 및 업데이트]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
8,partnerRequirements,"[신선한 재료 공급을 위한 지역 농가와의 계약, 식품 안전 기준 준수]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED
9,qualificationRequirements,[],CONCEPT_GENERATED,REVIEWABLE,PROPOSED
10,advertisingClaims,"[신선한 재료로 만든 요리, 1~2인 가구에 최적화된 솔루션 제공]",CONCEPT_GENERATED,REVIEWABLE,PROPOSED

## 27. Prepared Legal C1 Evidence Summary

In [28]:
legal_adapter = CurrentLegalAdapter()
legal_c1_input = legal_adapter.task_input(candidates[0].candidate, seed) if candidates else None
display({'candidateId': candidates[0].candidateId if candidates else None,
         'externalFacts': legal_c1_input['externalFactContext']['facts'] if legal_c1_input else [],
         'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'})

{'candidateId': 'C1',
 'externalFacts': [],
 'note': '공식 근거 수와 allowed index는 Full Legal 응답/실패 diagnostics에서 확인'}

## 28. Full Evidence Judgment — C1 Staged Smoke

In [29]:
RUN_FULL_LEGAL_C1 = True  # staged LIVE 확인 후 True
legal_one = None
if RUN_FULL_LEGAL_C1 and candidates:
    try:
        legal_one = await engine.review_legal_candidate(seed, candidates[0])
        display(show_legal_result([legal_one]))
    except Exception:
        display(show_legal_failure(candidates[0].candidateId, engine.gateway))
else:
    print('SKIPPED — RUN_FULL_LEGAL_C1=True로 명시해야 실행됩니다.')

,candidateId,route,productionStatus,sourceStatus,evidenceCoverage,reviewPhase,factCompletenessStatus,legalSourceStatus,finalEvidenceJudgmentExecuted,recoveryResolution,...,controlConvertibleCount,legalClarificationCount,safeSummary,requiredControls,requiredPartnersAndQualifications,requiredDisclosures,prohibitedVariants,evidenceCount,evidenceRefs,evidenceDiagnostics
0,C1,ACCEPT,IMPLEMENTABLE_WITH_CONTROLS,SOURCE_PARTIAL,"공식 근거를 바탕으로 구현 가능성을 검토했으나, 일부 법률 소스의 조회 범위에는 제...",LEGAL_SOURCE,None,SOURCE_PARTIAL,True,None,...,0,0,이 사업 모델은 고객 맞춤형 식재료 제공 및 레시피 제공을 통해 안전하게 운영될 수...,"[신선한 재료 공급을 위한 지역 농가와의 계약을 체결해야 한다., 식품 안전 기준을...","[신선한 재료를 공급할 수 있는 지역 농가와의 계약이 필요하다., 식품 안전 기준을...","[고객의 개인정보 처리 방침을 고지해야 한다., 서비스 이용약관을 고객에게 고지해야...","[기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매는 금지된다., 식품 또는 ...",20,"[{'referenceIndex': 0, 'sourceType': 'OFFICIAL...","{'coverageStatus': 'SOURCE_PARTIAL', 'coverage..."

## 29. C1 Route + Staged Redesign/Compliance/Second Legal

In [30]:
c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = ([], [], [], 0, 0)
if legal_one and candidates:
    c1_portfolio, c1_legal_all, c1_required_inputs, c1_redesigned, c1_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[:1], [legal_one])
display({'initialRoute': legal_one.route.value if legal_one else 'SKIPPED',
         'redesignRequirements': legal_one.redesignRequirements if legal_one else [],
         'recoveryReviews': [item.model_dump(mode='json') for item in c1_legal_all[1:]],
         'requiredInputs': c1_required_inputs, 'terminalCandidates': len(c1_portfolio),
         'redesigned': c1_redesigned, 'replanned': c1_replanned})

{'initialRoute': 'ACCEPT',
 'redesignRequirements': [],
 'recoveryReviews': [],
 'requiredInputs': [],
 'terminalCandidates': 1,
 'redesigned': 0,
 'replanned': 0}

## 30. Remaining 4 Legal + Exhaustive Recovery Summary

In [31]:
RUN_REMAINING_LEGAL = True
legal_remaining = []
portfolio, legal_all, required_inputs = (list(c1_portfolio), list(c1_legal_all), list(c1_required_inputs))
redesigned_count, replanned_count = c1_redesigned, c1_replanned
c1_terminal = bool(c1_portfolio or c1_required_inputs or (c1_legal_all and c1_legal_all[-1].route.value == 'SYSTEM_FAILURE'))
if RUN_REMAINING_LEGAL and c1_terminal and len(candidates) > 1:
    legal_remaining = await engine.review_legal(seed, candidates[1:])
    rest_portfolio, rest_legal, rest_inputs, rest_redesigned, rest_replanned = await engine.resolve_legal(
        seed, candidate_preparation.usedPlans, candidates[1:], legal_remaining)
    portfolio += rest_portfolio; legal_all += rest_legal; required_inputs += rest_inputs
    redesigned_count += rest_redesigned; replanned_count += rest_replanned
else:
    print('SKIPPED — C1이 정상 terminal에 도달한 후 remaining Legal을 실행합니다.')
legal_initial = ([legal_one] if legal_one else []) + legal_remaining
display({'recoveryTrace': [item.model_dump(mode='json') for item in legal_all
                           if item.candidateId not in {x.candidateId for x in legal_initial}],
         'requiredInputs': required_inputs, 'metrics': engine._legal_metrics})
print({'Plan Selected': len(selected_plans),
       'Candidate Generated': candidate_preparation.candidateGenerated,
       'Candidate Accepted': len(candidates),
       'Legal Accepted': sum(item.route.value == 'ACCEPT' for item in legal_all),
       'Legal Redesigned': redesigned_count, 'Legal Replanned': replanned_count,
       'Final Portfolio': len(portfolio)})

{'recoveryTrace': [],
 'requiredInputs': [{'candidateId': 'C4',
   'scope': 'CANDIDATE',
   'conflictingLock': None,
   'currentValue': None,
   'requiredLegalChange': None,
   'reason': None,
   'possibleUserAction': None,
   'safeSummary': 'Concept가 결정할 수 없는 외부 현실 사실의 확인이 필요합니다.'}],
 'metrics': {'factAttempted': 0,
  'factValidated': 0,
  'factAccepted': 0,
  'factExhausted': 0,
  'redesignAttempted': 0,
  'redesignValidated': 0,
  'redesignAccepted': 0,
  'redesignExhausted': 0,
  'replanAttempted': 0,
  'replanValidated': 0,
  'replanAccepted': 0,
  'replanExhausted': 0}}

{'Plan Selected': 5, 'Candidate Generated': 5, 'Candidate Accepted': 5, 'Legal Accepted': 4, 'Legal Redesigned': 0, 'Legal Replanned': 0, 'Final Portfolio': 4}

## 31. Replan

In [32]:
display(show_replan(type('PortfolioView', (), {'concepts': portfolio})()))
print({'replanned': replanned_count, 'reserveAvailable': len(reserve_plans)})

Empty DataFrame
Columns: []
Index: []

{'replanned': 0, 'reserveAvailable': 1}

## 32. Final Portfolio

In [33]:
legal_terminal_status = ('READY_FULL' if len(portfolio) == MAX_CONCEPTS else
    'READY_LIMITED' if portfolio else
    'LEGAL_RECOVERY_COMPLETE_NO_ACCEPTED_CANDIDATE' if legal_initial and len(legal_initial) == len(candidates)
    else 'LEGAL_PENDING')
display(show_final_portfolio(type('PortfolioView', (), {'concepts': portfolio})()) if portfolio else {'status': legal_terminal_status})

,candidateId,lineageId,parentCandidateId,이름,핵심 작동방식,family,descriptor,수익,운영
0,C1,L1,None,1~2인 가구 맞춤형 요리 서비스,"고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하고, 남은 재료를 활용할 수 ...",기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
1,C2,L2,None,소량 맞춤형 식재료 서비스,개인 맞춤형 식재료 패키지를 통해 1~2인 가구의 요리 문제를 해결합니다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
2,C3,L3,None,간편한 소량 식재료 제공 서비스,고객의 요리 스타일에 맞춘 소량 식재료를 제공하여 음식물 쓰레기를 줄인다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.
3,C5,L5,None,신선한 소량 식재료 배달 서비스,고객 맞춤형 식재료 패키지를 제공하여 요리 스타일에 맞춘 소량의 재료를 배송한다.,기타 역할 · 기타 운영,{'thesis': {'targetSegmentThesis': '요리할 시간이 적고...,구독 모델 및 일회성 구매 모델,고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.

## 33. Unresolved Candidate Summary

In [34]:
display(required_inputs if required_inputs else {'unresolved': []})

[{'candidateId': 'C4',
  'scope': 'CANDIDATE',
  'conflictingLock': None,
  'currentValue': None,
  'requiredLegalChange': None,
  'reason': None,
  'possibleUserAction': None,
  'safeSummary': 'Concept가 결정할 수 없는 외부 현실 사실의 확인이 필요합니다.'}]

## 34. Manual Concept Selection

In [35]:
SELECTED_CANDIDATE_ID = portfolio[0].candidateId if portfolio else None  # 사용자가 수정
selected_concept = next((item for item in portfolio if item.candidateId == SELECTED_CANDIDATE_ID), None)
print({'selectedCandidateId': SELECTED_CANDIDATE_ID})

{'selectedCandidateId': 'C1'}

## 35. 7 Hypotheses

In [36]:
hypotheses = engine.build_or_load_current_hypothesis_contract(selected_concept) if selected_concept else []
display(show_hypotheses(hypotheses))
display(show_hypothesis_readiness(hypotheses))

,HypothesisType,ProposedValue,FinalValue,SemanticStatus,SemanticReason,Locked,DecisionStatus,LegalImpact
0,TARGET_REGION,대한민국 전역,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
1,REVENUE_MODEL,구독 모델 및 일회성 구매 모델,None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
2,PRICE,"1인 기준 5,000원 ~ 15,000원",None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
3,CHANNELS,온라인 플랫폼 (웹사이트 및 모바일 앱),None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
4,DIFFERENTIATORS,"고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치",None,VALID,실제 사업 가설값입니다.,False,PROPOSED,NONE
5,PRE_MARKET_SOM_SHARE,targetSharePercent=15.0 horizonYears=3 rationa...,None,VALID,수치·기간·산식 가설이 명시되었습니다.,False,PROPOSED,NONE
6,PRE_MARKET_SOM,amount=5000000.0 currency='KRW' period='1년' ca...,None,VALID,수치·기간·산식 가설이 명시되었습니다.,False,PROPOSED,NONE

{'All Hypotheses Semantically Ready': False,
 'status': 'NOT_READY',
 'reason': 'UNRESOLVED_HYPOTHESES',
 'unresolvedHypotheses': ['TARGET_REGION',
  'REVENUE_MODEL',
  'PRICE',
  'CHANNELS',
  'DIFFERENTIATORS',
  'PRE_MARKET_SOM_SHARE',
  'PRE_MARKET_SOM']}

## 36. Confirm / Edit

In [37]:
CONFIRM_ALL_PROPOSED = True
HYPOTHESIS_EDITS = {
    # 'PRICE': '월 17,900원',
}
confirmed_hypotheses = engine.confirm_hypotheses(
    hypotheses, HYPOTHESIS_EDITS, confirm_all_proposed=CONFIRM_ALL_PROPOSED) if hypotheses else []
display(show_hypotheses(confirmed_hypotheses))
hypothesis_readiness = show_hypothesis_readiness(confirmed_hypotheses)
display(hypothesis_readiness)

,HypothesisType,ProposedValue,FinalValue,SemanticStatus,SemanticReason,Locked,DecisionStatus,LegalImpact
0,TARGET_REGION,대한민국 전역,대한민국 전역,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
1,REVENUE_MODEL,구독 모델 및 일회성 구매 모델,구독 모델 및 일회성 구매 모델,VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
2,PRICE,"1인 기준 5,000원 ~ 15,000원","1인 기준 5,000원 ~ 15,000원",VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
3,CHANNELS,온라인 플랫폼 (웹사이트 및 모바일 앱),온라인 플랫폼 (웹사이트 및 모바일 앱),VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
4,DIFFERENTIATORS,"고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치","고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치",VALID,실제 사업 가설값입니다.,False,ACCEPTED,NONE
5,PRE_MARKET_SOM_SHARE,targetSharePercent=15.0 horizonYears=3 rationa...,targetSharePercent=15.0 horizonYears=3 rationa...,VALID,수치·기간·산식 가설이 명시되었습니다.,False,ACCEPTED,NONE
6,PRE_MARKET_SOM,amount=5000000.0 currency='KRW' period='1년' ca...,amount=5000000.0 currency='KRW' period='1년' ca...,VALID,수치·기간·산식 가설이 명시되었습니다.,False,ACCEPTED,NONE

{'All Hypotheses Semantically Ready': True,
 'status': 'READY',
 'reason': None,
 'unresolvedHypotheses': []}

## 37. Actual Delta Legal

In [38]:
RUN_DELTA_LEGAL = True
delta_legal_result = None
if RUN_DELTA_LEGAL and selected_concept and any(h.deltaLegalRequired for h in confirmed_hypotheses):
    delta_legal_result = await engine.review_delta_legal(seed, selected_concept, confirmed_hypotheses)
    confirmed_hypotheses = engine.mark_delta_legal_reviewed(confirmed_hypotheses, delta_legal_result)
display(delta_legal_result.model_dump(mode='json') if delta_legal_result else {'status': 'NOT_REQUIRED_OR_SKIPPED'})

{'status': 'NOT_REQUIRED_OR_SKIPPED'}

## 38. Market Seed

In [39]:
handoff = None
if selected_concept and legal_all and hypothesis_readiness['All Hypotheses Semantically Ready']:
    handoff = engine.build_downstream_handoff(seed, selected_concept, confirmed_hypotheses, legal_all)
display(handoff.marketAnalysisSeedSnapshot if handoff else {
    'status': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'contract': 'market-analysis-seed-snapshot-v1',
 'schemaVersion': '2.0',
 'snapshotId': 'lab-market-seed',
 'projectId': 0,
 'selectionId': 0,
 'conceptId': 'C1',
 'createdAt': '2026-08-10T02:18:21.965519+00:00',
 'sourceSnapshotHash': 'sha256:48ef3babc6f1665a3e865fd48dc546d018dfb0735804c54a1eac1177d01d3f52',
 'originalSeed': {'ideaOverview': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
  'fields': {'ideaOverview': {'value': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'},
   'problem': {'value': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'},
   'targetUsers': {'value': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
    'source': 'USER_INPUT',
    'decisionState': 'LOCKED'}}},
 'aiInterpretation': {'interpretedProblem': '1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.',
  'interpretedTargetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.',
  'usageContext': '소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.',
  'industryCategory': '식품 및 요리 서비스',
  'researchScope': '소량 식재료 및 레시피 제공 서비스에 대한 시장 조사.',
  'conciseIdeaDefinition': '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.',
  'targetRegionInterpretation': '특정 지역에 대한 정보가 필요합니다.',
  'relevantKnownCompetitorContext': '경쟁자에 대한 정보가 필요합니다.'},
 'selectedConcept': {'identity': {'conceptName': '1~2인 가구 맞춤형 요리 서비스',
   'conceptDefinition': '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.',
   'introduction': '1~2인 가구를 위한 맞춤형 요리 솔루션 제공 서비스로, 고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하여 요리의 즐거움을 높인다.',
   'coreValue': '필요한 만큼의 식재료와 요리 레시피를 제공하여 요리를 쉽게 할 수 있도록 돕는다.',
   'targetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
   'industryCategory': '식품 및 요리 서비스',
   'researchScope': '소량 식재료 및 레시피 제공 서비스에 대한 시장 조사.'},
  'solution': {'problemScenario': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다.',
   'solutionMechanism': '고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하고, 남은 재료를 활용할 수 있는 레시피를 안내한다.',
   'featureSet': ['고객 맞춤형 식재료 패키지', '정기 구독 서비스', '온라인 레시피 제공', '신선한 재료 배송']},
  'operation': {'actorRoles': ['고객', '주문 처리 시스템', '배송 서비스', '레시피 제공 시스템'],
   'platformRole': '온라인 플랫폼 운영 및 관리',
   'operatingModel': '고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.',
   'partnerModel': '지역 농가 및 식품 제조업체와 협력하여 신선한 재료를 확보한다.',
   'providerRole': '식재료 공급 및 레시피 제공',
   'sellerRole': '고객과의 거래 및 서비스 제공',
   'intermediaryRole': '배송 서비스 제공',
   'transactionFlow': ['고객이 온라인 플랫폼에서 식재료와 레시피를 선택한다.',
    '주문이 접수되면 시스템이 주문을 처리한다.',
    '배송 서비스가 고객의 주소로 식재료를 배송한다.'],
   'paymentFlow': ['고객이 온라인 플랫폼에서 결제한다.',
    '결제 확인 후 주문이 처리된다.',
    '배송 완료 후 정산이 이루어진다.'],
   'personalDataUsage': ['고객의 선호도 분석을 위한 데이터 수집', '주문 이력 관리'],
   'physicalActivities': ['식재료 포장 및 배송', '레시피 개발 및 업데이트'],
   'partnerRequirements': ['신선한 재료 공급을 위한 지역 농가와의 계약', '식품 안전 기준 준수'],
   'qualificationRequirements': []},
  'valueSemantics': [{'fieldKey': 'conceptName',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'conceptDefinition',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'introduction',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'coreValue',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'targetUsers',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'industryCategory',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'researchScope',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'targetRegion',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'revenueModel',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'price',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'channels',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'differentiators',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'preMarketSomShareHypothesis',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'preMarketSomHypothesis',
    'source': 'AI_HYPOTHESIS',
    'authority': 'OPEN',
    'decision': 'PROPOSED'},
   {'fieldKey': 'actorRoles',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'platformRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'problemScenario',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'solutionMechanism',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'featureSet',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'operatingModel',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'partnerModel',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'providerRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'sellerRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'intermediaryRole',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'transactionFlow',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'paymentFlow',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'personalDataUsage',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'physicalActivities',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'partnerRequirements',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'qualificationRequirements',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'},
   {'fieldKey': 'advertisingClaims',
    'source': 'CONCEPT_GENERATED',
    'authority': 'REVIEWABLE',
    'decision': 'PROPOSED'}],
  'canonicalHash': 'sha256:e482e106e6459a3add71072ef0dc1b39cda83bbe0013b2833ad397d0e7357d2d'},
 'finalHypotheses': {'targetRegion': {'value': '대한민국 전역',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'revenueModel': {'value': '구독 모델 및 일회성 구매 모델',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'price': {'value': '1인 기준 5,000원 ~ 15,000원',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'channels': {'value': '온라인 플랫폼 (웹사이트 및 모바일 앱)',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'differentiators': {'value': '고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치',
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'preMarketSomShare': {'value': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='1~2인 가구의 증가와 요리의 간편함을 추구하는 트렌드에 기반하여 시장 점유율을 확보할 수 있다.', assumptions=['1~2인 가구의 수가 증가할 것이다.', '소량 식재료에 대한 수요가 증가할 것이다.']),
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'},
  'preMarketSom': {'value': PreMarketSomHypothesis(amount=5000000.0, currency='KRW', period='1년', calculationBasis='1~2인 가구의 평균 소비자 수와 예상 구매 빈도에 기반하여 추정.', assumptions=['소량 식재료 서비스에 대한 인식이 높아질 것이다.', '고객의 재구매율이 높을 것이다.'], confidence='HIGH'),
   'source': 'AI_HYPOTHESIS',
   'decisionStatus': 'ACCEPTED',
   'proposalVersion': 1,
   'legalImpact': 'NONE',
   'legalReviewStatus': 'NOT_REQUIRED'}},
 'legalResult': {'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
  'safeSummary': '이 사업 모델은 고객 맞춤형 식재료 제공 및 레시피 제공을 통해 안전하게 운영될 수 있으며, 관련 법령을 준수하는 조건 하에 구현이 가능하다.',
  'requiredControls': ['신선한 재료 공급을 위한 지역 농가와의 계약을 체결해야 한다.',
   '식품 안전 기준을 준수해야 한다.',
   '고객의 개인정보를 안전하게 처리하기 위한 정책을 마련해야 한다.',
   '온라인 플랫폼에서의 결제 시스템을 안전하게 운영해야 한다.',
   '고객에게 청약철회 및 거래조건에 대한 정보를 제공해야 한다.',
   '영수증 발급 의무를 준수해야 한다.',
   '약관의 작성 및 설명의무를 준수해야 한다.'],
  'requiredPartnersAndQualifications': ['신선한 재료를 공급할 수 있는 지역 농가와의 계약이 필요하다.',
   '식품 안전 기준을 준수하는 파트너와 협력해야 한다.'],
  'prohibitedVariants': ['기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매는 금지된다.',
   '식품 또는 식품첨가물에 관한 기준 및 규격을 준수하지 않는 경우 판매가 금지된다.',
   '농약 등의 잔류허용기준을 초과하는 식재료의 사용은 금지된다.'],
  'requiredDisclosures': ['고객의 개인정보 처리 방침을 고지해야 한다.',
   '서비스 이용약관을 고객에게 고지해야 한다.'],
  'officialEvidenceReferences': [{'referenceIndex': 0,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001805',
    'officialIdentifier': '277149',
    'lawName': '식품위생법',
    'articleReference': '제6조',
    'title': '기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매 등 금지',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20251001',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:1253eb1604afa3574783b0789f62cc1842b5ba0826a8ad798d27de56d9d07579',
    'boundedProvisionSummary': '기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매 금지',
    'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 1,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001805',
    'officialIdentifier': '277149',
    'lawName': '식품위생법',
    'articleReference': '제7조',
    'title': '식품 또는 식품첨가물에 관한 기준 및 규격',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20251001',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:2d558b508a0bf2d5f9c1e1af2642c0580d313a0dce3f5c300b4a4b346b573dc6',
    'boundedProvisionSummary': '식품 또는 식품첨가물에 관한 기준 및 규격 설정',
    'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 2,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001805',
    'officialIdentifier': '277149',
    'lawName': '식품위생법',
    'articleReference': '제7조의3',
    'title': '농약 등의 잔류허용기준 설정 요청 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20251001',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:1d5ae9f8190ed5234896f5b5596a792866460e050b0afdf568144d67a5d7cac7',
    'boundedProvisionSummary': '농약 등의 잔류허용기준 설정 요청',
    'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 3,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001805',
    'officialIdentifier': '277149',
    'lawName': '식품위생법',
    'articleReference': '제7조의4',
    'title': '식품등의 기준 및 규격 관리계획 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20251001',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:93488d5f793d1458d041b00e684b538067fec75d25eb28909cd51c5818c80c9b',
    'boundedProvisionSummary': '식품등의 기준 및 규격 관리계획 수립',
    'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 4,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '013094',
    'officialIdentifier': '269957',
    'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
    'articleReference': '제4조',
    'title': '표시의 기준',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250318',
    'effectiveDate': '20250919',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:7ab3b3609ddb05ab291bdd9e67d5ed58e4dc15e6731eba81681e3c41710a56fd',
    'boundedProvisionSummary': '식품등의 표시 기준 설정',
    'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 5,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '013094',
    'officialIdentifier': '269957',
    'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
    'articleReference': '제4조의2',
    'title': '시각ㆍ청각장애인을 위한 점자 및 음성ㆍ수어영상변환용 코드의 표시',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250318',
    'effectiveDate': '20250919',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:4591f32b2c11e98d98a4b972b6743b3a6d0f9e041212de12547a120053c93096',
    'boundedProvisionSummary': '시각ㆍ청각장애인을 위한 점자 및 음성ㆍ수어영상변환용 코드의 표시',
    'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 6,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '013094',
    'officialIdentifier': '269957',
    'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
    'articleReference': '제5조',
    'title': '영양표시',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250318',
    'effectiveDate': '20250919',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:ccae8d1b46cf70df431217ea23ceb114e94a24c651c746d9b44ca585d561bef0',
    'boundedProvisionSummary': '영양표시 의무',
    'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 7,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '013094',
    'officialIdentifier': '269957',
    'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
    'articleReference': '제6조',
    'title': '나트륨 함량 비교 표시',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20250318',
    'effectiveDate': '20250919',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:d719f3435b365a553bbf3fc847b4f0558dd1326ce8932ffb7a9182f1db0bd6d7',
    'boundedProvisionSummary': '나트륨 함량 비교 표시 의무',
    'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 8,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제12조',
    'title': '통신판매업자의 신고 등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:448fe0bd6a72942700268999bc17abaf1a130dc75ff98338f016366ffccb8d53',
    'boundedProvisionSummary': '통신판매업자의 신고 의무',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 9,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제13조',
    'title': '신원 및 거래조건에 대한 정보의 제공',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:6e496bba7781eda4a1e42db7cb6ead3a7f9648a8557ee96ea09e290d3f30b30d',
    'boundedProvisionSummary': '신원 및 거래조건에 대한 정보 제공 의무',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 10,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제17조',
    'title': '청약철회등',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:086921e6e5bc694ea2d723423f266762b50490e33b8739d64e1920b7a13bde5c',
    'boundedProvisionSummary': '청약철회 등의 권리 안내',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 11,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '009318',
    'officialIdentifier': '282793',
    'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
    'articleReference': '제18조',
    'title': '청약철회등의 효과',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
    'jurisdiction': 'KR',
    'promulgationDate': '20260120',
    'effectiveDate': '20260721',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:48bb8d8484384496bed84e6eac658a1ea9dcd53ed91bc5d6291359764c102642',
    'boundedProvisionSummary': '청약철회 등의 효과 안내',
    'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
    'registryVersion': 'legal-registry-v1'},
   {'referenceIndex': 12,
    'sourceType': 'OFFICIAL_LAW',
    'lawId': '001571',
    'officialIdentifier': '276117',
    'lawName': '부가가치세법',
    'articleReference': '제5조',
    'title': '과세기간',
    'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
    'jurisdiction': 'KR',
    'promulgationDate': '20251001',
    'effectiveDate': '20260102',
    'retrievedAt': '2026-08-10T02:16:53.380434Z',
    'contentHash': 'sha256:55e12be5d081847f6c347a9be100376c35ba524c561e8d24448e063534c29ca9',
    'boundedProvisionSummary': '부가가치세 과세기간 설정',

## 39. Marketing Source

In [40]:
display(handoff.marketingSourceSnapshot if handoff else {
    'status': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'contract': 'marketing-source-snapshot-v1',
 'schemaVersion': '2.0',
 'snapshotId': 'lab-marketing-source',
 'projectId': 0,
 'selectionId': 0,
 'conceptId': 'C1',
 'marketAnalysisSeedSnapshotId': 'lab-market-seed',
 'marketAnalysisSeedSnapshotHash': 'sha256:e5613a55ff90e846b4080bb52d9f2575e3449c6b1a8e47bd4898e68edff3225b',
 'createdAt': '2026-08-10T02:18:21.965519+00:00',
 'conceptName': '1~2인 가구 맞춤형 요리 서비스',
 'targetSegment': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
 'problem': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다.',
 'valueProposition': '필요한 만큼의 식재료와 요리 레시피를 제공하여 요리를 쉽게 할 수 있도록 돕는다.',
 'positioning': '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.',
 'keyFeatures': ['고객 맞춤형 식재료 패키지', '정기 구독 서비스', '온라인 레시피 제공', '신선한 재료 배송'],
 'targetRegion': '대한민국 전역',
 'revenueModel': '구독 모델 및 일회성 구매 모델',
 'price': '1인 기준 5,000원 ~ 15,000원',
 'pricing': '구독 모델 및 일회성 구매 모델 · 1인 기준 5,000원 ~ 15,000원',
 'channels': ['온라인 플랫폼 (웹사이트 및 모바일 앱)'],
 'competitorDifferentiators': ['고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치'],
 'preMarketSomShare': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='1~2인 가구의 증가와 요리의 간편함을 추구하는 트렌드에 기반하여 시장 점유율을 확보할 수 있다.', assumptions=['1~2인 가구의 수가 증가할 것이다.', '소량 식재료에 대한 수요가 증가할 것이다.']),
 'preMarketSom': PreMarketSomHypothesis(amount=5000000.0, currency='KRW', period='1년', calculationBasis='1~2인 가구의 평균 소비자 수와 예상 구매 빈도에 기반하여 추정.', assumptions=['소량 식재료 서비스에 대한 인식이 높아질 것이다.', '고객의 재구매율이 높을 것이다.'], confidence='HIGH'),
 'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
 'allowedClaims': ['신선한 재료로 만든 요리', '1~2인 가구에 최적화된 솔루션 제공'],
 'prohibitedClaims': ['기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매는 금지된다.',
  '식품 또는 식품첨가물에 관한 기준 및 규격을 준수하지 않는 경우 판매가 금지된다.',
  '농약 등의 잔류허용기준을 초과하는 식재료의 사용은 금지된다.'],
 'requiredDisclosures': ['고객의 개인정보 처리 방침을 고지해야 한다.',
  '서비스 이용약관을 고객에게 고지해야 한다.'],
 'requiredControls': ['신선한 재료 공급을 위한 지역 농가와의 계약을 체결해야 한다.',
  '식품 안전 기준을 준수해야 한다.',
  '고객의 개인정보를 안전하게 처리하기 위한 정책을 마련해야 한다.',
  '온라인 플랫폼에서의 결제 시스템을 안전하게 운영해야 한다.',
  '고객에게 청약철회 및 거래조건에 대한 정보를 제공해야 한다.',
  '영수증 발급 의무를 준수해야 한다.',
  '약관의 작성 및 설명의무를 준수해야 한다.'],
 'communicationRequiredControls': ['신선한 재료 공급을 위한 지역 농가와의 계약을 체결해야 한다.',
  '식품 안전 기준을 준수해야 한다.',
  '고객의 개인정보를 안전하게 처리하기 위한 정책을 마련해야 한다.',
  '온라인 플랫폼에서의 결제 시스템을 안전하게 운영해야 한다.',
  '고객에게 청약철회 및 거래조건에 대한 정보를 제공해야 한다.',
  '영수증 발급 의무를 준수해야 한다.',
  '약관의 작성 및 설명의무를 준수해야 한다.'],
 'officialEvidenceReferences': [{'referenceIndex': 0,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001805',
   'officialIdentifier': '277149',
   'lawName': '식품위생법',
   'articleReference': '제6조',
   'title': '기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매 등 금지',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20251001',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:1253eb1604afa3574783b0789f62cc1842b5ba0826a8ad798d27de56d9d07579',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 1,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001805',
   'officialIdentifier': '277149',
   'lawName': '식품위생법',
   'articleReference': '제7조',
   'title': '식품 또는 식품첨가물에 관한 기준 및 규격',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20251001',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:2d558b508a0bf2d5f9c1e1af2642c0580d313a0dce3f5c300b4a4b346b573dc6',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 2,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001805',
   'officialIdentifier': '277149',
   'lawName': '식품위생법',
   'articleReference': '제7조의3',
   'title': '농약 등의 잔류허용기준 설정 요청 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20251001',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:1d5ae9f8190ed5234896f5b5596a792866460e050b0afdf568144d67a5d7cac7',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 3,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001805',
   'officialIdentifier': '277149',
   'lawName': '식품위생법',
   'articleReference': '제7조의4',
   'title': '식품등의 기준 및 규격 관리계획 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20251001',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:93488d5f793d1458d041b00e684b538067fec75d25eb28909cd51c5818c80c9b',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 4,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '013094',
   'officialIdentifier': '269957',
   'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
   'articleReference': '제4조',
   'title': '표시의 기준',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250318',
   'effectiveDate': '20250919',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:7ab3b3609ddb05ab291bdd9e67d5ed58e4dc15e6731eba81681e3c41710a56fd',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 5,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '013094',
   'officialIdentifier': '269957',
   'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
   'articleReference': '제4조의2',
   'title': '시각ㆍ청각장애인을 위한 점자 및 음성ㆍ수어영상변환용 코드의 표시',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250318',
   'effectiveDate': '20250919',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:4591f32b2c11e98d98a4b972b6743b3a6d0f9e041212de12547a120053c93096',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 6,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '013094',
   'officialIdentifier': '269957',
   'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
   'articleReference': '제5조',
   'title': '영양표시',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250318',
   'effectiveDate': '20250919',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:ccae8d1b46cf70df431217ea23ceb114e94a24c651c746d9b44ca585d561bef0',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 7,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '013094',
   'officialIdentifier': '269957',
   'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
   'articleReference': '제6조',
   'title': '나트륨 함량 비교 표시',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20250318',
   'effectiveDate': '20250919',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:d719f3435b365a553bbf3fc847b4f0558dd1326ce8932ffb7a9182f1db0bd6d7',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 8,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제12조',
   'title': '통신판매업자의 신고 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:448fe0bd6a72942700268999bc17abaf1a130dc75ff98338f016366ffccb8d53',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 9,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제13조',
   'title': '신원 및 거래조건에 대한 정보의 제공',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:6e496bba7781eda4a1e42db7cb6ead3a7f9648a8557ee96ea09e290d3f30b30d',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 10,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제17조',
   'title': '청약철회등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:086921e6e5bc694ea2d723423f266762b50490e33b8739d64e1920b7a13bde5c',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 11,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '009318',
   'officialIdentifier': '282793',
   'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
   'articleReference': '제18조',
   'title': '청약철회등의 효과',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20260120',
   'effectiveDate': '20260721',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:48bb8d8484384496bed84e6eac658a1ea9dcd53ed91bc5d6291359764c102642',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 12,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제5조',
   'title': '과세기간',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:55e12be5d081847f6c347a9be100376c35ba524c561e8d24448e063534c29ca9',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 13,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제8조',
   'title': '사업자등록',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:f592e37dcf9ad848267be7603a224ad1645f2b8ef32bd5463d0f81b6296939b2',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 14,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제36조',
   'title': '영수증 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:73a2ea65e521a0d7b21520ba72f17ce4be74a0258a17177073833853d88968f2',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 15,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '001571',
   'officialIdentifier': '276117',
   'lawName': '부가가치세법',
   'articleReference': '제53조의2',
   'title': '전자적 용역을 공급하는 국외사업자의 사업자등록 및 납부 등에 관한 특례',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%98%EC%84%B8%EB%B2%95',
   'jurisdiction': 'KR',
   'promulgationDate': '20251001',
   'effectiveDate': '20260102',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:fb9766cb992d59a2c98a513510e00823fbac4ba1662f6afa5554c0e5e1e5dc18',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 16,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제3조',
   'title': '약관의 작성 및 설명의무 등',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:1616dce193e178dfd11405c2891a1bdea99e8a3b2e06ee7b662ebcb5d99bea23',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 17,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제5조',
   'title': '약관의 해석',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:f85b7d1c454d2a8ed12a884b224e377844ab60a45906b658e47469009efc00e6',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 18,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제16조',
   'title': '일부 무효의 특칙',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:0719bda3584934dc655f86e42d2bd50b5faeedf32df5de39a409256332337d52',
   'registryVersion': 'legal-registry-v1'},
  {'referenceIndex': 19,
   'sourceType': 'OFFICIAL_LAW',
   'lawId': '000667',
   'officialIdentifier': '260021',
   'lawName': '약관의 규제에 관한 법률',
   'articleReference': '제17조',
   'title': '불공정약관조항의 사용금지',
   'officialSourceUri': 'https://www.law.go.kr/법령/%EC%95%BD%EA%B4%80%EC%9D%98%20%EA%B7%9C%EC%A0%9C%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
   'jurisdiction': 'KR',
   'promulgationDate': '20240206',
   'effectiveDate': '20240807',
   'retrievedAt': '2026-08-10T02:16:53.380434Z',
   'contentHash': 'sha256:c443ce12c5268686ed554a0ced386d8c85057d3bf72b69c432f50429172c692a',
   'registryVersion': 'legal-registry-v1'}],
 'hash': 'sha256:babd915e9d538e96beec8f49f840f835e8b432bfec7052fe3cbdbc56cbc584f8',
 'sourceSnapshotHash': 'sha256:babd915e9d538e96beec8f49f840f835e8b432bfec7052fe3cbdbc56cbc584f8'}

## 40. Contract Compatibility

In [41]:
display(show_downstream_handoff(handoff) if handoff else {
    'contract': 'NOT_READY', 'reason': hypothesis_readiness.get('reason'),
    'unresolvedHypotheses': hypothesis_readiness.get('unresolvedHypotheses', [])})

{'호환성': 'PASS',
 '구조': 'STRUCTURE_PASS',
 '계약': 'CONTRACT_PASS',
 '필드 매핑':                        v2Field                             downstreamField  \
 0        candidate.conceptName        selectedConcept.identity.conceptName
 1  candidate.solutionMechanism  selectedConcept.solution.solutionMechanism
 2                hypotheses[*]                             finalHypotheses
 3                        legal                                 legalResult

               source  transformed  required
 0  CONCEPT_GENERATED        False      True
 1  CONCEPT_GENERATED        False      True
 2     USER_CONFIRMED         True      True
 3  OFFICIAL_EVIDENCE         True      True  ,
 'Market payload': {'contract': 'market-analysis-seed-snapshot-v1',
  'schemaVersion': '2.0',
  'snapshotId': 'lab-market-seed',
  'projectId': 0,
  'selectionId': 0,
  'conceptId': 'C1',
  'createdAt': '2026-08-10T02:18:21.965519+00:00',
  'sourceSnapshotHash': 'sha256:48ef3babc6f1665a3e865fd48dc546d018dfb0735804c54a1eac1177d01d3f52',
  'originalSeed': {'ideaOverview': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
   'fields': {'ideaOverview': {'value': '개인 맞춤형 소량 식재료를 제공하고 남은 재료 활용 레시피를 안내하는 서비스',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'},
    'problem': {'value': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'},
    'targetUsers': {'value': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
     'source': 'USER_INPUT',
     'decisionState': 'LOCKED'}}},
  'aiInterpretation': {'interpretedProblem': '1~2인 가구에서 발생하는 음식물 쓰레기 문제를 해결하기 위한 서비스.',
   'interpretedTargetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구.',
   'usageContext': '소량의 식재료를 필요로 하는 소비자에게 맞춤형 서비스를 제공하는 상황.',
   'industryCategory': '식품 및 요리 서비스',
   'researchScope': '소량 식재료 및 레시피 제공 서비스에 대한 시장 조사.',
   'conciseIdeaDefinition': '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.',
   'targetRegionInterpretation': '특정 지역에 대한 정보가 필요합니다.',
   'relevantKnownCompetitorContext': '경쟁자에 대한 정보가 필요합니다.'},
  'selectedConcept': {'identity': {'conceptName': '1~2인 가구 맞춤형 요리 서비스',
    'conceptDefinition': '개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스.',
    'introduction': '1~2인 가구를 위한 맞춤형 요리 솔루션 제공 서비스로, 고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하여 요리의 즐거움을 높인다.',
    'coreValue': '필요한 만큼의 식재료와 요리 레시피를 제공하여 요리를 쉽게 할 수 있도록 돕는다.',
    'targetUsers': '요리할 시간이 적고 낭비를 줄이고 싶은 1~2인 가구',
    'industryCategory': '식품 및 요리 서비스',
    'researchScope': '소량 식재료 및 레시피 제공 서비스에 대한 시장 조사.'},
   'solution': {'problemScenario': '1~2인 가구가 큰 포장 단위 때문에 식재료를 남기고 음식물 쓰레기가 발생한다.',
    'solutionMechanism': '고객의 요리 스타일에 맞춘 소량 식재료 패키지를 제공하고, 남은 재료를 활용할 수 있는 레시피를 안내한다.',
    'featureSet': ['고객 맞춤형 식재료 패키지', '정기 구독 서비스', '온라인 레시피 제공', '신선한 재료 배송']},
   'operation': {'actorRoles': ['고객', '주문 처리 시스템', '배송 서비스', '레시피 제공 시스템'],
    'platformRole': '온라인 플랫폼 운영 및 관리',
    'operatingModel': '고객의 선호도에 따라 맞춤형 식재료를 조합하여 제공한다.',
    'partnerModel': '지역 농가 및 식품 제조업체와 협력하여 신선한 재료를 확보한다.',
    'providerRole': '식재료 공급 및 레시피 제공',
    'sellerRole': '고객과의 거래 및 서비스 제공',
    'intermediaryRole': '배송 서비스 제공',
    'transactionFlow': ['고객이 온라인 플랫폼에서 식재료와 레시피를 선택한다.',
     '주문이 접수되면 시스템이 주문을 처리한다.',
     '배송 서비스가 고객의 주소로 식재료를 배송한다.'],
    'paymentFlow': ['고객이 온라인 플랫폼에서 결제한다.',
     '결제 확인 후 주문이 처리된다.',
     '배송 완료 후 정산이 이루어진다.'],
    'personalDataUsage': ['고객의 선호도 분석을 위한 데이터 수집', '주문 이력 관리'],
    'physicalActivities': ['식재료 포장 및 배송', '레시피 개발 및 업데이트'],
    'partnerRequirements': ['신선한 재료 공급을 위한 지역 농가와의 계약', '식품 안전 기준 준수'],
    'qualificationRequirements': []},
   'valueSemantics': [{'fieldKey': 'conceptName',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'conceptDefinition',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'introduction',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'coreValue',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'targetUsers',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'industryCategory',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'researchScope',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'targetRegion',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'revenueModel',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'price',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'channels',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'differentiators',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'preMarketSomShareHypothesis',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'preMarketSomHypothesis',
     'source': 'AI_HYPOTHESIS',
     'authority': 'OPEN',
     'decision': 'PROPOSED'},
    {'fieldKey': 'actorRoles',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'platformRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'problemScenario',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'solutionMechanism',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'featureSet',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'operatingModel',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'partnerModel',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'providerRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'sellerRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'intermediaryRole',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'transactionFlow',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'paymentFlow',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'personalDataUsage',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'physicalActivities',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'partnerRequirements',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'qualificationRequirements',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'},
    {'fieldKey': 'advertisingClaims',
     'source': 'CONCEPT_GENERATED',
     'authority': 'REVIEWABLE',
     'decision': 'PROPOSED'}],
   'canonicalHash': 'sha256:e482e106e6459a3add71072ef0dc1b39cda83bbe0013b2833ad397d0e7357d2d'},
  'finalHypotheses': {'targetRegion': {'value': '대한민국 전역',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'revenueModel': {'value': '구독 모델 및 일회성 구매 모델',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'price': {'value': '1인 기준 5,000원 ~ 15,000원',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'channels': {'value': '온라인 플랫폼 (웹사이트 및 모바일 앱)',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'differentiators': {'value': '고객 맞춤형 레시피 제공, 정기 구독 서비스로 지속적인 고객 유치',
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'preMarketSomShare': {'value': PreMarketSomShareHypothesis(targetSharePercent=15.0, horizonYears=3, rationale='1~2인 가구의 증가와 요리의 간편함을 추구하는 트렌드에 기반하여 시장 점유율을 확보할 수 있다.', assumptions=['1~2인 가구의 수가 증가할 것이다.', '소량 식재료에 대한 수요가 증가할 것이다.']),
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'},
   'preMarketSom': {'value': PreMarketSomHypothesis(amount=5000000.0, currency='KRW', period='1년', calculationBasis='1~2인 가구의 평균 소비자 수와 예상 구매 빈도에 기반하여 추정.', assumptions=['소량 식재료 서비스에 대한 인식이 높아질 것이다.', '고객의 재구매율이 높을 것이다.'], confidence='HIGH'),
    'source': 'AI_HYPOTHESIS',
    'decisionStatus': 'ACCEPTED',
    'proposalVersion': 1,
    'legalImpact': 'NONE',
    'legalReviewStatus': 'NOT_REQUIRED'}},
  'legalResult': {'legalStatus': 'IMPLEMENTABLE_WITH_CONTROLS',
   'safeSummary': '이 사업 모델은 고객 맞춤형 식재료 제공 및 레시피 제공을 통해 안전하게 운영될 수 있으며, 관련 법령을 준수하는 조건 하에 구현이 가능하다.',
   'requiredControls': ['신선한 재료 공급을 위한 지역 농가와의 계약을 체결해야 한다.',
    '식품 안전 기준을 준수해야 한다.',
    '고객의 개인정보를 안전하게 처리하기 위한 정책을 마련해야 한다.',
    '온라인 플랫폼에서의 결제 시스템을 안전하게 운영해야 한다.',
    '고객에게 청약철회 및 거래조건에 대한 정보를 제공해야 한다.',
    '영수증 발급 의무를 준수해야 한다.',
    '약관의 작성 및 설명의무를 준수해야 한다.'],
   'requiredPartnersAndQualifications': ['신선한 재료를 공급할 수 있는 지역 농가와의 계약이 필요하다.',
    '식품 안전 기준을 준수하는 파트너와 협력해야 한다.'],
   'prohibitedVariants': ['기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매는 금지된다.',
    '식품 또는 식품첨가물에 관한 기준 및 규격을 준수하지 않는 경우 판매가 금지된다.',
    '농약 등의 잔류허용기준을 초과하는 식재료의 사용은 금지된다.'],
   'requiredDisclosures': ['고객의 개인정보 처리 방침을 고지해야 한다.',
    '서비스 이용약관을 고객에게 고지해야 한다.'],
   'officialEvidenceReferences': [{'referenceIndex': 0,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001805',
     'officialIdentifier': '277149',
     'lawName': '식품위생법',
     'articleReference': '제6조',
     'title': '기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매 등 금지',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20251001',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:1253eb1604afa3574783b0789f62cc1842b5ba0826a8ad798d27de56d9d07579',
     'boundedProvisionSummary': '기준ㆍ규격이 정하여지지 아니한 화학적 합성품 등의 판매 금지',
     'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 1,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001805',
     'officialIdentifier': '277149',
     'lawName': '식품위생법',
     'articleReference': '제7조',
     'title': '식품 또는 식품첨가물에 관한 기준 및 규격',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20251001',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:2d558b508a0bf2d5f9c1e1af2642c0580d313a0dce3f5c300b4a4b346b573dc6',
     'boundedProvisionSummary': '식품 또는 식품첨가물에 관한 기준 및 규격 설정',
     'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 2,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001805',
     'officialIdentifier': '277149',
     'lawName': '식품위생법',
     'articleReference': '제7조의3',
     'title': '농약 등의 잔류허용기준 설정 요청 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20251001',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:1d5ae9f8190ed5234896f5b5596a792866460e050b0afdf568144d67a5d7cac7',
     'boundedProvisionSummary': '농약 등의 잔류허용기준 설정 요청',
     'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 3,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '001805',
     'officialIdentifier': '277149',
     'lawName': '식품위생법',
     'articleReference': '제7조의4',
     'title': '식품등의 기준 및 규격 관리계획 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%EC%9C%84%EC%83%9D%EB%B2%95',
     'jurisdiction': 'KR',
     'promulgationDate': '20251001',
     'effectiveDate': '20251001',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:93488d5f793d1458d041b00e684b538067fec75d25eb28909cd51c5818c80c9b',
     'boundedProvisionSummary': '식품등의 기준 및 규격 관리계획 수립',
     'queryKey': 'sha256:137b651425ea46750088d433cf3c2a09e7d872244c8aaae1a070c618421311ee',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 4,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '013094',
     'officialIdentifier': '269957',
     'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
     'articleReference': '제4조',
     'title': '표시의 기준',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250318',
     'effectiveDate': '20250919',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:7ab3b3609ddb05ab291bdd9e67d5ed58e4dc15e6731eba81681e3c41710a56fd',
     'boundedProvisionSummary': '식품등의 표시 기준 설정',
     'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 5,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '013094',
     'officialIdentifier': '269957',
     'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
     'articleReference': '제4조의2',
     'title': '시각ㆍ청각장애인을 위한 점자 및 음성ㆍ수어영상변환용 코드의 표시',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250318',
     'effectiveDate': '20250919',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:4591f32b2c11e98d98a4b972b6743b3a6d0f9e041212de12547a120053c93096',
     'boundedProvisionSummary': '시각ㆍ청각장애인을 위한 점자 및 음성ㆍ수어영상변환용 코드의 표시',
     'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 6,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '013094',
     'officialIdentifier': '269957',
     'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
     'articleReference': '제5조',
     'title': '영양표시',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250318',
     'effectiveDate': '20250919',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:ccae8d1b46cf70df431217ea23ceb114e94a24c651c746d9b44ca585d561bef0',
     'boundedProvisionSummary': '영양표시 의무',
     'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 7,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '013094',
     'officialIdentifier': '269957',
     'lawName': '식품 등의 표시ㆍ광고에 관한 법률',
     'articleReference': '제6조',
     'title': '나트륨 함량 비교 표시',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%8B%9D%ED%92%88%20%EB%93%B1%EC%9D%98%20%ED%91%9C%EC%8B%9C%E3%86%8D%EA%B4%91%EA%B3%A0%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20250318',
     'effectiveDate': '20250919',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:d719f3435b365a553bbf3fc847b4f0558dd1326ce8932ffb7a9182f1db0bd6d7',
     'boundedProvisionSummary': '나트륨 함량 비교 표시 의무',
     'queryKey': 'sha256:f68bf83bc5b54e834af01fb823c32fc5732fc6870f20fc0f28968dd99cb13364',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 8,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제12조',
     'title': '통신판매업자의 신고 등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:448fe0bd6a72942700268999bc17abaf1a130dc75ff98338f016366ffccb8d53',
     'boundedProvisionSummary': '통신판매업자의 신고 의무',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 9,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제13조',
     'title': '신원 및 거래조건에 대한 정보의 제공',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:6e496bba7781eda4a1e42db7cb6ead3a7f9648a8557ee96ea09e290d3f30b30d',
     'boundedProvisionSummary': '신원 및 거래조건에 대한 정보 제공 의무',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 10,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제17조',
     'title': '청약철회등',
     'officialSourceUri': 'https://www.law.go.kr/법령/%EC%A0%84%EC%9E%90%EC%83%81%EA%B1%B0%EB%9E%98%20%EB%93%B1%EC%97%90%EC%84%9C%EC%9D%98%20%EC%86%8C%EB%B9%84%EC%9E%90%EB%B3%B4%ED%98%B8%EC%97%90%20%EA%B4%80%ED%95%9C%20%EB%B2%95%EB%A5%A0',
     'jurisdiction': 'KR',
     'promulgationDate': '20260120',
     'effectiveDate': '20260721',
     'retrievedAt': '2026-08-10T02:16:53.380434Z',
     'contentHash': 'sha256:086921e6e5bc694ea2d723423f266762b50490e33b8739d64e1920b7a13bde5c',
     'boundedProvisionSummary': '청약철회 등의 권리 안내',
     'queryKey': 'sha256:602e295f16136be3303188937186db5e352b09cf13eb7009076c93ed7530c296',
     'registryVersion': 'legal-registry-v1'},
    {'referenceIndex': 11,
     'sourceType': 'OFFICIAL_LAW',
     'lawId': '009318',
     'officialIdentifier': '282793',
     'lawName': '전자상거래 등에서의 소비자보호에 관한 법률',
     'articleReference': '제18조',
     'title': '청약철회등의 효과',

## 41. Trace

In [42]:
display(show_trace(engine.trace))

,순서,시각,stage,action,entity,parent,status,mode,호출,요약,decision,reasonCode
0,1,2026-08-10T02:14:42.160597+00:00,CREATED,CREATED,NaN,NaN,RUNNING,LIVE,NaN,V2 Lab 실행을 생성했습니다.,NaN,NaN
1,2,2026-08-10T02:14:47.017854+00:00,SAFETY_CHECKING,IDEA_BRIEF_DERIVED,NaN,NaN,PASS,LIVE,1.0,Idea interpretation/readiness를 보존했습니다: READY_F...,NaN,NaN
2,3,2026-08-10T02:14:47.017881+00:00,SAFETY_CHECKING,READINESS_INCONSISTENT,NaN,NaN,WARNING,LIVE,NaN,READY_FOR_REVIEW이지만 score=0입니다. V2 gating은 막지 ...,READINESS_INCONSISTENT,NaN
3,4,2026-08-10T02:14:47.093090+00:00,SEED_ANALYZING,ANALYZED,lab-idea-brief,NaN,PASS,LIVE,NaN,필수 3개와 LOCK 3개를 분류했습니다.,NaN,NaN
4,5,2026-08-10T02:14:47.093341+00:00,SEED_ANALYZING,DESIGN_SPACE_READY,NaN,NaN,PASS,LIVE,NaN,Open=11 Constrained=0 Breadth=EXPLORE,NaN,NaN
5,6,2026-08-10T02:14:47.151385+00:00,PLANNING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,최대 5개 동적 plan을 요청합니다.,NaN,NaN
6,7,2026-08-10T02:15:13.535005+00:00,PLANNING,DRAFTS_GENERATED,NaN,NaN,PASS,LIVE,2.0,Plan draft pool=6,NaN,NaN
7,8,2026-08-10T02:15:13.536923+00:00,PLANNING,NORMALIZED,NaN,NaN,PASS,LIVE,NaN,System metadata를 부여한 Plan=6,NaN,NaN
8,9,2026-08-10T02:15:19.572137+00:00,PLANNING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,3.0,low-confidence Plan architecture 6개를 batch 분류했...,NaN,NaN
9,10,2026-08-10T02:15:19.572180+00:00,PLAN_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Opportunity·LOCK·DUPLICATE/VARIANT/DISTINCT 관계...,NaN,NaN
10,11,2026-08-10T02:15:19.576302+00:00,PLAN_VALIDATING,SELECTED,NaN,NaN,PASS,LIVE,NaN,Plans=5 Rejected=0,NaN,NaN
11,12,2026-08-10T02:15:29.551466+00:00,EXPANDING,EXPANDED,C1,P3,PASS,LIVE,4.0,P3 → C1,NaN,NaN
12,13,2026-08-10T02:15:38.759903+00:00,EXPANDING,EXPANDED,C2,P1,PASS,LIVE,5.0,P1 → C2,NaN,NaN
13,14,2026-08-10T02:15:48.460777+00:00,EXPANDING,EXPANDED,C3,P6,PASS,LIVE,6.0,P6 → C3,NaN,NaN
14,15,2026-08-10T02:15:56.790859+00:00,EXPANDING,EXPANDED,C4,P2,PASS,LIVE,7.0,P2 → C4,NaN,NaN
15,16,2026-08-10T02:16:05.959211+00:00,EXPANDING,EXPANDED,C5,P4,PASS,LIVE,8.0,P4 → C5,NaN,NaN
16,17,2026-08-10T02:16:06.026181+00:00,CANDIDATE_VALIDATING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 검사를 분리 수행합니다.,NaN,NaN
17,18,2026-08-10T02:16:14.866686+00:00,CANDIDATE_VALIDATING,ARCHITECTURE_SEMANTIC_FALLBACK,NaN,NaN,PASS,LIVE,9.0,low-confidence Candidate architecture 5개를 batc...,NaN,NaN
18,19,2026-08-10T02:16:14.867264+00:00,CANDIDATE_VALIDATING,FIDELITY_AMBIGUOUS,C1,NaN,RUNNING,LIVE,NaN,lexical 판정이 불확실해 semantic fidelity를 요청합니다.,NaN,CANDIDATE_FIDELITY_RECOVERABLE
19,20,2026-08-10T02:16:16.816178+00:00,CANDIDATE_VALIDATING,SEMANTIC_FIDELITY_CHECKED,C1,NaN,PASS,LIVE,10.0,"개인 맞춤형 소량 식재료와 활용 레시피를 제공하는 서비스로, 1~2인 가구의 요리 ...",PASS,NaN
20,21,2026-08-10T02:16:16.816228+00:00,CANDIDATE_VALIDATING,VALIDATED,C1,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
21,22,2026-08-10T02:16:16.817201+00:00,CANDIDATE_VALIDATING,VALIDATED,C2,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
22,23,2026-08-10T02:16:16.818098+00:00,CANDIDATE_VALIDATING,VALIDATED,C3,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
23,24,2026-08-10T02:16:16.819629+00:00,CANDIDATE_VALIDATING,VALIDATED,C4,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
24,25,2026-08-10T02:16:16.820721+00:00,CANDIDATE_VALIDATING,VALIDATED,C5,NaN,PASS,LIVE,NaN,검사 통과,NaN,NaN
25,26,2026-08-10T02:16:16.820775+00:00,CANDIDATE_VALIDATING,CANDIDATE_PORTFOLIO_READY,NaN,NaN,PASS,LIVE,NaN,"Candidate Portfolio=5/5, recovered=0",READY_FULL,NaN
26,27,2026-08-10T02:16:16.867185+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_STARTED,NaN,NaN,RUNNING,LIVE,NaN,Candidate 5개의 법률 사실패턴 완결성을 검사합니다.,NaN,NaN
27,28,2026-08-10T02:16:16.867802+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C1,NaN,COMPLETE,LIVE,NaN,법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.,COMPLETE,NaN
28,29,2026-08-10T02:16:16.868241+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C2,NaN,COMPLETE,LIVE,NaN,법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.,COMPLETE,NaN
29,30,2026-08-10T02:16:16.868681+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C3,NaN,COMPLETE,LIVE,NaN,법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.,COMPLETE,NaN
30,31,2026-08-10T02:16:16.869042+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C4,NaN,COMPLETE,LIVE,NaN,법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.,COMPLETE,NaN
31,32,2026-08-10T02:16:16.869446+00:00,LEGAL_RECOVERING,LEGAL_FACT_COMPLETENESS_CHECKED,C5,NaN,COMPLETE,LIVE,NaN,법률 사전검토에 필요한 사업 사실패턴이 구조적으로 완결되었습니다.,COMPLETE,NaN
32,33,2026-08-10T02:17:04.473655+00:00,LEGAL_REVIEWING,REVIEWED,C1,NaN,ACCEPT,LIVE,11.0,이 사업 모델은 고객 맞춤형 식재료 제공 및 레시피 제공을 통해 안전하게 운영될 수...,ACCEPT,NaN
33,34,2026-08-10T02:17:04.492691+00:00,LEGAL_RECOVERING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Legal route별 복구를 수행합니다.,NaN,NaN
34,35,2026-08-10T02:17:04.521750+00:00,LEGAL_REVIEWING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,공식 Legal contract route를 실행합니다.,NaN,NaN
35,36,2026-08-10T02:17:31.435692+00:00,LEGAL_REVIEWING,REVIEWED,C2,NaN,ACCEPT,LIVE,12.0,이 사업 모델은 고객 맞춤형 식재료 제공 및 음식물 쓰레기 감소에 기여하는 서비스를...,ACCEPT,NaN
36,37,2026-08-10T02:17:46.584158+00:00,LEGAL_REVIEWING,REVIEWED,C3,NaN,ACCEPT,LIVE,13.0,이 사업 모델은 고객 맞춤형 식재료 제공 및 정기 구독 서비스를 통해 법적 요구사항...,ACCEPT,NaN
37,38,2026-08-10T02:17:58.734558+00:00,LEGAL_REVIEWING,REVIEWED,C4,NaN,NEEDS_INPUT,LIVE,14.0,Concept가 결정할 수 없는 외부 현실 사실의 확인이 필요합니다.,NEEDS_INPUT,NaN
38,39,2026-08-10T02:18:21.822548+00:00,LEGAL_REVIEWING,REVIEWED,C5,NaN,ACCEPT,LIVE,15.0,"이 사업 모델은 고객 맞춤형 식재료 제공 및 온라인 플랫폼을 통한 주문 관리로, 관...",ACCEPT,NaN
39,40,2026-08-10T02:18:21.822571+00:00,LEGAL_RECOVERING,STARTED,NaN,NaN,RUNNING,LIVE,NaN,Legal route별 복구를 수행합니다.,NaN,NaN
40,41,2026-08-10T02:18:21.973060+00:00,PORTFOLIO_VALIDATING,HANDOFF_VALIDATED,C1,NaN,PASS,LIVE,NaN,downstream contract compatibility=PASS,NaN,NaN

## 42. Provider/Legal Usage

In [43]:
display(show_provider_usage(engine.gateway.usage))
print('상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.')

,논리 작업,상위 외부 작업,논리 stage별,상위 외부 작업 stage별,재시도,소요(ms),모드별,token,보고 비용
0,15,15,"{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...","{'SAFETY_CHECKING': 1, 'PLANNING': 1, 'NORMALI...",0,219108,{'LIVE': 15},None,None

상위 외부 작업 수는 내부 AI/MOLEG 네트워크 호출 수와 동일하다고 주장하지 않습니다.

## 43. Replay Manifest

In [44]:
display(show_replay_manifest(engine.gateway))

{'status': 'REPLAY_PARTIAL',
 'entries':                   operation  \
 0                 PLAN_POOL
 1                 PLAN_POOL
 2         SEMANTIC_RELATION
 3   NORMALIZE_ARCHITECTURES
 4     IDEA_BRIEF_DERIVATION
 ..                      ...
 73                 REDESIGN
 74                   EXPAND
 75                   EXPAND
 76                 REDESIGN
 77                   EXPAND

                                                  hash operationVersion  \
 0   038e1d9753b8c07ad835823495b54906a14fb6542c3c70...               v3
 1   03b73ea7d485636893670a848e28d49e239cc8bc0c5239...             v2.1
 2   05680e1eabb667cd53d8bbde75192650b626fd5dfaa3fd...               v3
 3   07ba75e844ed104c5fc7d25bf69f296244d0925e2f8916...               v1
 4   07c6209c7795158bce16bf1d386c8f6cd1322277337ef9...               v2
 ..                                                ...              ...
 73  e1f00b4299a6f184485ef2e095448c90d70b545e62eeb2...               v3
 74  f70dd87bc47ba34a9d5de29b772a86ed726c800f928769...               v3
 75  fa3806ec6a088c6605461f5c94b877d4038d6d51a2faa2...               v3
 76  fb3d9fe4d14b27f3087a013761b18ba1d2e7b680c90c17...               v3
 77  fb6986c6b42d538d7e6633cd0b5e8695331b5eab5748d2...              NaN

                                    promptVersion schemaVersion  recordExists  \
 0              concept-portfolio-generic-plan-v3           2.0          True
 1                    concept-portfolio-plan-v2.1           2.0          True
 2                  concept-portfolio-relation-v3           2.0          True
 3   concept-portfolio-architecture-classifier-v1           2.0          True
 4                          idea-brief-current-v2           2.0          True
 ..                                           ...           ...           ...
 73                           concept-redesign-v3           2.0          True
 74        concept-portfolio-generic-candidate-v3           2.0          True
 75        concept-portfolio-generic-candidate-v3           2.0          True
 76                           concept-redesign-v3           2.0          True
 77                                           NaN           2.0          True

                            timestamp  versionCompatible
 0   2026-08-10T02:15:13.524746+00:00               True
 1   2026-08-09T22:07:18.877351+00:00               True
 2   2026-08-09T23:08:53.044335+00:00               True
 3   2026-08-10T01:11:25.716946+00:00               True
 4   2026-08-10T02:14:47.016410+00:00               True
 ..                               ...                ...
 73  2026-08-10T00:16:12.143934+00:00               True
 74  2026-08-10T01:11:14.702780+00:00               True
 75  2026-08-10T00:13:24.693228+00:00               True
 76  2026-08-10T00:15:48.771228+00:00               True
 77  2026-08-09T15:57:14.211269+00:00              False

 [78 rows x 8 columns]}

## 44. One-click MOCK

In [45]:
mock_result = await ConceptPortfolioEngine('MOCK').run_full(
    TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=True)
display(show_run_summary(mock_result))
assert mock_result.handoff and mock_result.handoff.contractStatus == 'CONTRACT_PASS'

,safety,requestedMaximum,planned,planDuplicatesRemoved,candidatesExpanded,candidateGenerated,candidateAcceptedInitially,candidateRegenerated,candidateRecovered,reservePlansActivated,...,legalReplanExhausted,legalAccepted,legalRedesigned,replanned,finalPortfolio,portfolioStatus,selectedConcept,downstreamHandoff,providerCalls,totalDurationMs
0,PASS,5,7,0,5,5,5,0,0,0,...,0,5,0,0,5,READY_FULL,직접 운영 핵심형,PASS,0,63

## 45. One-click REPLAY

In [46]:
RUN_ONE_CLICK_REPLAY = False
replay_result = None
if RUN_ONE_CLICK_REPLAY:
    replay_gateway = ProviderGateway('REPLAY', recordings_dir=RECORDINGS_DIR)
    replay_result = await ConceptPortfolioEngine('REPLAY', gateway=replay_gateway).run_full(
        TEST_INPUT, max_concepts=MAX_CONCEPTS, auto_confirm_hypotheses=False)
display(show_run_summary(replay_result) if replay_result else {'status': 'SKIPPED'})

{'status': 'SKIPPED'}

## 46. One-click LIVE

In [48]:
RUN_ONE_CLICK_LIVE = True
live_result = None
if RUN_ONE_CLICK_LIVE:
    assert MODE == 'LIVE', 'MODE=LIVE를 먼저 명시하세요.'
    assert RUN_FULL_LEGAL_C1 and RUN_REMAINING_LEGAL, 'staged LIVE Legal 확인이 먼저입니다.'
    live_result = await engine.run_full(TEST_INPUT, max_concepts=MAX_CONCEPTS,
                                        auto_confirm_hypotheses=False)
display(show_run_summary(live_result) if live_result else {'status': 'SKIPPED'})

  portfolioStatus  finalPortfolio downstreamHandoff
0          FAILED               0           INVALID